package importmanifest

import (
	"encoding/json"
	"fmt"

	"gopkg.in/yaml.v3"

	"github.com/rudderlabs/rudder-iac/cli/internal/project/specs"
)

// FileName is the name of the generated import-manifest file.
const FileName = "import-manifest.yaml"

// ManifestHeaderComment is rendered at the top of the generated import-manifest
// file to discourage hand-edits, since the importer regenerates it.
const ManifestHeaderComment = " This is a project-level import manifest, generated by rudder-cli import.\n" +
	" It maps local resource URNs to remote IDs so apply reconciles them as imports.\n" +
	" Do not edit unless required."

// ImportEntry is a single URN → remote-ID mapping for a workspace, emitted by
// the export path. Providers return these alongside the specs they format so
// the importer can aggregate them into one import-manifest (see BuildSpec).
type ImportEntry struct {
	WorkspaceID string
	URN         string
	RemoteID    string
}

// BuildSpec groups export entries by workspace (preserving first-seen order)
// into an import-manifest spec. Returns nil when there are no entries. The
// produced spec round-trips through parseWorkspaces.
func BuildSpec(entries []ImportEntry) *specs.Spec {
	if len(entries) == 0 {
		return nil
	}

	order := make([]string, 0)
	byWorkspace := make(map[string]*specs.WorkspaceImportMetadata)
	for _, e := range entries {
		ws, ok := byWorkspace[e.WorkspaceID]
		if !ok {
			ws = &specs.WorkspaceImportMetadata{WorkspaceID: e.WorkspaceID}
			byWorkspace[e.WorkspaceID] = ws
			order = append(order, e.WorkspaceID)
		}
		ws.Resources = append(ws.Resources, specs.ImportIds{URN: e.URN, RemoteID: e.RemoteID})
	}

	workspaces := make([]specs.WorkspaceImportMetadata, 0, len(order))
	for _, id := range order {
		workspaces = append(workspaces, *byWorkspace[id])
	}

	metadata := specs.Metadata{Name: "import-manifest"}
	metadataMap, err := metadata.ToMap()
	if err != nil {
		// Metadata.ToMap only round-trips a fixed struct through JSON; it cannot
		// fail for this literal. Guard defensively rather than panic.
		return nil
	}

	specBody, err := workspacesToMap(specs.WorkspacesImportMetadata{Workspaces: workspaces})
	if err != nil {
		return nil
	}

	return &specs.Spec{
		Version:  specs.SpecVersionV1,
		Kind:     KindImportManifest,
		Metadata: metadataMap,
		Spec:     specBody,
	}
}

// BuildNode builds the import-manifest as a YAML node carrying the header
// comment, ready to be written to disk. Returns nil (no node, no error) when
// there are no entries. The node encodes the same spec BuildSpec produces, so
// it round-trips through parseWorkspaces.
func BuildNode(entries []ImportEntry) (*yaml.Node, error) {
	spec := BuildSpec(entries)
	if spec == nil {
		return nil, nil
	}

	var node yaml.Node
	if err := node.Encode(spec); err != nil {
		return nil, fmt.Errorf("encoding import-manifest spec to YAML node: %w", err)
	}
	// node is a mapping node here (Encode of a struct). The head comment renders
	// as leading `#` lines above the first key.
	node.HeadComment = ManifestHeaderComment
	return &node, nil
}

// workspacesToMap converts the workspaces payload to the generic map shape that
// specs.Spec.Spec carries (and that parseWorkspaces decodes). The yaml and json
// tags on the specs types are identical, so the JSON round-trip yields the same
// keys parseWorkspaces expects.
func workspacesToMap(w specs.WorkspacesImportMetadata) (map[string]any, error) {
	b, err := json.Marshal(w)
	if err != nil {
		return nil, fmt.Errorf("marshaling workspaces: %w", err)
	}
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, fmt.Errorf("unmarshaling workspaces: %w", err)
	}
	return m, nil
}
