/**
 * This client was automatically generated by RudderTyper. ** Do Not Edit **
 */

import type {
  RudderAnalytics,
  RudderAnalyticsPreloader,
  ApiOptions,
  ApiObject,
} from '@rudderstack/analytics-js';
/**
 * The analytics instance should be available via window.rudderanalytics.
 * You can install it by following instructions at: https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/installation/
 */
declare global {
  interface Window {
    rudderanalytics: RudderAnalytics | RudderAnalyticsPreloader | undefined;
  }
}

type apiCallback = (data?: any) => void;

export enum Someintegerwithenum_Integer {
  N_200 = 200,
  N_201 = 201,
  N_204 = 204,
  N_400 = 400,
  N_401 = 401,
  N_403 = 403,
  N_404 = 404,
  N_500 = 500,
}

export enum Somestringwithenum_String {
  S_GET = 'GET',
  S_PUT = 'PUT',
  S_POST = 'POST',
  S_DELETE = 'DELETE',
  S_PATCH = 'PATCH',
}

export interface SomeTrackEventSomeNestedLevel2 {
  someBoolean?: boolean;
  someInteger?: number;
  someNumber?: number;
  someObject?: Record<string, any>;
  someString?: string;
}

export interface SomeTrackEventSomeNestedLevel1 {
  someNestedLevel2?: SomeTrackEventSomeNestedLevel2;
}

export interface SomeTrackEventSomeNestedObject {
  someNestedLevel1?: SomeTrackEventSomeNestedLevel1;
}

export interface SomeTrackEvent {
  someArray?: any[];
  someArrayOfBooleans?: boolean[];
  someArrayOfIntegers?: number[];
  someArrayOfMultipleTypes?: boolean | number | number | string[];
  someArrayOfNumbers?: number[];
  someArrayOfStrings?: string[];
  someBoolean: boolean;
  someCustomArray?: CustomTypeDefs['SomeArrayType'];
  someCustomBoolean?: CustomTypeDefs['SomeBooleanType'];
  someCustomInteger?: CustomTypeDefs['SomeIntegerType'];
  someCustomNumber?: CustomTypeDefs['SomeNumberType'];
  someCustomObject?: CustomTypeDefs['SomeObjectType'];
  someCustomString?: CustomTypeDefs['SomeStringType'];
  someInteger: number;
  someIntegerWithEnum?: Someintegerwithenum_Integer;
  someMultiType?: any[] | boolean | number | number | Record<string, any> | string | null;
  someNestedObject?: SomeTrackEventSomeNestedObject;
  someNumber: number;
  someObject: Record<string, any>;
  someString: string;
  someStringWithEnum?: Somestringwithenum_String;
  someVariantType?: CustomTypeDefs['SomeVariantType'];
}

export interface SomeTrackEventWithVariants {
  someInteger?: number;
  someString: string;
}

export interface CustomTypeDefsSomeObjectType {
  someCustomString: CustomTypeDefs['SomeStringType'];
  someInteger?: number;
}

export interface CustomTypeDefsSomeVariantType {
  someInteger?: number;
  someString: string;
}

export type ViolationHandler = (message: Record<string, any>, violations: any[]) => void;

let analytics: () => any | undefined = () => {
  return window.rudderanalytics;
};

/** Options to customize the runtime behavior of a RudderTyper client. */
export interface RudderTyperOptions {
  /**
   * Underlying analytics instance where analytics calls are forwarded on to.
   * Defaults to window.rudderanalytics.
   */
  analytics?: any;
  /**
   * Handler fired when if an event does not match its spec. This handler
   * does not fire in production mode, because it requires inlining the full
   * JSON Schema spec for each event in your Tracking Plan.
   *
   * By default, it will throw errors if NODE_ENV = "test" so that tests will fail
   * if a message does not match the spec. Otherwise, errors will be logged to stderr.
   */
  onViolation?: ViolationHandler;
}

/**
 * Updates the run-time configuration of this RudderTyper client.
 *
 * @param {RudderTyperOptions} options - the options to upsert
 *
 * @typedef {Object} RudderTyperOptions
 * @property {Rudder.AnalyticsJS} [analytics] - Underlying analytics instance where analytics
 * 		calls are forwarded on to. Defaults to window.analytics.
 * @property {Function} [onViolation] - Handler fired when if an event does not match its spec. This handler does not fire in
 * 		production mode, because it requires inlining the full JSON Schema spec for each event in your Tracking Plan. By default,
 * 		it will throw errors if NODE_ENV="test" so that tests will fail if a message does not match the spec. Otherwise, errors
 * 		will be logged to stderr.
 */
export function setRudderTyperOptions(options: RudderTyperOptions) {
  analytics = options.analytics ? () => options.analytics || window.rudderanalytics : analytics;
}

/**
 * Helper to attach metadata on RudderTyper to outbound requests.
 * This is used for attribution and debugging by the RudderStack team.
 */
function withRudderTyperContext(message: ApiOptions = {}): ApiOptions {
  return {
    ...message,
    context: {
      ...((message.context as ApiObject) || {}),
      ruddertyper: {
        sdk: 'analytics.js',
        language: 'typescript',
        rudderTyperVersion: '1.7.3',
        trackingPlanId: 'tp_36gukfnRQ95IMVzwvFx2qcASpd3',
        trackingPlanVersion: 2,
      },
    },
  };
}

export interface CustomTypeDefs {
  SomeArrayType?: any[];
  SomeBooleanType?: boolean;
  SomeIntegerType?: number;
  SomeNumberType?: number;
  SomeObjectType?: CustomTypeDefsSomeObjectType;
  SomeStringType?: string;
  SomeVariantType?: CustomTypeDefsSomeVariantType;
}

/**
 * @typedef SomeTrackEventSomeNestedLevel2
 * @property {boolean} [someBoolean] -
 * @property {number} [someInteger] -
 * @property {number} [someNumber] -
 * @property {Record<string, any>} [someObject] -
 * @property {string} [someString] -
 */
/**
 * @typedef SomeTrackEventSomeNestedLevel1
 * @property {SomeTrackEventSomeNestedLevel2} [someNestedLevel2] -
 */
/**
 * @typedef SomeTrackEventSomeNestedObject
 * @property {SomeTrackEventSomeNestedLevel1} [someNestedLevel1] -
 */
/**
 * @typedef SomeTrackEvent
 * @property {any[]} [someArray] -
 * @property {boolean[]} [someArrayOfBooleans] -
 * @property {number[]} [someArrayOfIntegers] -
 * @property {boolean | number | number | string[]} [someArrayOfMultipleTypes] -
 * @property {number[]} [someArrayOfNumbers] -
 * @property {string[]} [someArrayOfStrings] -
 * @property {boolean} someBoolean -
 * @property {CustomTypeDefs['SomeArrayType']} [someCustomArray] -
 * @property {CustomTypeDefs['SomeBooleanType']} [someCustomBoolean] -
 * @property {CustomTypeDefs['SomeIntegerType']} [someCustomInteger] -
 * @property {CustomTypeDefs['SomeNumberType']} [someCustomNumber] -
 * @property {CustomTypeDefs['SomeObjectType']} [someCustomObject] -
 * @property {CustomTypeDefs['SomeStringType']} [someCustomString] -
 * @property {number} someInteger -
 * @property {Someintegerwithenum_Integer} [someIntegerWithEnum] -
 * @property {any[] | boolean | number | number | Record<string, any> | string | null} [someMultiType] -
 * @property {SomeTrackEventSomeNestedObject} [someNestedObject] -
 * @property {number} someNumber -
 * @property {Record<string, any>} someObject -
 * @property {string} someString -
 * @property {Somestringwithenum_String} [someStringWithEnum] -
 * @property {CustomTypeDefs['SomeVariantType']} [someVariantType] -
 */
/**
 * @typedef SomeTrackEventWithVariants
 * @property {number} [someInteger] -
 * @property {string} someString -
 */
/**
 * @typedef CustomTypeDefsSomeObjectType
 * @property {CustomTypeDefs['SomeStringType']} someCustomString -
 * @property {number} [someInteger] -
 */
/**
 * @typedef CustomTypeDefsSomeVariantType
 * @property {number} [someInteger] -
 * @property {string} someString -
 */

/**
 * This is a track event with no properties for testing.
 *
 * @param {Record<string, any>} [props] - The analytics properties that will be sent to RudderStack.
 * @param {Object} [options] - A dictionary of options. For example, enable or disable specific destinations for the call.
 * @param {Function} [callback] - An optional callback called after a short timeout after the analytics call is fired.
 */
export function someEmptyTrackEvent(
  props?: Record<string, any>,
  options?: ApiOptions,
  callback?: apiCallback,
): void {
  const a = analytics();

  if (a) {
    a.track('Some Empty Track Event', props || {}, withRudderTyperContext(options), callback);
  }
}
/**
 * This is a track event with no properties but with additional properties for testing.
 *
 * @param {Record<string, any>} [props] - The analytics properties that will be sent to RudderStack.
 * @param {Object} [options] - A dictionary of options. For example, enable or disable specific destinations for the call.
 * @param {Function} [callback] - An optional callback called after a short timeout after the analytics call is fired.
 */
export function someEmptyTrackEventWithAdditionalProperties(
  props?: Record<string, any>,
  options?: ApiOptions,
  callback?: apiCallback,
): void {
  const a = analytics();

  if (a) {
    a.track(
      'Some Empty Track Event With Additional Properties',
      props || {},
      withRudderTyperContext(options),
      callback,
    );
  }
}
/**
 * This is a track event for testing.
 *
 * @param {SomeTrackEvent} props - The analytics properties that will be sent to RudderStack.
 * @param {Object} [options] - A dictionary of options. For example, enable or disable specific destinations for the call.
 * @param {Function} [callback] - An optional callback called after a short timeout after the analytics call is fired.
 */
export function someTrackEvent(
  props: SomeTrackEvent,
  options?: ApiOptions,
  callback?: apiCallback,
): void {
  const a = analytics();

  if (a) {
    a.track('Some Track Event', props || {}, withRudderTyperContext(options), callback);
  }
}
/**
 * This is a track event with variants for testing.
 *
 * @param {SomeTrackEventWithVariants} props - The analytics properties that will be sent to RudderStack.
 * @param {Object} [options] - A dictionary of options. For example, enable or disable specific destinations for the call.
 * @param {Function} [callback] - An optional callback called after a short timeout after the analytics call is fired.
 */
export function someTrackEventWithVariants(
  props: SomeTrackEventWithVariants,
  options?: ApiOptions,
  callback?: apiCallback,
): void {
  const a = analytics();

  if (a) {
    a.track(
      'Some Track Event With Variants',
      props || {},
      withRudderTyperContext(options),
      callback,
    );
  }
}

const clientAPI = {
  /**
   * Updates the run-time configuration of this RudderTyper client.
   *
   * @param {RudderTyperOptions} options - the options to upsert
   *
   * @typedef {Object} RudderTyperOptions
   * @property {Rudder.AnalyticsJS} [analytics] - Underlying analytics instance where analytics
   * 		calls are forwarded on to. Defaults to window.analytics.
   * @property {Function} [onViolation] - Handler fired when if an event does not match its spec. This handler does not fire in
   * 		production mode, because it requires inlining the full JSON Schema spec for each event in your Tracking Plan. By default,
   * 		it will throw errors if NODE_ENV="test" so that tests will fail if a message does not match the spec. Otherwise, errors
   * 		will be logged to stderr.
   */
  setRudderTyperOptions,
  /**
   * This is a track event with no properties for testing.
   *
   * @param {Record<string, any>} [props] - The analytics properties that will be sent to RudderStack.
   * @param {Object} [options] - A dictionary of options. For example, enable or disable specific destinations for the call.
   * @param {Function} [callback] - An optional callback called after a short timeout after the analytics call is fired.
   */
  someEmptyTrackEvent,
  /**
   * This is a track event with no properties but with additional properties for testing.
   *
   * @param {Record<string, any>} [props] - The analytics properties that will be sent to RudderStack.
   * @param {Object} [options] - A dictionary of options. For example, enable or disable specific destinations for the call.
   * @param {Function} [callback] - An optional callback called after a short timeout after the analytics call is fired.
   */
  someEmptyTrackEventWithAdditionalProperties,
  /**
   * This is a track event for testing.
   *
   * @param {SomeTrackEvent} props - The analytics properties that will be sent to RudderStack.
   * @param {Object} [options] - A dictionary of options. For example, enable or disable specific destinations for the call.
   * @param {Function} [callback] - An optional callback called after a short timeout after the analytics call is fired.
   */
  someTrackEvent,
  /**
   * This is a track event with variants for testing.
   *
   * @param {SomeTrackEventWithVariants} props - The analytics properties that will be sent to RudderStack.
   * @param {Object} [options] - A dictionary of options. For example, enable or disable specific destinations for the call.
   * @param {Function} [callback] - An optional callback called after a short timeout after the analytics call is fired.
   */
  someTrackEventWithVariants,
};

export const RudderTyperAnalytics = new Proxy<typeof clientAPI>(clientAPI, {
  get(target, method) {
    if (typeof method === 'string' && Object.keys(target).includes(method)) {
      return target[method as keyof typeof clientAPI];
    }

    return () => {
      const a = analytics();
      if (a) {
        a.track(
          'Unknown Analytics Call Fired',
          {
            method,
          },
          withRudderTyperContext(),
        );
      }
    };
  },
});
