/**
 * This client was automatically generated by RudderTyper. ** Do Not Edit **
 */

import type {
  RudderAnalytics,
  ApiOptions,
  ApiObject,
  ApiCallback,
} from '@rudderstack/analytics-js';

// =============================================================================
// Custom Types
// =============================================================================

/** some array custom type */
type CustomTypeSomeArrayType = any[];

/** some boolean custom type */
type CustomTypeSomeBooleanType = boolean;

/** some integer custom type */
type CustomTypeSomeIntegerType = number;

/** some number custom type */
type CustomTypeSomeNumberType = number;

/** some string custom type */
type CustomTypeSomeStringType = string;

/** some object custom type */
interface CustomTypeSomeObjectType {
  someCustomString: CustomTypeSomeStringType;
  someInteger?: number;
}

// Variant type: Case 1
interface CustomTypeSomeVariantTypeCase1 {
  someString: 'case_1';
  someInteger: number;
}

// Variant type: Case 2a
interface CustomTypeSomeVariantTypeCase2A {
  someString: 'case_2_a';
  someInteger?: number;
  someNumber: number;
}

// Variant type: Case 2b
interface CustomTypeSomeVariantTypeCase2B {
  someString: 'case_2_b';
  someInteger?: number;
  someNumber: number;
}

// Variant type: Default case
interface CustomTypeSomeVariantTypeDefault {
  someString: Exclude<string, 'case_1' | 'case_2_a' | 'case_2_b'>;
  someInteger?: number;
  someBoolean?: boolean;
}

type CustomTypeSomeVariantType =
  | CustomTypeSomeVariantTypeCase1
  | CustomTypeSomeVariantTypeCase2A
  | CustomTypeSomeVariantTypeCase2B
  | CustomTypeSomeVariantTypeDefault;

// =============================================================================
// Property Types
// =============================================================================

type PropertySomeArray = any[];
type PropertySomeArrayOfBooleans = boolean[];
type PropertySomeArrayOfIntegers = number[];
type PropertySomeArrayOfMultipleTypes = (boolean | number | string)[];
type PropertySomeArrayOfNumbers = number[];
type PropertySomeArrayOfStrings = string[];
type PropertySomeBoolean = boolean;
type PropertySomeCustomArray = CustomTypeSomeArrayType;
type PropertySomeCustomBoolean = CustomTypeSomeBooleanType;
type PropertySomeCustomInteger = CustomTypeSomeIntegerType;
type PropertySomeCustomNumber = CustomTypeSomeNumberType;
type PropertySomeCustomObject = CustomTypeSomeObjectType;
type PropertySomeCustomString = CustomTypeSomeStringType;
type PropertySomeInteger = number;
type PropertySomeIntegerWithEnum = 200 | 201 | 204 | 400 | 401 | 403 | 404 | 500;
type PropertySomeMultiType = any[] | boolean | number | Record<string, any> | string | null;
type PropertySomeNumber = number;
type PropertySomeObject = Record<string, never>;
type PropertySomeString = string;
type PropertySomeStringWithEnum = 'GET' | 'PUT' | 'POST' | 'DELETE' | 'PATCH';
type PropertySomeVariantType = CustomTypeSomeVariantType;

// =============================================================================
// Event Properties Interfaces
// =============================================================================

/** Properties for Some Track Event */
interface TrackSomeTrackEventProperties {
  someArray?: PropertySomeArray;
  someArrayOfBooleans?: PropertySomeArrayOfBooleans;
  someArrayOfIntegers?: PropertySomeArrayOfIntegers;
  someArrayOfMultipleTypes?: PropertySomeArrayOfMultipleTypes;
  someArrayOfNumbers?: PropertySomeArrayOfNumbers;
  someArrayOfStrings?: PropertySomeArrayOfStrings;
  someBoolean: PropertySomeBoolean;
  someCustomArray?: PropertySomeCustomArray;
  someCustomBoolean?: PropertySomeCustomBoolean;
  someCustomInteger?: PropertySomeCustomInteger;
  someCustomNumber?: PropertySomeCustomNumber;
  someCustomObject?: PropertySomeCustomObject;
  someCustomString?: PropertySomeCustomString;
  someInteger: PropertySomeInteger;
  someIntegerWithEnum?: PropertySomeIntegerWithEnum;
  someMultiType?: PropertySomeMultiType;
  someNestedObject?: {
    someNestedLevel1?: {
      someNestedLevel2?: {
        someBoolean?: PropertySomeBoolean;
        someInteger?: PropertySomeInteger;
        someNumber?: PropertySomeNumber;
        someObject?: Record<string, never>;
        someString?: PropertySomeString;
      };
    };
  };
  someNumber: PropertySomeNumber;
  someObject: PropertySomeObject;
  someString: PropertySomeString;
  someStringWithEnum?: PropertySomeStringWithEnum;
  someVariantType?: PropertySomeVariantType;
}

// Variant properties for Some Track Event With Variants
interface TrackSomeTrackEventWithVariantsPropertiesCase1 {
  someString: 'case_1';
  someInteger: number;
}

interface TrackSomeTrackEventWithVariantsPropertiesCase2A {
  someString: 'case_2_a';
  someInteger?: number;
  someNumber?: number;
}

interface TrackSomeTrackEventWithVariantsPropertiesCase2B {
  someString: 'case_2_b';
  someInteger?: number;
  someNumber?: number;
}

interface TrackSomeTrackEventWithVariantsPropertiesDefault {
  someString: Exclude<string, 'case_1' | 'case_2_a' | 'case_2_b'>;
  someInteger?: number;
  someBoolean?: boolean;
}

type TrackSomeTrackEventWithVariantsProperties =
  | TrackSomeTrackEventWithVariantsPropertiesCase1
  | TrackSomeTrackEventWithVariantsPropertiesCase2A
  | TrackSomeTrackEventWithVariantsPropertiesCase2B
  | TrackSomeTrackEventWithVariantsPropertiesDefault;

/** Properties for empty track event with additional properties */
type TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties = Record<string, any>;

// =============================================================================
// RudderTyper Analytics Class
// =============================================================================

/**
 * Type-safe RudderStack Analytics client generated from your tracking plan.
 *
 * Usage:
 * ```typescript
 * import { RudderAnalytics } from '@rudderstack/analytics-js';
 * import { RudderTyperAnalytics } from './index';
 *
 * const analytics = new RudderAnalytics();
 * analytics.load('<WRITE_KEY>', '<DATA_PLANE_URL>');
 *
 * const rudderTyper = new RudderTyperAnalytics(analytics);
 * rudderTyper.trackSomeTrackEvent({ someString: 'hello', someInteger: 42, ... });
 * ```
 */
export class RudderTyperAnalytics {
  private analytics: RudderAnalytics;

  constructor(analytics: RudderAnalytics) {
    this.analytics = analytics;
  }

  /**
   * Helper to attach metadata on RudderTyper to outbound requests.
   * This is used for attribution and debugging by the RudderStack team.
   */
  private withRudderTyperContext(message: ApiOptions = {}): ApiOptions {
    return {
      ...message,
      context: {
        ...((message.context as ApiObject) || {}),
        ruddertyper: {
          sdk: 'analytics.js',
          language: 'typescript',
          rudderTyperVersion: '2.0.0',
          trackingPlanId: 'tp_36gukfnRQ95IMVzwvFx2qcASpd3',
          trackingPlanVersion: 2,
        },
      },
    };
  }

  /**
   * This is a track event with no properties for testing.
   *
   * @param options - A dictionary of options. For example, enable or disable specific destinations for the call.
   * @param callback - An optional callback called after a short timeout after the analytics call is fired.
   */
  trackSomeEmptyTrackEvent(): void;
  trackSomeEmptyTrackEvent(callback: ApiCallback): void;
  trackSomeEmptyTrackEvent(options: ApiOptions, callback?: ApiCallback): void;
  trackSomeEmptyTrackEvent(
    optionsOrCallback?: ApiOptions | ApiCallback,
    callback?: ApiCallback,
  ): void {
    let options: ApiOptions | undefined;
    let cb: ApiCallback | undefined;

    if (typeof optionsOrCallback === 'function') {
      cb = optionsOrCallback;
    } else {
      options = optionsOrCallback;
      cb = callback;
    }

    this.analytics.track(
      'Some Empty Track Event',
      {},
      this.withRudderTyperContext(options),
      cb,
    );
  }

  /**
   * This is a track event with no properties but with additional properties for testing.
   *
   * @param props - The analytics properties that will be sent to RudderStack.
   * @param options - A dictionary of options. For example, enable or disable specific destinations for the call.
   * @param callback - An optional callback called after a short timeout after the analytics call is fired.
   */
  trackSomeEmptyTrackEventWithAdditionalProperties(): void;
  trackSomeEmptyTrackEventWithAdditionalProperties(callback: ApiCallback): void;
  trackSomeEmptyTrackEventWithAdditionalProperties(
    props: TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties,
  ): void;
  trackSomeEmptyTrackEventWithAdditionalProperties(
    props: TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties,
    callback: ApiCallback,
  ): void;
  trackSomeEmptyTrackEventWithAdditionalProperties(
    props: TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties,
    options: ApiOptions,
    callback?: ApiCallback,
  ): void;
  trackSomeEmptyTrackEventWithAdditionalProperties(
    propsOrCallback?:
      | TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties
      | ApiCallback,
    optionsOrCallback?: ApiOptions | ApiCallback,
    callback?: ApiCallback,
  ): void {
    let props: TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties = {};
    let options: ApiOptions | undefined;
    let cb: ApiCallback | undefined;

    if (typeof propsOrCallback === 'function') {
      cb = propsOrCallback;
    } else if (propsOrCallback !== undefined) {
      props = propsOrCallback;
      if (typeof optionsOrCallback === 'function') {
        cb = optionsOrCallback;
      } else {
        options = optionsOrCallback;
        cb = callback;
      }
    }

    this.analytics.track(
      'Some Empty Track Event With Additional Properties',
      props,
      this.withRudderTyperContext(options),
      cb,
    );
  }

  /**
   * This is a track event for testing.
   *
   * @param props - The analytics properties that will be sent to RudderStack.
   * @param options - A dictionary of options. For example, enable or disable specific destinations for the call.
   * @param callback - An optional callback called after a short timeout after the analytics call is fired.
   */
  trackSomeTrackEvent(props: TrackSomeTrackEventProperties): void;
  trackSomeTrackEvent(
    props: TrackSomeTrackEventProperties,
    callback: ApiCallback,
  ): void;
  trackSomeTrackEvent(
    props: TrackSomeTrackEventProperties,
    options: ApiOptions,
    callback?: ApiCallback,
  ): void;
  trackSomeTrackEvent(
    props: TrackSomeTrackEventProperties,
    optionsOrCallback?: ApiOptions | ApiCallback,
    callback?: ApiCallback,
  ): void {
    let options: ApiOptions | undefined;
    let cb: ApiCallback | undefined;

    if (typeof optionsOrCallback === 'function') {
      cb = optionsOrCallback;
    } else {
      options = optionsOrCallback;
      cb = callback;
    }

    this.analytics.track(
      'Some Track Event',
      props,
      this.withRudderTyperContext(options),
      cb,
    );
  }

  /**
   * This is a track event with variants for testing.
   *
   * @param props - The analytics properties that will be sent to RudderStack.
   * @param options - A dictionary of options. For example, enable or disable specific destinations for the call.
   * @param callback - An optional callback called after a short timeout after the analytics call is fired.
   */
  trackSomeTrackEventWithVariants(
    props: TrackSomeTrackEventWithVariantsProperties,
  ): void;
  trackSomeTrackEventWithVariants(
    props: TrackSomeTrackEventWithVariantsProperties,
    callback: ApiCallback,
  ): void;
  trackSomeTrackEventWithVariants(
    props: TrackSomeTrackEventWithVariantsProperties,
    options: ApiOptions,
    callback?: ApiCallback,
  ): void;
  trackSomeTrackEventWithVariants(
    props: TrackSomeTrackEventWithVariantsProperties,
    optionsOrCallback?: ApiOptions | ApiCallback,
    callback?: ApiCallback,
  ): void {
    let options: ApiOptions | undefined;
    let cb: ApiCallback | undefined;

    if (typeof optionsOrCallback === 'function') {
      cb = optionsOrCallback;
    } else {
      options = optionsOrCallback;
      cb = callback;
    }

    this.analytics.track(
      'Some Track Event With Variants',
      props,
      this.withRudderTyperContext(options),
      cb,
    );
  }
}

// =============================================================================
// Exported Types
// =============================================================================

export type {
  // Custom Types
  CustomTypeSomeArrayType,
  CustomTypeSomeBooleanType,
  CustomTypeSomeIntegerType,
  CustomTypeSomeNumberType,
  CustomTypeSomeStringType,
  CustomTypeSomeObjectType,
  CustomTypeSomeVariantType,
  // Property Types
  PropertySomeArray,
  PropertySomeArrayOfBooleans,
  PropertySomeArrayOfIntegers,
  PropertySomeArrayOfMultipleTypes,
  PropertySomeArrayOfNumbers,
  PropertySomeArrayOfStrings,
  PropertySomeBoolean,
  PropertySomeCustomArray,
  PropertySomeCustomBoolean,
  PropertySomeCustomInteger,
  PropertySomeCustomNumber,
  PropertySomeCustomObject,
  PropertySomeCustomString,
  PropertySomeInteger,
  PropertySomeIntegerWithEnum,
  PropertySomeMultiType,
  PropertySomeNumber,
  PropertySomeObject,
  PropertySomeString,
  PropertySomeStringWithEnum,
  PropertySomeVariantType,
  // Event Properties
  TrackSomeTrackEventProperties,
  TrackSomeTrackEventWithVariantsProperties,
  TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties,
};
