.nh
.TH "RUDDER-CLI-COMPLETION-ZSH" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-completion-zsh - Generate the autocompletion script for zsh


.SH SYNOPSIS
\fBrudder-cli completion zsh [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for the zsh shell.

.PP
Source the generated script for the current shell or install it in a directory
listed in fpath so new zsh sessions load rudder-cli completions automatically.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for zsh

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
# Load completions for the current shell
source <(rudder-cli completion zsh)

# Install completions for future zsh shells
rudder-cli completion zsh > "${fpath[1]}/_rudder-cli"

.EE


.SH SEE ALSO
\fBrudder-cli-completion(1)\fP
