.nh
.TH "RUDDER-CLI-EXPERIMENTAL-LIST" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-experimental-list - List all available experimental flags


.SH SYNOPSIS
\fBrudder-cli experimental list [flags]\fP


.SH DESCRIPTION
List every available experimental feature flag, its status, and its environment variable.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
RUDDERSTACK_CLI_EXPERIMENTAL=true rudder-cli experimental list

.EE


.SH SEE ALSO
\fBrudder-cli-experimental(1)\fP
