.nh
.TH "RUDDER-CLI" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-telemetry-enable - Enable telemetry


.SH SYNOPSIS
\fBrudder-cli telemetry enable [flags]\fP


.SH DESCRIPTION
Enable anonymous rudder-cli usage and error telemetry in the selected configuration file.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for enable


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
  rudder-cli telemetry enable
.EE


.SH SEE ALSO
\fBrudder-cli-telemetry(1)\fP
