.nh
.TH "RUDDER-CLI-DEBUG" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-debug - Debug commands


.SH SYNOPSIS
\fBrudder-cli debug [flags]\fP


.SH DESCRIPTION
Inspect local CLI diagnostic information. Debug commands require debug mode during normal CLI execution.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for debug


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
RUDDERSTACK_CLI_DEBUG=true rudder-cli debug config

.EE


.SH SEE ALSO
\fBrudder-cli(1)\fP, \fBrudder-cli-debug-config(1)\fP, \fBrudder-cli-debug-config-file(1)\fP, \fBrudder-cli-debug-stacktrace(1)\fP
