.nh
.TH "RUDDER-CLI-RETL-SOURCES" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-retl-sources - Manage RETL sources


.SH SYNOPSIS
\fBrudder-cli retl-sources [flags]\fP


.SH DESCRIPTION
Preview or validate reverse ETL SQL model resources declared in a local project.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for retl-sources


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
rudder-cli retl-sources validate my-model --location ./project

.EE


.SH SEE ALSO
\fBrudder-cli(1)\fP, \fBrudder-cli-retl-sources-preview(1)\fP, \fBrudder-cli-retl-sources-validate(1)\fP
