.nh
.TH "RUDDER-CLI-TELEMETRY-DISABLE" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-telemetry-disable - Disable telemetry


.SH SYNOPSIS
\fBrudder-cli telemetry disable [flags]\fP


.SH DESCRIPTION
Disable anonymous CLI telemetry collection in the local configuration.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for disable


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
rudder-cli telemetry disable

.EE


.SH SEE ALSO
\fBrudder-cli-telemetry(1)\fP
