.nh
.TH "RUDDER-CLI-WORKSPACE-RETL-SOURCES" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-workspace-retl-sources - Manage RETL sources in the workspace


.SH SYNOPSIS
\fBrudder-cli workspace retl-sources [flags]\fP


.SH DESCRIPTION
Inspect reverse ETL sources available in the authenticated workspace.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for retl-sources


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
rudder-cli workspace retl-sources list --json

.EE


.SH SEE ALSO
\fBrudder-cli-workspace(1)\fP, \fBrudder-cli-workspace-retl-sources-list(1)\fP
