.nh
.TH "RUDDER-CLI-WORKSPACE-ACCOUNTS" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-workspace-accounts - Manage accounts in the workspace


.SH SYNOPSIS
\fBrudder-cli workspace accounts [flags]\fP


.SH DESCRIPTION
Inspect source and destination accounts available in the authenticated workspace.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for accounts


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
rudder-cli workspace accounts list --json

.EE


.SH SEE ALSO
\fBrudder-cli-workspace(1)\fP, \fBrudder-cli-workspace-accounts-list(1)\fP
