.nh
.TH "RUDDER-CLI-DEBUG-STACKTRACE" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-debug-stacktrace - Display the last panic stacktrace from the log file


.SH SYNOPSIS
\fBrudder-cli debug stacktrace [flags]\fP


.SH DESCRIPTION
Read the CLI log and display the most recent recorded panic stack trace.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for stacktrace


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
RUDDERSTACK_CLI_DEBUG=true rudder-cli debug stacktrace

.EE


.SH SEE ALSO
\fBrudder-cli-debug(1)\fP
