.nh
.TH "RUDDER-CLI-IMPORT-WORKSPACE" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-import-workspace - Import workspace resources


.SH SYNOPSIS
\fBrudder-cli import workspace [flags]\fP


.SH DESCRIPTION
Import upstream workspace resources using available providers into configuration files


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for workspace

.PP
\fB-l\fP, \fB--location\fP="."
	Path to the directory containing the project files

.PP
\fB--merge\fP[=false]
	Allow import on a diverged project, linking remote resources that match existing local resources (experimental)

.PP
\fB--var-file\fP=[]
	Path to a variable file ending in .vars.yaml or .vars.yml (repeatable; later files take priority)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
rudder-cli import workspace --location ./project
rudder-cli import workspace --location ./project --var-file prod.vars.yaml

.EE


.SH SEE ALSO
\fBrudder-cli-import(1)\fP
