.nh
.TH "RUDDER-CLI" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-workspace-accounts - Inspect accounts in the workspace


.SH SYNOPSIS
\fBrudder-cli workspace accounts [flags]\fP


.SH DESCRIPTION
Inspect account resources available in the authenticated workspace. Use the list subcommand to filter accounts by category or type.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for accounts


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
  rudder-cli workspace accounts list
  rudder-cli workspace accounts list --category destination --json
.EE


.SH SEE ALSO
\fBrudder-cli-workspace(1)\fP, \fBrudder-cli-workspace-accounts-list(1)\fP
