.nh
.TH "RUDDER-CLI-COMPLETION-POWERSHELL" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-completion-powershell - Generate the autocompletion script for powershell


.SH SYNOPSIS
\fBrudder-cli completion powershell [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for PowerShell.

.PP
The generated script can be evaluated for the current session or added to your
PowerShell profile so new sessions load rudder-cli completions automatically.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for powershell

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
# Load completions for the current shell
rudder-cli completion powershell | Out-String | Invoke-Expression

.EE


.SH SEE ALSO
\fBrudder-cli-completion(1)\fP
