.nh
.TH "RUDDER-CLI" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-workspace-tracking-plans - Inspect tracking plans in the workspace


.SH SYNOPSIS
\fBrudder-cli workspace tracking-plans [flags]\fP


.SH DESCRIPTION
Inspect tracking plans in the authenticated workspace. Use the list subcommand for table or JSON output.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for tracking-plans


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
  rudder-cli workspace tracking-plans list --json
.EE


.SH SEE ALSO
\fBrudder-cli-workspace(1)\fP, \fBrudder-cli-workspace-tracking-plans-list(1)\fP
