.nh
.TH "RUDDER-CLI-AUTH-LOGIN" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-auth-login - Login with an access token


.SH SYNOPSIS
\fBrudder-cli auth login [flags]\fP


.SH DESCRIPTION
Store a RudderStack access token for subsequent authenticated CLI operations.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for login


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
rudder-cli auth login

.EE


.SH SEE ALSO
\fBrudder-cli-auth(1)\fP
