.nh
.TH "RUDDER-CLI-WORKSPACE-EVENT-STREAM-SOURCES-LIST" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-workspace-event-stream-sources-list - List event stream sources in the workspace


.SH SYNOPSIS
\fBrudder-cli workspace event-stream-sources list [flags]\fP


.SH DESCRIPTION
List event stream sources in the authenticated workspace, as a table or JSON.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--json\fP[=false]
	Output as JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
rudder-cli workspace event-stream-sources list
rudder-cli workspace event-stream-sources list --json

.EE


.SH SEE ALSO
\fBrudder-cli-workspace-event-stream-sources(1)\fP
