.nh
.TH "RUDDER-CLI-TELEMETRY-STATUS" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-telemetry-status - Show current telemetry status


.SH SYNOPSIS
\fBrudder-cli telemetry status [flags]\fP


.SH DESCRIPTION
Display whether telemetry collection is currently enabled or disabled.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for status


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
rudder-cli telemetry status

.EE


.SH SEE ALSO
\fBrudder-cli-telemetry(1)\fP
