.nh
.TH "RUDDER-CLI-DEBUG-CONFIG" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-debug-config - Dump the active configuration


.SH SYNOPSIS
\fBrudder-cli debug config [flags]\fP


.SH DESCRIPTION
Print the effective CLI configuration as formatted JSON for troubleshooting.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for config


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
RUDDERSTACK_CLI_DEBUG=true rudder-cli debug config

.EE


.SH SEE ALSO
\fBrudder-cli-debug(1)\fP
