.nh
.TH "RUDDER-CLI" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-data-graphs - Manage data graphs


.SH SYNOPSIS
\fBrudder-cli data-graphs  [flags]\fP


.SH DESCRIPTION
Validate data graph models and relationships in a local project against their warehouse account. Use the validate subcommand to check all, modified, or one selected resource.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for data-graphs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
$ rudder-cli data-graphs validate --all
$ rudder-cli data-graphs validate --modified
$ rudder-cli data-graphs validate model my-model-id

.EE


.SH SEE ALSO
\fBrudder-cli(1)\fP, \fBrudder-cli-data-graphs-validate(1)\fP
