.nh
.TH "RUDDER-CLI-IMPORT-RETL-SOURCES" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-import-retl-sources - Import remote RETL SQL Model to local configuration


.SH SYNOPSIS
\fBrudder-cli import retl-sources [flags]\fP


.SH DESCRIPTION
Import a remote RETL SQL Model source into a local YAML configuration file.
This command fetches the remote SQL Model using the provided remote ID,
creates a local YAML configuration with the specified local ID, and embeds
import metadata for tracking.

.PP
Optionally, you can specify a separate location for SQL files using --sql-location.
When provided, the SQL content will be saved as a separate .sql file and the
YAML configuration will reference it using the 'file' field instead of inline 'sql'.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for retl-sources

.PP
\fB-i\fP, \fB--local-id\fP=""
	Local identifier for the imported SQL Model (required)

.PP
\fB-l\fP, \fB--location\fP="."
	Directory where to save the YAML configuration file (default: current directory)

.PP
\fB-r\fP, \fB--remote-id\fP=""
	Remote RETL source ID to import (required)

.PP
\fB-s\fP, \fB--sql-location\fP=""
	Directory where to save SQL files separately (optional, if not provided SQL will be inline in YAML)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
$ rudder-cli import retl-sources --local-id my-model --remote-id abc123
$ rudder-cli import retl-sources -i analytics-model -r def789 -l ./models
$ rudder-cli import retl-sources --local-id analytics-model --remote-id def789 --location ./models --sql-location ./sql
$ rudder-cli import retl-sources -i analytics-model -r def789 -l ./models -s ./sql

.EE


.SH SEE ALSO
\fBrudder-cli-import(1)\fP
