.nh
.TH "RUDDER-CLI-EXPERIMENTAL" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-experimental - Manage experimental features


.SH SYNOPSIS
\fBrudder-cli experimental [flags]\fP


.SH DESCRIPTION
List and manage opt-in experimental feature flags. Experimental commands require experimental mode during normal CLI execution.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for experimental


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
RUDDERSTACK_CLI_EXPERIMENTAL=true rudder-cli experimental list

.EE


.SH SEE ALSO
\fBrudder-cli(1)\fP, \fBrudder-cli-experimental-disable(1)\fP, \fBrudder-cli-experimental-enable(1)\fP, \fBrudder-cli-experimental-list(1)\fP, \fBrudder-cli-experimental-reset(1)\fP
