.nh
.TH "RUDDER-CLI-COMPLETION-FISH" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-completion-fish - Generate the autocompletion script for fish


.SH SYNOPSIS
\fBrudder-cli completion fish [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for the fish shell.

.PP
The generated script can be sourced for the current session or written to the
fish completions directory so new shells load rudder-cli completions
automatically.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for fish

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
# Load completions for the current shell
rudder-cli completion fish | source

# Install completions for future fish shells
rudder-cli completion fish > ~/.config/fish/completions/rudder-cli.fish

.EE


.SH SEE ALSO
\fBrudder-cli-completion(1)\fP
