.nh
.TH "RUDDER-CLI-TYPER" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-typer - Generate type-safe tracking code


.SH SYNOPSIS
\fBrudder-cli typer [flags]\fP


.SH DESCRIPTION
Generate type-safe tracking APIs from remote tracking plans or local declarative project specifications.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for typer


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
rudder-cli typer generate --local --location ./project --platform kotlin

.EE


.SH SEE ALSO
\fBrudder-cli(1)\fP, \fBrudder-cli-typer-generate(1)\fP, \fBrudder-cli-typer-options(1)\fP
