.nh
.TH "RUDDER-CLI-RETL-SOURCES-VALIDATE" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-retl-sources-validate - Validate a RETL source's spec (SQL model or table)


.SH SYNOPSIS
\fBrudder-cli retl-sources validate  [flags]\fP


.SH DESCRIPTION
Validate a RETL source's spec.

.PP
This checks the project's specs and that the source is defined in it. It
does not run the source's query: reading from the warehouse is what
\fBrudder-cli retl-sources preview\fR is for, and it is opt-in because it
executes a query against live data.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for validate

.PP
\fB-l\fP, \fB--location\fP="."
	Path to the project directory


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
$ rudder-cli retl-sources validate my-model
$ rudder-cli retl-sources validate my-model --location ./project

.EE


.SH SEE ALSO
\fBrudder-cli-retl-sources(1)\fP
