.nh
.TH "RUDDER-CLI-EXPERIMENTAL-DISABLE" "1" "Jan 1970" "rudder-cli" "Rudder CLI Manual"

.SH NAME
rudder-cli-experimental-disable - Disable an experimental flag


.SH SYNOPSIS
\fBrudder-cli experimental disable  [flags]\fP


.SH DESCRIPTION
Disable a specific experimental flag by name


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for disable


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-c\fP, \fB--config\fP="~/.rudder/config.json"
	config file (default is '~/.rudder/config.json')


.SH EXAMPLE
.EX
RUDDERSTACK_CLI_EXPERIMENTAL=true rudder-cli experimental disable importMerge

.EE


.SH SEE ALSO
\fBrudder-cli-experimental(1)\fP
