package test

// GetDefaultEvents returns a map of default test event samples.
// These events are used as fallback when no test input files are found.
// Returns map of event name to event data structure.
func GetDefaultEvents() map[string]any {
	return map[string]any{
		"Track": map[string]any{
			"anonymousId": "sample_anonymous_id",
			"channel":     "web",
			"context": map[string]any{
				"app": map[string]any{
					"installType": "npm",
					"name":        "RudderLabs JavaScript SDK",
					"namespace":   "com.rudderlabs.javascript",
					"version":     "3.7.6",
				},
				"campaign": map[string]any{},
				"library": map[string]any{
					"name":    "RudderLabs JavaScript SDK",
					"version": "3.7.6",
				},
				"locale": "en-US",
				"os": map[string]any{
					"name":    "",
					"version": "",
				},
				"page": map[string]any{
					"initial_referrer":         "$direct",
					"initial_referring_domain": "",
					"path":                     "/path",
					"referrer":                 "https://www.website.com/product",
					"referring_domain":         "website.com",
					"search":                   "",
					"tab_url":                  "https://www.website.com/product/path",
					"title":                    "RS 101",
					"url":                      "https://www.website.com/product/path",
				},
				"screen": map[string]any{
					"density":     1,
					"height":      1200,
					"innerHeight": 1065,
					"innerWidth":  1643,
					"width":       1920,
				},
				"sessionId":    1729093483760,
				"sessionStart": true,
				"timezone":     "GMT-0500",
				"traits": map[string]any{
					"name":  "Alex Keener",
					"email": "alex@example.com",
					"phone": "+11234567891",
				},
				"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
			},
			"event": "Product Click",
			"integrations": map[string]any{
				"All": true,
			},
			"messageId":         "81014883-8b3c-46b0-b9f1-2d8928f9f10d",
			"originalTimestamp": "2024-10-16T15:45:18.782Z",
			"properties": map[string]any{
				"product_id": "622c6f5d5cf86a4c77358033",
				"sku":        "8472-998-0112",
				"category":   "Games",
				"name":       "Cones of Dunshire",
				"brand":      "Wyatt Games",
				"variant":    "expansion pack",
				"price":      49.99,
				"quantity":   5,
				"coupon":     "PREORDER15",
				"position":   1,
				"image_url":  "https://www.website.com/product/path",
			},
			"receivedAt": "2024-10-16T15:45:19.033Z",
			"request_ip": "104.176.44.185",
			"rudderId":   "c2160424-86f9-4868-908e-193da5752ec7",
			"sentAt":     "2024-10-16T15:45:18.783Z",
			"type":       "track",
			"userId":     "sample_user_id",
		},
		"Identify": map[string]any{
			"userId": "sample_user_id",
			"type":   "identify",
			"context": map[string]any{
				"traits": map[string]any{
					"name":  "Alex Keener",
					"email": "alex@example.com",
					"phone": "+11234567891",
				},
				"sessionId": 1729095623786,
				"app": map[string]any{
					"name":      "RudderLabs JavaScript SDK",
					"namespace": "com.rudderlabs.javascript",
					"version":   "3.0.3",
				},
				"library": map[string]any{
					"name":    "RudderLabs JavaScript SDK",
					"version": "3.0.3",
				},
				"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
				"os": map[string]any{
					"name":    "",
					"version": "",
				},
				"locale": "en-US",
				"screen": map[string]any{
					"width":       1920,
					"height":      1080,
					"density":     1.5,
					"innerWidth":  800,
					"innerHeight": 750,
				},
				"campaign": map[string]any{},
				"page": map[string]any{
					"initial_referrer":         "$direct",
					"initial_referring_domain": "",
					"path":                     "/path",
					"referrer":                 "https://www.website.com/product",
					"referring_domain":         "website.com",
					"search":                   "",
					"tab_url":                  "https://www.website.com/product/path",
					"title":                    "RS 101",
					"url":                      "https://www.website.com/product/path",
				},
				"timezone": "GMT-0400",
			},
			"channel":           "web",
			"originalTimestamp": "2024-10-16T16:21:18.821Z",
			"integrations": map[string]any{
				"All": true,
			},
			"messageId":   "170cd977-ebb3-416f-a00c-577eaf2b3c61",
			"anonymousId": "sample_anonymous_id",
			"sentAt":      "2024-10-16T16:21:18.822Z",
		},
		"Page": map[string]any{
			"anonymousId": "sample_anonymous_id",
			"channel":     "web",
			"context": map[string]any{
				"app": map[string]any{
					"installType": "npm",
					"name":        "RudderLabs JavaScript SDK",
					"namespace":   "com.rudderlabs.javascript",
					"version":     "3.3.0",
				},
				"campaign": map[string]any{},
				"library": map[string]any{
					"name":    "RudderLabs JavaScript SDK",
					"version": "3.3.0",
				},
				"locale": "en-US",
				"os": map[string]any{
					"name":    "",
					"version": "",
				},
				"page": map[string]any{
					"initial_referrer":         "$direct",
					"initial_referring_domain": "",
					"path":                     "/path",
					"referrer":                 "https://www.website.com/product",
					"referring_domain":         "website.com",
					"search":                   "",
					"tab_url":                  "https://www.website.com/product/path",
					"title":                    "RS 101",
					"url":                      "https://www.website.com/product/path",
				},
				"traits": map[string]any{
					"name":  "Alex Keener",
					"email": "alex@example.com",
					"phone": "+11234567891",
				},
				"screen": map[string]any{
					"density":     3,
					"height":      852,
					"innerHeight": 659,
					"innerWidth":  393,
					"width":       393,
				},
				"sessionId": 1729092331910,
				"timezone":  "GMT-0400",
				"userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1",
			},
			"integrations": map[string]any{
				"All": true,
			},
			"messageId":         "d454a8cc-c262-4938-b475-802595533ed3",
			"originalTimestamp": "2024-10-16T15:44:51.319Z",
			"properties": map[string]any{
				"initial_referrer":         "$direct",
				"initial_referring_domain": "",
				"path":                     "/path",
				"referrer":                 "https://www.website.com/product",
				"referring_domain":         "website.com",
				"search":                   "",
				"tab_url":                  "https://www.website.com/product/path",
				"title":                    "RS 101",
				"url":                      "https://www.website.com/product/path",
			},
			"receivedAt": "2024-10-16T15:44:51.661Z",
			"request_ip": "192.168.1.1",
			"rudderId":   "a465a371-8570-4248-a058-d3047ab42d1b",
			"sentAt":     "2024-10-16T15:44:51.319Z",
			"type":       "page",
			"userId":     "sample_user_id",
		},
		"Screen": map[string]any{
			"anonymousId": "sample_anonymous_id",
			"channel":     "mobile",
			"context": map[string]any{
				"app": map[string]any{
					"build":     "1",
					"name":      "My Application",
					"namespace": "com.rudderstack.demo.myapplication",
					"version":   "1.0",
				},
				"device": map[string]any{
					"id":           "3c2edcdb0e25bb2c",
					"manufacturer": "unknown",
					"model":        "Android SDK built for arm64",
					"name":         "generic_arm64",
					"type":         "Android",
				},
				"library": map[string]any{
					"name":    "com.rudderstack.android.sdk.core",
					"version": "1.7.1",
				},
				"locale": "en-US",
				"network": map[string]any{
					"carrier":  "Android",
					"cellular": true,
					"wifi":     true,
				},
				"os": map[string]any{
					"name":    "Android",
					"version": "9",
				},
				"screen": map[string]any{
					"density": 420,
					"height":  2274,
					"width":   1080,
				},
				"sessionId": 1729745383,
				"timezone":  "Asia/Kolkata",
				"traits": map[string]any{
					"name":        "Alex Keener",
					"email":       "alex@example.com",
					"phone":       "+11234567891",
					"anonymousId": "sample_anonymous_id",
					"id":          "sample_user_id",
					"userId":      "sample_user_id",
				},
				"userAgent": "Dalvik/2.1.0 (Linux; U; Android 9; Android SDK built for arm64 Build/PSR1.210301.009.B1)",
			},
			"event": "HomeScreen",
			"integrations": map[string]any{
				"All": true,
			},
			"messageId":         "1729745383261-a7579db6-0f6f-4ec9-8a4a-2cabe101dde8",
			"originalTimestamp": "2024-10-24T04:49:43.261Z",
			"properties": map[string]any{
				"category": "Parent Screens",
				"name":     "HomeScreen",
			},
			"receivedAt": "2024-10-24T04:49:56.064Z",
			"request_ip": "49.37.32.5",
			"rudderId":   "e41db1e3-a084-49f4-af85-15bd7b8c0ddf",
			"sentAt":     "2024-10-24T04:49:55.295Z",
			"type":       "screen",
			"userId":     "sample_user_id",
		},
	}
}
