package workspace

type Resource struct {
	// ID is the remote identifier for the resource, in the RudderStack workspace
	ID string
	// Is a human-readable name for the resource, either already part of the resource's configuration,
	// or generated by the provider. This is used for communication purposes only, as part of common framework
	// functionality, such interactive resource selection during imports.
	Name string
	// Description is a human-readable description of the resource, either already part of the resource's configuration,
	// or generated by the provider. Similar to Name, this is used for communication purposes only.
	Description string
	// Type is the type of the resource, as defined by the provider. This is the same as a CLI resource's type, and allows
	// Provider's clients to identify which Provider is responsible for handling the resource.
	Type string
	// Data is a generic pointer to the resource's Data, as defined by the Provider (e.g a specific API client's response type).
	// Providers control the type of this value and can use this to provide resource specific operations, such as exposing a Go template
	// that expects Data of a resource specific type.
	Data any
}
