// Code generated by RudderTyper (Rudder CLI 1.0.0). DO NOT EDIT.

// Package examples provides type-safe analytics methods generated from the
// RudderStack tracking plan "Examples Plan".
//
//   - Tracking plan ID: plan_examples
//   - Tracking plan version: 0
//
// Quick start:
//
//	client := analytics.New(writeKey, dataPlaneURL)
//	defer client.Close()
//
//	rt := examples.New(client)
//	err := rt.TrackEventWithNameCamelCase(
//		examples.Identity{UserID: "user-123"},
//		examples.TrackEventWithNameCamelCaseProperties{ /* ... */ },
//	)
package examples

import (
	"encoding/json"
	"errors"
	"maps"
	"slices"
	"time"

	analytics "github.com/rudderlabs/analytics-go/v4"
)

// --- Client ---

// RudderTyperAnalytics sends the events of the tracking plan "Examples Plan"
// through a RudderStack Go SDK client. It holds no mutable state, so one
// value can be shared by many goroutines.
type RudderTyperAnalytics struct {
	client analytics.Client
}

// New returns a RudderTyperAnalytics that sends events through client.
// The caller keeps ownership of client and must Close it on shutdown.
func New(client analytics.Client) *RudderTyperAnalytics {
	if client == nil {
		panic("ruddertyper: New called with a nil analytics.Client")
	}
	return &RudderTyperAnalytics{client: client}
}

// Identity identifies who performed an event. Set UserID, AnonymousID or
// both; the SDK rejects a call that sets neither. When AnonymousID is empty,
// the SDK generates a random one for track, page, screen and group (not
// identify) calls.
type Identity struct {
	UserID      string
	AnonymousID string
}

// Errors returned by generated methods, in addition to the SDK's own. Match
// them with errors.Is.
var (
	// ErrNilPayload reports a nil or typed-nil payload that the tracking
	// plan requires.
	ErrNilPayload = errors.New("ruddertyper: payload is nil")
	// ErrInvalidValue reports a value that cannot be sent as the tracking
	// plan requires, such as an unset union or an unset required variant,
	// or that JSON cannot carry, such as NaN or a value that contains itself.
	ErrInvalidValue = errors.New("ruddertyper: invalid value")
	// ErrCategoryConflict reports a WithCategory value that the event's
	// tracking plan rule does not accept.
	ErrCategoryConflict = errors.New("ruddertyper: category conflicts with the tracking plan")
)

// Option customizes a single call. Options apply in order, so a later option
// overrides an earlier one of the same kind.
type Option func(*callOptions)

type callOptions struct {
	context      *analytics.Context
	integrations analytics.Integrations
	timestamp    time.Time
	messageID    string
}

// WithAnalyticsContext sets the event context. RudderTyper adds its metadata
// under context.ruddertyper, replacing any "ruddertyper" key in ctx.Extra.
func WithAnalyticsContext(ctx analytics.Context) Option {
	return func(o *callOptions) { o.context = &ctx }
}

// WithIntegrations selects the destinations the event is sent to.
func WithIntegrations(integrations analytics.Integrations) Option {
	return func(o *callOptions) { o.integrations = integrations }
}

// WithTimestamp sets when the event happened (originalTimestamp). The SDK
// uses the current time when it is not set.
func WithTimestamp(t time.Time) Option {
	return func(o *callOptions) { o.timestamp = t }
}

// WithMessageID sets the message ID. The SDK generates one when it is not set.
func WithMessageID(id string) Option {
	return func(o *callOptions) { o.messageID = id }
}

// --- Value helpers ---

// Ptr returns a pointer to v. Use it to set optional fields.
func Ptr[T any](v T) *T { return &v }

// --- Property types ---

// Property1stPlace represents the property "1st_place".
type Property1stPlace = int64

// PropertyAdditionalProperties represents the property "additionalProperties".
type PropertyAdditionalProperties = string

// PropertyAmount represents the property "amount".
//
// amount as a number
type PropertyAmount = float64

// PropertyAmount1 represents the property "amount".
//
// amount as a string
type PropertyAmount1 = string

// PropertyAny represents the property "any".
type PropertyAny = any

// PropertyArray represents the property "array".
type PropertyArray = []any

// PropertyBoolean represents the property "boolean".
type PropertyBoolean = bool

// PropertyInteger represents the property "integer".
type PropertyInteger = int64

// PropertyNumber represents the property "number".
type PropertyNumber = float64

// PropertyObject represents the property "object".
type PropertyObject = map[string]any

// PropertyPrice represents the property "price".
type PropertyPrice = float64

// PropertyProductID represents the property "productId".
type PropertyProductID = string

// PropertyProductName represents the property "productName".
type PropertyProductName = string

// PropertySomeBoolean represents the property "someBoolean".
//
// some boolean property
type PropertySomeBoolean = bool

// PropertySomeInteger represents the property "someInteger".
//
// some integer property
type PropertySomeInteger = int64

// PropertySomeString represents the property "someString".
//
// some string property
type PropertySomeString = string

// PropertyString represents the property "string".
type PropertyString = string

// PropertyToProperties represents the property "toProperties".
type PropertyToProperties = string

// PropertyType represents the property "type".
type PropertyType = string

// PropertyUser represents the property "user".
type PropertyUser = string

// PropertyUserID represents the property "userId".
type PropertyUserID = string

// PropertyUserID1 represents the property "user_id".
type PropertyUserID1 = string

// --- Event payloads ---

// TrackEventWithNameCamelCaseProperties holds the properties of "$eventWithNameCamelCase$!".
type TrackEventWithNameCamelCaseProperties struct {
	SomeString *PropertySomeString // optional
}

func (v TrackEventWithNameCamelCaseProperties) toMap() map[string]any {
	m := map[string]any{}
	if v.SomeString != nil {
		m["someString"] = *v.SomeString
	}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackEventWithNameCamelCaseProperties) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEventWithNameCamelCaseProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// TrackEveryPrimitiveTypeProperties holds the properties of "Every Primitive Type".
type TrackEveryPrimitiveTypeProperties struct {
	Any     PropertyAny      // required
	Array   PropertyArray    // required
	Boolean *PropertyBoolean // optional
	Integer *PropertyInteger // optional
	Number  PropertyNumber   // required
	Object  PropertyObject   // optional
	String  PropertyString   // required
	Type    *PropertyType    // optional
}

func (v TrackEveryPrimitiveTypeProperties) toMap() map[string]any {
	m := map[string]any{
		"any":    v.Any,
		"array":  v.Array,
		"number": v.Number,
		"string": v.String,
	}
	if v.Boolean != nil {
		m["boolean"] = *v.Boolean
	}
	if v.Integer != nil {
		m["integer"] = *v.Integer
	}
	if v.Object != nil {
		m["object"] = v.Object
	}
	if v.Type != nil {
		m["type"] = *v.Type
	}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackEveryPrimitiveTypeProperties) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEveryPrimitiveTypeProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// TrackNameCollisionsProperties holds the properties of "Name Collisions".
type TrackNameCollisionsProperties struct {
	X1stPlace     *Property1stPlace     // optional
	Amount        PropertyAmount1       // required
	ToProperties1 *PropertyToProperties // optional
	UserID        PropertyUserID        // required
	UserID1       *PropertyUserID1      // optional
}

func (v TrackNameCollisionsProperties) toMap() map[string]any {
	m := map[string]any{
		"amount": v.Amount,
		"userId": v.UserID,
	}
	if v.X1stPlace != nil {
		m["1st_place"] = *v.X1stPlace
	}
	if v.ToProperties1 != nil {
		m["toProperties"] = *v.ToProperties1
	}
	if v.UserID1 != nil {
		m["user_id"] = *v.UserID1
	}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackNameCollisionsProperties) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackNameCollisionsProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties holds the properties of "Some Empty Track Event With Additional Properties". The tracking plan declares no properties and allows any.
type TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties = map[string]any

// TrackSomeOpenTrackEventProperties holds the properties of "Some Open Track Event".
type TrackSomeOpenTrackEventProperties struct {
	AdditionalProperties1 *PropertyAdditionalProperties // optional
	Amount                *PropertyAmount               // optional
	Price                 *PropertyPrice                // optional
	ProductID             PropertyProductID             // required
	ProductName           *PropertyProductName          // optional
	AdditionalProperties  map[string]any                // optional; undeclared keys only
}

func (v TrackSomeOpenTrackEventProperties) toMap() map[string]any {
	m := withAdditional(v.AdditionalProperties, "additionalProperties", "amount", "price", "productId", "productName")
	if v.AdditionalProperties1 != nil {
		m["additionalProperties"] = *v.AdditionalProperties1
	}
	if v.Amount != nil {
		m["amount"] = *v.Amount
	}
	if v.Price != nil {
		m["price"] = *v.Price
	}
	m["productId"] = v.ProductID
	if v.ProductName != nil {
		m["productName"] = *v.ProductName
	}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackSomeOpenTrackEventProperties) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackSomeOpenTrackEventProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// TrackSomeTrackEventProperties holds the properties of "Some Track Event".
type TrackSomeTrackEventProperties struct {
	SomeBoolean *PropertySomeBoolean // optional
	SomeInteger PropertySomeInteger  // required
	SomeString  PropertySomeString   // required
}

func (v TrackSomeTrackEventProperties) toMap() map[string]any {
	m := map[string]any{
		"someInteger": v.SomeInteger,
		"someString":  v.SomeString,
	}
	if v.SomeBoolean != nil {
		m["someBoolean"] = *v.SomeBoolean
	}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackSomeTrackEventProperties) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackSomeTrackEventProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// TrackUserProperties holds the properties of "User".
type TrackUserProperties struct {
	User *PropertyUser // optional
}

func (v TrackUserProperties) toMap() map[string]any {
	m := map[string]any{}
	if v.User != nil {
		m["user"] = *v.User
	}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackUserProperties) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackUserProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// TrackEventWithNameCamelCaseProperties1 holds the properties of "eventWithNameCamelCase".
type TrackEventWithNameCamelCaseProperties1 struct {
	SomeString *PropertySomeString // optional
}

func (v TrackEventWithNameCamelCaseProperties1) toMap() map[string]any {
	m := map[string]any{}
	if v.SomeString != nil {
		m["someString"] = *v.SomeString
	}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackEventWithNameCamelCaseProperties1) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEventWithNameCamelCaseProperties1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// --- Events ---

// TrackEventWithNameCamelCase sends the track event "$eventWithNameCamelCase$!".
func (r *RudderTyperAnalytics) TrackEventWithNameCamelCase(identity Identity, props TrackEventWithNameCamelCaseProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "$eventWithNameCamelCase$!", p, opts)
}

// TrackEveryPrimitiveType sends the track event "Every Primitive Type".
func (r *RudderTyperAnalytics) TrackEveryPrimitiveType(identity Identity, props TrackEveryPrimitiveTypeProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Every Primitive Type", p, opts)
}

// TrackNameCollisions sends the track event "Name Collisions".
func (r *RudderTyperAnalytics) TrackNameCollisions(identity Identity, props TrackNameCollisionsProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Name Collisions", p, opts)
}

// TrackSomeEmptyTrackEventWithAdditionalProperties sends the track event "Some Empty Track Event With Additional Properties". props may be nil.
func (r *RudderTyperAnalytics) TrackSomeEmptyTrackEventWithAdditionalProperties(identity Identity, props TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties, opts ...Option) error {
	return r.track(identity, "Some Empty Track Event With Additional Properties", props, opts)
}

// TrackSomeEmptyTrackEvent sends the track event "Some Empty Track Event", which has no properties.
func (r *RudderTyperAnalytics) TrackSomeEmptyTrackEvent(identity Identity, opts ...Option) error {
	return r.track(identity, "Some Empty Track Event", nil, opts)
}

// TrackSomeOpenTrackEvent sends the track event "Some Open Track Event".
//
// Declares properties and allows unplanned ones.
// Undeclared keys travel in AdditionalProperties.
func (r *RudderTyperAnalytics) TrackSomeOpenTrackEvent(identity Identity, props TrackSomeOpenTrackEventProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Some Open Track Event", p, opts)
}

// TrackSomeTrackEvent sends the track event "Some Track Event".
//
// This is a track event for testing.
func (r *RudderTyperAnalytics) TrackSomeTrackEvent(identity Identity, props TrackSomeTrackEventProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Some Track Event", p, opts)
}

// TrackUser sends the track event "User".
func (r *RudderTyperAnalytics) TrackUser(identity Identity, props TrackUserProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "User", p, opts)
}

// TrackEventWithNameCamelCase1 sends the track event "eventWithNameCamelCase".
func (r *RudderTyperAnalytics) TrackEventWithNameCamelCase1(identity Identity, props TrackEventWithNameCamelCaseProperties1, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "eventWithNameCamelCase", p, opts)
}

// --- Internals ---

func (r *RudderTyperAnalytics) track(identity Identity, event string, properties analytics.Properties, opts []Option) error {
	o := applyOptions(opts)
	return r.client.Enqueue(analytics.Track{
		UserId:            identity.UserID,
		AnonymousId:       identity.AnonymousID,
		Event:             event,
		Properties:        properties,
		Context:           o.analyticsContext(),
		Integrations:      o.integrations,
		OriginalTimestamp: o.timestamp,
		MessageId:         o.messageID,
	})
}

// rudderTyperContext returns the metadata sent as context.ruddertyper. It
// builds a new map on every call because Config.Callback receives the
// message and could otherwise modify a shared one.
func rudderTyperContext() map[string]any {
	return map[string]any{
		"platform":            "go",
		"rudderCLIVersion":    "1.0.0",
		"trackingPlanId":      "plan_examples",
		"trackingPlanVersion": 0,
	}
}

// applyOptions applies opts in order, skipping nil ones.
func applyOptions(opts []Option) callOptions {
	var o callOptions
	for _, opt := range opts {
		if opt != nil {
			opt(&o)
		}
	}
	return o
}

// analyticsContext builds a fresh context for the call, because the SDK
// writes into the context it is given.
func (o callOptions) analyticsContext() *analytics.Context {
	var ctx analytics.Context
	if o.context != nil {
		ctx = *o.context
	}
	extra := make(map[string]any, len(ctx.Extra)+1)
	maps.Copy(extra, ctx.Extra)
	extra["ruddertyper"] = rudderTyperContext()
	ctx.Extra = extra
	return &ctx
}

// withAdditional starts an object from the keys of extra that the tracking
// plan does not declare. Declared keys always come from the typed fields.
func withAdditional(extra map[string]any, declared ...string) map[string]any {
	m := make(map[string]any, len(extra)+len(declared))
	for k, v := range extra {
		if !slices.Contains(declared, k) {
			m[k] = v
		}
	}
	return m
}
