// Code generated by RudderTyper (Rudder CLI 1.0.0). DO NOT EDIT.

// Package examples provides type-safe analytics methods generated from the
// RudderStack tracking plan "Examples Plan".
//
//   - Tracking plan ID: plan_examples
//   - Tracking plan version: 0
//
// Quick start:
//
//	client := analytics.New(writeKey, dataPlaneURL)
//	defer client.Close()
//
//	rt := examples.New(client)
//	err := rt.TrackEventWithNameCamelCase(
//		examples.Identity{UserID: "user-123"},
//		examples.TrackEventWithNameCamelCaseProperties{ /* ... */ },
//	)
package examples

import (
	"bytes"
	"encoding"
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"math"
	"reflect"
	"slices"
	"time"

	analytics "github.com/rudderlabs/analytics-go/v4"
)

// --- Client ---

// RudderTyperAnalytics sends the events of the tracking plan "Examples Plan"
// through a RudderStack Go SDK client. It holds no mutable state, so one
// value can be shared by many goroutines.
type RudderTyperAnalytics struct {
	client analytics.Client
}

// New returns a RudderTyperAnalytics that sends events through client.
// The caller keeps ownership of client and must Close it on shutdown.
func New(client analytics.Client) *RudderTyperAnalytics {
	if client == nil {
		panic("ruddertyper: New called with a nil analytics.Client")
	}
	return &RudderTyperAnalytics{client: client}
}

// Identity identifies who performed an event. Set UserID, AnonymousID or
// both; the SDK rejects a call that sets neither. When AnonymousID is empty,
// the SDK generates a random one for track, page, screen and group (not
// identify) calls.
type Identity struct {
	UserID      string
	AnonymousID string
}

// Errors returned by generated methods, in addition to the SDK's own. Match
// them with errors.Is.
var (
	// ErrNilPayload reports a nil or typed-nil payload that the tracking
	// plan requires.
	ErrNilPayload = errors.New("ruddertyper: payload is nil")
	// ErrInvalidValue reports a value that cannot be sent as the tracking
	// plan requires, such as an unset union or an unset required variant,
	// or that JSON cannot carry, such as NaN or a value that contains itself.
	ErrInvalidValue = errors.New("ruddertyper: invalid value")
	// ErrCategoryConflict reports a WithCategory value that the event's
	// tracking plan rule does not accept.
	ErrCategoryConflict = errors.New("ruddertyper: category conflicts with the tracking plan")
)

// Option customizes a single call. Options apply in order, so a later option
// overrides an earlier one of the same kind.
type Option func(*callOptions)

type callOptions struct {
	context      *analytics.Context
	integrations analytics.Integrations
	timestamp    time.Time
	messageID    string
}

// WithAnalyticsContext sets the event context. Everything reachable from ctx
// is copied when the event method is called, so ctx can be reused or changed
// afterwards. RudderTyper adds its metadata under context.ruddertyper,
// replacing any "ruddertyper" key in ctx.Extra.
func WithAnalyticsContext(ctx analytics.Context) Option {
	return func(o *callOptions) { o.context = &ctx }
}

// WithIntegrations selects the destinations the event is sent to. The map is
// copied when the event method is called.
func WithIntegrations(integrations analytics.Integrations) Option {
	return func(o *callOptions) { o.integrations = integrations }
}

// WithTimestamp sets when the event happened (originalTimestamp). The SDK
// uses the current time when it is not set.
func WithTimestamp(t time.Time) Option {
	return func(o *callOptions) { o.timestamp = t }
}

// WithMessageID sets the message ID. The SDK generates one when it is not set.
func WithMessageID(id string) Option {
	return func(o *callOptions) { o.messageID = id }
}

// --- Value helpers ---

// Ptr returns a pointer to v. Use it to set optional fields.
func Ptr[T any](v T) *T { return &v }

// --- Property types ---

// Property1stPlace represents the property "1st_place".
type Property1stPlace = int64

// PropertyAdditionalProperties represents the property "additionalProperties".
type PropertyAdditionalProperties = string

// PropertyAmount represents the property "amount".
//
// amount as a number
type PropertyAmount = float64

// PropertyAmount1 represents the property "amount".
//
// amount as a string
type PropertyAmount1 = string

// PropertyAny represents the property "any".
type PropertyAny = any

// PropertyArray represents the property "array".
type PropertyArray = []any

// PropertyBoolean represents the property "boolean".
type PropertyBoolean = bool

// PropertyInteger represents the property "integer".
type PropertyInteger = int64

// PropertyNumber represents the property "number".
type PropertyNumber = float64

// PropertyObject represents the property "object".
type PropertyObject = map[string]any

// PropertyPrice represents the property "price".
type PropertyPrice = float64

// PropertyProductID represents the property "productId".
type PropertyProductID = string

// PropertyProductName represents the property "productName".
type PropertyProductName = string

// PropertySomeBoolean represents the property "someBoolean".
//
// some boolean property
type PropertySomeBoolean = bool

// PropertySomeInteger represents the property "someInteger".
//
// some integer property
type PropertySomeInteger = int64

// PropertySomeString represents the property "someString".
//
// some string property
type PropertySomeString = string

// PropertyString represents the property "string".
type PropertyString = string

// PropertyToProperties represents the property "toProperties".
type PropertyToProperties = string

// PropertyType represents the property "type".
type PropertyType = string

// PropertyUser represents the property "user".
type PropertyUser = string

// PropertyUserID represents the property "userId".
type PropertyUserID = string

// PropertyUserID1 represents the property "user_id".
type PropertyUserID1 = string

// --- Event payloads ---

// TrackEventWithNameCamelCaseProperties holds the properties of "$eventWithNameCamelCase$!".
type TrackEventWithNameCamelCaseProperties struct {
	SomeString *PropertySomeString // optional
}

func (v TrackEventWithNameCamelCaseProperties) toMap() map[string]any {
	m := map[string]any{}
	if v.SomeString != nil {
		m["someString"] = *v.SomeString
	}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackEventWithNameCamelCaseProperties) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEventWithNameCamelCaseProperties) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// TrackEveryPrimitiveTypeProperties holds the properties of "Every Primitive Type".
type TrackEveryPrimitiveTypeProperties struct {
	Any     PropertyAny      // required
	Array   PropertyArray    // required
	Boolean *PropertyBoolean // optional
	Integer *PropertyInteger // optional
	Number  PropertyNumber   // required
	Object  PropertyObject   // optional
	String  PropertyString   // required
	Type    *PropertyType    // optional
}

func (v TrackEveryPrimitiveTypeProperties) toMap() map[string]any {
	m := map[string]any{
		"any":    v.Any,
		"array":  v.Array,
		"number": v.Number,
		"string": v.String,
	}
	if v.Boolean != nil {
		m["boolean"] = *v.Boolean
	}
	if v.Integer != nil {
		m["integer"] = *v.Integer
	}
	if v.Object != nil {
		m["object"] = v.Object
	}
	if v.Type != nil {
		m["type"] = *v.Type
	}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackEveryPrimitiveTypeProperties) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEveryPrimitiveTypeProperties) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// TrackNameCollisionsProperties holds the properties of "Name Collisions".
type TrackNameCollisionsProperties struct {
	X1stPlace     *Property1stPlace     // optional
	Amount        PropertyAmount1       // required
	ToProperties1 *PropertyToProperties // optional
	UserID        PropertyUserID        // required
	UserID1       *PropertyUserID1      // optional
}

func (v TrackNameCollisionsProperties) toMap() map[string]any {
	m := map[string]any{
		"amount": v.Amount,
		"userId": v.UserID,
	}
	if v.X1stPlace != nil {
		m["1st_place"] = *v.X1stPlace
	}
	if v.ToProperties1 != nil {
		m["toProperties"] = *v.ToProperties1
	}
	if v.UserID1 != nil {
		m["user_id"] = *v.UserID1
	}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackNameCollisionsProperties) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackNameCollisionsProperties) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties holds the properties of "Some Empty Track Event With Additional Properties". The tracking plan declares no properties and allows any.
type TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties = map[string]any

// TrackSomeOpenTrackEventProperties holds the properties of "Some Open Track Event".
type TrackSomeOpenTrackEventProperties struct {
	AdditionalProperties1 *PropertyAdditionalProperties // optional
	Amount                *PropertyAmount               // optional
	Price                 *PropertyPrice                // optional
	ProductID             PropertyProductID             // required
	ProductName           *PropertyProductName          // optional
	AdditionalProperties  map[string]any                // optional; undeclared keys only
}

func (v TrackSomeOpenTrackEventProperties) toMap() map[string]any {
	m := withAdditional(v.AdditionalProperties, "additionalProperties", "amount", "price", "productId", "productName")
	if v.AdditionalProperties1 != nil {
		m["additionalProperties"] = *v.AdditionalProperties1
	}
	if v.Amount != nil {
		m["amount"] = *v.Amount
	}
	if v.Price != nil {
		m["price"] = *v.Price
	}
	m["productId"] = v.ProductID
	if v.ProductName != nil {
		m["productName"] = *v.ProductName
	}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackSomeOpenTrackEventProperties) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackSomeOpenTrackEventProperties) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// TrackSomeTrackEventProperties holds the properties of "Some Track Event".
type TrackSomeTrackEventProperties struct {
	SomeBoolean *PropertySomeBoolean // optional
	SomeInteger PropertySomeInteger  // required
	SomeString  PropertySomeString   // required
}

func (v TrackSomeTrackEventProperties) toMap() map[string]any {
	m := map[string]any{
		"someInteger": v.SomeInteger,
		"someString":  v.SomeString,
	}
	if v.SomeBoolean != nil {
		m["someBoolean"] = *v.SomeBoolean
	}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackSomeTrackEventProperties) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackSomeTrackEventProperties) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// TrackUserProperties holds the properties of "User".
type TrackUserProperties struct {
	User *PropertyUser // optional
}

func (v TrackUserProperties) toMap() map[string]any {
	m := map[string]any{}
	if v.User != nil {
		m["user"] = *v.User
	}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackUserProperties) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackUserProperties) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// TrackEventWithNameCamelCaseProperties1 holds the properties of "eventWithNameCamelCase".
type TrackEventWithNameCamelCaseProperties1 struct {
	SomeString *PropertySomeString // optional
}

func (v TrackEventWithNameCamelCaseProperties1) toMap() map[string]any {
	m := map[string]any{}
	if v.SomeString != nil {
		m["someString"] = *v.SomeString
	}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackEventWithNameCamelCaseProperties1) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEventWithNameCamelCaseProperties1) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// --- Events ---

// TrackEventWithNameCamelCase sends the track event "$eventWithNameCamelCase$!".
func (r *RudderTyperAnalytics) TrackEventWithNameCamelCase(identity Identity, props TrackEventWithNameCamelCaseProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "$eventWithNameCamelCase$!", p, opts)
}

// TrackEveryPrimitiveType sends the track event "Every Primitive Type".
func (r *RudderTyperAnalytics) TrackEveryPrimitiveType(identity Identity, props TrackEveryPrimitiveTypeProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Every Primitive Type", p, opts)
}

// TrackNameCollisions sends the track event "Name Collisions".
func (r *RudderTyperAnalytics) TrackNameCollisions(identity Identity, props TrackNameCollisionsProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Name Collisions", p, opts)
}

// TrackSomeEmptyTrackEventWithAdditionalProperties sends the track event "Some Empty Track Event With Additional Properties". props may be nil; it is copied, so it can be reused after the call.
func (r *RudderTyperAnalytics) TrackSomeEmptyTrackEventWithAdditionalProperties(identity Identity, props TrackSomeEmptyTrackEventWithAdditionalPropertiesProperties, opts ...Option) error {
	p, err := snapshot(props)
	if err != nil {
		return err
	}
	return r.track(identity, "Some Empty Track Event With Additional Properties", p, opts)
}

// TrackSomeEmptyTrackEvent sends the track event "Some Empty Track Event", which has no properties.
func (r *RudderTyperAnalytics) TrackSomeEmptyTrackEvent(identity Identity, opts ...Option) error {
	return r.track(identity, "Some Empty Track Event", nil, opts)
}

// TrackSomeOpenTrackEvent sends the track event "Some Open Track Event".
//
// Declares properties and allows unplanned ones.
// Undeclared keys travel in AdditionalProperties.
func (r *RudderTyperAnalytics) TrackSomeOpenTrackEvent(identity Identity, props TrackSomeOpenTrackEventProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Some Open Track Event", p, opts)
}

// TrackSomeTrackEvent sends the track event "Some Track Event".
//
// This is a track event for testing.
func (r *RudderTyperAnalytics) TrackSomeTrackEvent(identity Identity, props TrackSomeTrackEventProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Some Track Event", p, opts)
}

// TrackUser sends the track event "User".
func (r *RudderTyperAnalytics) TrackUser(identity Identity, props TrackUserProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "User", p, opts)
}

// TrackEventWithNameCamelCase1 sends the track event "eventWithNameCamelCase".
func (r *RudderTyperAnalytics) TrackEventWithNameCamelCase1(identity Identity, props TrackEventWithNameCamelCaseProperties1, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "eventWithNameCamelCase", p, opts)
}

// --- Internals ---

func (r *RudderTyperAnalytics) track(identity Identity, event string, properties analytics.Properties, opts []Option) error {
	o, err := applyOptions(opts)
	if err != nil {
		return err
	}
	return r.client.Enqueue(analytics.Track{
		UserId:            identity.UserID,
		AnonymousId:       identity.AnonymousID,
		Event:             event,
		Properties:        properties,
		Context:           o.analyticsContext(nil),
		Integrations:      o.integrations,
		OriginalTimestamp: o.timestamp,
		MessageId:         o.messageID,
	})
}

// rudderTyperContext returns the metadata sent as context.ruddertyper. It
// builds a new map on every call because Config.Callback receives the
// message and could otherwise modify a shared one.
func rudderTyperContext() map[string]any {
	return map[string]any{
		"platform":            "go",
		"rudderCLIVersion":    "1.0.0",
		"trackingPlanId":      "plan_examples",
		"trackingPlanVersion": 0,
	}
}

// applyOptions applies opts and copies every caller-owned value they hold, so
// the SDK, which serializes later on another goroutine, never shares memory
// with the caller. The fields it does not copy are encoded once, so a value
// the SDK could not send is reported here rather than in Config.Callback.
func applyOptions(opts []Option) (callOptions, error) {
	var o callOptions
	for _, opt := range opts {
		if opt != nil {
			opt(&o)
		}
	}
	var err error
	if o.integrations, err = snapshot(o.integrations); err != nil {
		return o, fmt.Errorf("integrations: %w", err)
	}
	if _, err := o.timestamp.MarshalJSON(); err != nil {
		return o, fmt.Errorf("%w: timestamp: %w", ErrInvalidValue, err)
	}
	if o.context == nil {
		return o, nil
	}
	ctx := *o.context
	if ctx.Extra, err = snapshot(ctx.Extra); err != nil {
		return o, fmt.Errorf("context.Extra: %w", err)
	}
	if ctx.Traits, err = snapshot(ctx.Traits); err != nil {
		return o, fmt.Errorf("context.Traits: %w", err)
	}
	ctx.IP = slices.Clone(ctx.IP)
	fields := ctx
	fields.Extra, fields.Traits = nil, nil
	if _, err := json.Marshal(fields); err != nil {
		return o, fmt.Errorf("%w: context: %w", ErrInvalidValue, err)
	}
	o.context = &ctx
	return o, nil
}

// analyticsContext builds a fresh context for the call, because the SDK
// writes into the context it is given. contextTraits (from a context.traits
// identify rule) win over caller-supplied Context.Traits keys.
func (o callOptions) analyticsContext(contextTraits analytics.Traits) *analytics.Context {
	var ctx analytics.Context
	if o.context != nil {
		ctx = *o.context
	}
	extra := make(map[string]any, len(ctx.Extra)+1)
	maps.Copy(extra, ctx.Extra)
	extra["ruddertyper"] = rudderTyperContext()
	ctx.Extra = extra
	if len(contextTraits) > 0 {
		traits := make(analytics.Traits, len(ctx.Traits)+len(contextTraits))
		maps.Copy(traits, ctx.Traits)
		maps.Copy(traits, contextTraits)
		ctx.Traits = traits
	}
	return &ctx
}

// wireObject is implemented by every generated struct, and wireValuer by the
// other generated types with a wire form of their own: unions, mixed enums,
// Nullable and Null.
type (
	wireObject interface{ toMap() map[string]any }
	wireValuer interface{ wireValue() (any, error) }
)

// maxDepth bounds how deeply a value may nest. Real events stay far below it;
// a value that contains itself reaches it and fails instead of overflowing
// the stack.
const maxDepth = 1000

// snapshot converts v into what the SDK receives: new maps and slices holding
// strings, bools, numbers and nil. The SDK serializes later on another
// goroutine, so nothing the caller owns may reach it, and converting now
// reports a value that cannot be sent before Enqueue.
func snapshot(v any) (map[string]any, error) {
	w, err := wire(reflect.ValueOf(v), 0)
	if err != nil {
		return nil, err
	}
	m, _ := w.(map[string]any)
	return m, nil
}

// marshal is the MarshalJSON of every generated type, so json.Marshal and the
// event methods produce the same JSON.
func marshal(v any) ([]byte, error) {
	w, err := wire(reflect.ValueOf(v), 0)
	if err != nil {
		return nil, err
	}
	return json.Marshal(w)
}

// wire returns the JSON value of rv as new plain Go values. Nil slices and
// maps become [] and {}, so a Go zero value is never sent as null by
// accident; null comes only from nil pointers and interfaces, Null and an
// invalid Nullable.
func wire(rv reflect.Value, depth int) (any, error) {
	if depth > maxDepth {
		return nil, tooDeep()
	}
	depth++
	if !rv.IsValid() {
		return nil, nil
	}
	if k := rv.Kind(); (k == reflect.Pointer || k == reflect.Interface) && isNil(rv.Interface()) {
		// toMap already omits or rejects nil variants in fields, so this is a
		// nil variant array item, which has no valid wire form.
		if k == reflect.Interface && rv.Type().Implements(reflect.TypeOf((*wireObject)(nil)).Elem()) {
			return nil, fmt.Errorf("%w: nil %s item", ErrInvalidValue, rv.Type())
		}
		return nil, nil
	}
	switch v := rv.Interface().(type) {
	case wireObject:
		return wire(reflect.ValueOf(v.toMap()), depth)
	case wireValuer:
		x, err := v.wireValue()
		if err != nil {
			return nil, err
		}
		return wire(reflect.ValueOf(x), depth)
	case json.Number, json.Marshaler, encoding.TextMarshaler:
		return encode(v)
	}
	if addrMarshaler(rv) {
		return encode(rv.Addr().Interface())
	}
	switch rv.Kind() {
	case reflect.Interface, reflect.Pointer:
		return wire(rv.Elem(), depth)
	case reflect.Map:
		if rv.Type().Key().Kind() != reflect.String {
			return foreign(rv, depth)
		}
		m := make(map[string]any, rv.Len())
		for it := rv.MapRange(); it.Next(); {
			x, err := wire(it.Value(), depth)
			if err != nil {
				return nil, err
			}
			m[it.Key().String()] = x
		}
		return m, nil
	case reflect.Slice, reflect.Array:
		if rv.Kind() == reflect.Slice && rv.Type().Elem().Kind() == reflect.Uint8 {
			return encode(rv.Interface()) // base64, as encoding/json sends []byte
		}
		s := make([]any, rv.Len())
		for i := range s {
			x, err := wire(rv.Index(i), depth)
			if err != nil {
				return nil, err
			}
			s[i] = x
		}
		return s, nil
	case reflect.Struct:
		return foreign(rv, depth)
	case reflect.String:
		return rv.String(), nil
	case reflect.Bool:
		return rv.Bool(), nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return rv.Int(), nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return rv.Uint(), nil
	case reflect.Float32, reflect.Float64:
		f := rv.Float()
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return nil, fmt.Errorf("%w: %v is not a JSON number", ErrInvalidValue, f)
		}
		if rv.Kind() == reflect.Float32 {
			return float32(f), nil
		}
		return f, nil
	}
	// Channels, functions and complex numbers: encoding/json names the error.
	return encode(rv.Interface())
}

// foreign converts a caller-defined struct, or a map with non-string keys,
// with encoding/json, whose rules for them this file does not repeat. It
// encodes a copy in which nil slices and maps are empty, so the nil rule
// holds inside them too. Building the copy visits every value encoding/json
// will reach: a generated value in there is encoded by its own MarshalJSON,
// which starts a new walk, so only this walk can stop a cycle that runs
// through it.
func foreign(rv reflect.Value, depth int) (any, error) {
	c, err := normalize(rv, depth-1) // wire has already counted rv
	if err != nil {
		return nil, err
	}
	// encoding/json calls pointer-receiver marshalers only on addressable
	// values, so the copy is encoded as addressable as rv is.
	if rv.Kind() == reflect.Struct && rv.CanAddr() {
		c = c.Addr()
	}
	return encode(c.Interface())
}

// normalize returns a copy of rv in which nil slices and maps are empty,
// except []byte and maps with non-string keys, which encoding/json sends as
// null. Generated values and marshalers are kept, since they encode
// themselves; generated values are walked first to catch cycles.
func normalize(rv reflect.Value, depth int) (reflect.Value, error) {
	k, t := rv.Kind(), rv.Type()
	if (k == reflect.Pointer || k == reflect.Interface) && rv.IsNil() {
		_, err := wire(rv, depth) // rejects a nil variant
		return rv, err
	}
	switch rv.Interface().(type) {
	case wireObject, wireValuer:
		_, err := wire(rv, depth)
		return rv, err
	case json.Marshaler, encoding.TextMarshaler:
		return rv, nil
	}
	if addrMarshaler(rv) {
		return rv, nil
	}
	if depth > maxDepth {
		return rv, tooDeep()
	}
	depth++
	switch k {
	case reflect.Interface:
		return normalize(rv.Elem(), depth)
	case reflect.Pointer:
		e, err := normalize(rv.Elem(), depth)
		if err != nil {
			return rv, err
		}
		c := reflect.New(t.Elem())
		c.Elem().Set(e)
		return c, nil
	case reflect.Map:
		if rv.IsNil() && t.Key().Kind() != reflect.String {
			return rv, nil
		}
		c := reflect.MakeMapWithSize(t, rv.Len())
		for it := rv.MapRange(); it.Next(); {
			e, err := normalize(it.Value(), depth)
			if err != nil {
				return rv, err
			}
			c.SetMapIndex(it.Key(), e)
		}
		return c, nil
	case reflect.Slice, reflect.Array:
		if k == reflect.Slice && t.Elem().Kind() == reflect.Uint8 {
			return rv, nil
		}
		c := reflect.New(t).Elem()
		if k == reflect.Slice {
			c.Set(reflect.MakeSlice(t, rv.Len(), rv.Len()))
		}
		for i := 0; i < rv.Len(); i++ {
			e, err := normalize(rv.Index(i), depth)
			if err != nil {
				return rv, err
			}
			c.Index(i).Set(e)
		}
		return c, nil
	case reflect.Struct:
		c := reflect.New(t).Elem()
		c.Set(rv)
		return c, normalizeFields(c, rv, depth)
	}
	return rv, nil
}

// normalizeFields normalizes into dst the fields of struct src that
// encoding/json writes: the exported ones, including those it promotes from
// an embedded struct of an unexported type. Fields are read from src, so a
// field is as addressable as encoding/json will find it. dst is invalid
// behind an embedded pointer to such a struct: the pointer cannot be
// replaced and what it points to belongs to the caller, so the fields there
// are only checked.
func normalizeFields(dst, src reflect.Value, depth int) error {
	if depth > maxDepth {
		return tooDeep()
	}
	for i := 0; i < src.NumField(); i++ {
		var (
			f, fv = src.Type().Field(i), src.Field(i)
			d     reflect.Value
			err   error
		)
		if dst.IsValid() {
			d = dst.Field(i)
		}
		switch {
		case f.Tag.Get("json") == "-":
		case f.IsExported():
			var x reflect.Value
			if x, err = normalize(fv, depth); err == nil && d.IsValid() {
				d.Set(x)
			}
		case !f.Anonymous:
		case fv.Kind() == reflect.Struct:
			err = normalizeFields(d, fv, depth)
		case fv.Kind() == reflect.Pointer && !fv.IsNil() && fv.Elem().Kind() == reflect.Struct:
			err = normalizeFields(reflect.Value{}, fv.Elem(), depth+1)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// addrMarshaler reports whether encoding/json would call a pointer-receiver
// MarshalJSON or MarshalText on rv, which it does when rv is addressable,
// such as a slice element.
func addrMarshaler(rv reflect.Value) bool {
	if rv.Kind() == reflect.Pointer || !rv.CanAddr() {
		return false
	}
	switch rv.Addr().Interface().(type) {
	case json.Marshaler, encoding.TextMarshaler:
		return true
	}
	return false
}

// tooDeep reports a value that nests more than maxDepth levels deep, which a
// value that contains itself always does.
func tooDeep() error {
	return fmt.Errorf("%w: value nests more than %d levels deep or contains itself", ErrInvalidValue, maxDepth)
}

// encode converts v through encoding/json, for values whose JSON form only
// encoding/json defines. Numbers inside them come back as json.Number.
func encode(v any) (any, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrInvalidValue, err)
	}
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.UseNumber()
	var x any
	if err := dec.Decode(&x); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrInvalidValue, err)
	}
	return x, nil
}

// isNil reports whether v is nil or a nil pointer stored in an interface.
func isNil(v any) bool {
	if v == nil {
		return true
	}
	rv := reflect.ValueOf(v)
	return rv.Kind() == reflect.Pointer && rv.IsNil()
}

// withAdditional starts an object from the keys of extra that the tracking
// plan does not declare. Declared keys always come from the typed fields.
func withAdditional(extra map[string]any, declared ...string) map[string]any {
	m := make(map[string]any, len(extra)+len(declared))
	for k, v := range extra {
		if !slices.Contains(declared, k) {
			m[k] = v
		}
	}
	return m
}
