/**
 * compile.ts — turn a typed scenes.config.ts into a VHS .tape file.
 *
 * Usage:  npx tsx <skill>/scripts/compile.ts <demo-dir>
 *   <demo-dir> must contain a `scenes.config.ts` with a default-exported DemoConfig.
 *   Writes <demo-dir>/tape.tape and prints a duration estimate.
 *
 * Zero npm dependencies — runs straight under `npx tsx`. The .tape it emits is
 * hand-readable; vhs does not care that TypeScript generated it.
 */
import { pathToFileURL } from "node:url";
import { writeFileSync, existsSync } from "node:fs";
import { resolve, join, basename } from "node:path";

// Kept in sync with the template's inline type. The config file is plain JS at
// runtime, so this exists only for compile.ts's own type-checking.
interface Scene {
  /**
   * Full-screen intro/section/outro card: clears the screen and shows a large
   * centered title + dim subtitle. Held for `holdMs` (default 3000).
   */
  card?: { title: string; subtitle?: string; holdMs?: number };
  /**
   * "What's happening" note shown above the command: clears the screen, prints a
   * styled heading + dim detail, holds `holdMs` (default 2200), then the command
   * is typed below it on the same screen.
   */
  note?: { heading: string; detail?: string; holdMs?: number };
  /** Optional on-screen header, typed as a shell comment (runs nothing). */
  title?: string;
  /** The command to type and run. Optional for pure card/note beats. */
  command?: string;
  /** Per-scene typing speed override (ms/char). */
  typingSpeedMs?: number;
  /** Pause before typing this scene's command. */
  sleepBeforeMs?: number;
  /** Pause after the output renders, so a viewer can read it. */
  sleepAfterMs?: number;
  /**
   * Replay mode: a file under the demo's `outputs/` dir whose contents are
   * printed instead of running the command live. The command is still typed
   * verbatim on screen. Use for interactive/secret commands (auth login),
   * one-shot commands (import), or anything non-deterministic.
   */
  replayFile?: string;
}

interface DemoConfig {
  /** Output file, relative to the demo dir. Extension picks the format: .gif or .mp4. */
  output: string;
  width?: number;
  height?: number;
  fontSize?: number;
  /** Any built-in VHS theme name, e.g. "Dracula", "Catppuccin Mocha". */
  theme?: string;
  /** VHS shell, e.g. "bash" | "zsh". Defaults to bash for deterministic prompts. */
  shell?: string;
  /** Default typing speed (ms/char) for all scenes. */
  typingSpeedMs?: number;
  /** Hidden setup commands run before recording (PATH exports, cd, clear). */
  setup?: string[];
  scenes: Scene[];
}

function fail(msg: string): never {
  console.error(`compile.ts: ${msg}`);
  process.exit(1);
}

function typeCmd(s: string): string {
  // VHS `Type` has NO in-string escape mechanism — `\"` is literal, not an
  // escaped quote. Instead it accepts three quote wrappers ("", '', ``). Pick
  // one the text doesn't itself contain.
  if (!s.includes('"')) return `Type "${s}"`;
  if (!s.includes("'")) return `Type '${s}'`;
  if (!s.includes("`")) return `Type \`${s}\``;
  fail(`scene text mixes all three quote types; VHS Type cannot encode it: ${s}`);
}

function ms(n: number): string {
  // VHS rejects compound durations (4m30s); always emit plain ms.
  return `${Math.max(0, Math.round(n))}ms`;
}

function validate(cfg: unknown): asserts cfg is DemoConfig {
  if (!cfg || typeof cfg !== "object") fail("config default export is not an object");
  const c = cfg as Record<string, unknown>;
  if (typeof c.output !== "string" || !c.output) fail("config.output (string) is required");
  if (!/\.(gif|mp4|webm)$/.test(c.output as string)) fail("config.output must end in .gif, .mp4, or .webm");
  if (!Array.isArray(c.scenes) || c.scenes.length === 0) fail("config.scenes must be a non-empty array");
  c.scenes.forEach((s, i) => {
    const sc = s as Scene;
    if (!sc || typeof sc !== "object") fail(`scenes[${i}] must be an object`);
    if (!sc.command && !sc.card && !sc.note)
      fail(`scenes[${i}] needs at least one of: command, card, note`);
    if (sc.command !== undefined && typeof sc.command !== "string")
      fail(`scenes[${i}].command must be a string`);
  });
}

async function main() {
  const demoDir = process.argv[2];
  if (!demoDir) fail("missing <demo-dir> argument");
  const dir = resolve(demoDir);
  const configPath = join(dir, "scenes.config.ts");

  let mod: { default?: unknown };
  try {
    mod = await import(pathToFileURL(configPath).href);
  } catch (e) {
    fail(`could not import ${configPath}: ${(e as Error).message}`);
  }
  const cfg = mod!.default;
  validate(cfg);

  const typingDefault = cfg.typingSpeedMs ?? 50;
  const lines: string[] = [];
  let estMs = 0;

  lines.push(`# GENERATED by create-vhs/scripts/compile.ts — DO NOT EDIT.`);
  lines.push(`# Source of truth: ${basename(configPath)}. Re-run compile.ts after edits.`);
  // Absolute + quoted so the recording lands in the demo dir regardless of where
  // vhs runs (VHS's Output parser rejects unquoted paths containing slashes).
  lines.push(`Output "${join(dir, cfg.output)}"`);
  lines.push("");
  lines.push(`Set Shell "${cfg.shell ?? "bash"}"`);
  if (cfg.fontSize) lines.push(`Set FontSize ${cfg.fontSize}`);
  lines.push(`Set Width ${cfg.width ?? 1400}`);
  lines.push(`Set Height ${cfg.height ?? 900}`);
  lines.push(`Set TypingSpeed ${ms(typingDefault)}`);
  if (cfg.theme) lines.push(`Set Theme "${cfg.theme}"`);
  lines.push("");

  // Replay wiring: if any scene has replayFile, override the demo's binary with a
  // shell function that prints the next captured file (in command order) instead
  // of running the real command. Scenes that share the same binary but have no
  // replayFile fall through to the live binary via `command`.
  const firstToken = (cmd?: string) => (cmd ?? "").trim().split(/\s+/)[0] ?? "";
  const replayScenes = cfg.scenes.filter((s) => s.replayFile);
  const hidden: string[] = [...(cfg.setup ?? [])];
  if (replayScenes.length) {
    const binary = firstToken(replayScenes[0].command);
    const outputsDir = join(dir, "outputs");
    const order = cfg.scenes
      .filter((s) => s.command && firstToken(s.command) === binary)
      .map((s) => {
        if (s.replayFile && !existsSync(join(outputsDir, s.replayFile)))
          console.warn(`compile.ts: WARN capture not found: outputs/${s.replayFile}`);
        return `"${s.replayFile ?? ""}"`;
      });
    hidden.push(`__RIDX=0`);
    hidden.push(`__RDIR="${outputsDir}"`);
    hidden.push(`__RFILES=(${order.join(" ")})`);
    // `command <binary>` bypasses this function and runs the real binary.
    hidden.push(
      `${binary}() { local f="\${__RFILES[$__RIDX]}"; __RIDX=$((__RIDX+1)); ` +
        `if [ -n "$f" ]; then command cat "$__RDIR/$f"; else command ${binary} "$@"; fi; }`,
    );
  }

  // Styled card/note helpers, defined once in hidden setup. printf interprets
  // the \033 escapes; the whole def has no single quotes so typeCmd single-wraps.
  const usesCards = cfg.scenes.some((s) => s.card || s.note);
  if (usesCards) {
    hidden.push(
      `__card() { clear; printf "\\n\\n\\n"; printf "     \\033[1;35m◆\\033[0m  \\033[1;37m%s\\033[0m\\n\\n" "$1"; [ -n "$2" ] && printf "        \\033[2m%s\\033[0m\\n" "$2"; printf "\\n"; }`,
    );
    hidden.push(
      `__note() { clear; printf "\\n  \\033[1;36m▸ %s\\033[0m\\n" "$1"; [ -n "$2" ] && printf "    \\033[38;5;245m%s\\033[0m\\n" "$2"; printf "\\n"; }`,
    );
  }

  // `clear` MUST be the last hidden command: Hide stops frame capture but the
  // commands are still really typed into the terminal, so a clear anywhere but
  // the end would leave later setup/replay echoes on screen when Show resumes.
  hidden.push("clear");

  // Hidden setup: PATH exports, prompt, replay wiring, trailing clear. Hide
  // blocks DO NOT advance the timeline, so this adds nothing to the duration.
  lines.push("Hide");
  for (const cmd of hidden) {
    lines.push(typeCmd(cmd));
    lines.push("Enter");
  }
  lines.push("Sleep 500ms");
  lines.push("Show");
  lines.push("");

  // Pre-roll so the first frame is calm before typing begins.
  lines.push("Sleep 1s");
  estMs += 1000;

  // Card/note args go inside double quotes; neutralize any embedded double quote.
  const arg = (s: string) => `"${s.replace(/"/g, "'")}"`;

  // A card/note runs in Hide (its own `clear` wipes the typed call), then we Show
  // and hold so only the rendered card is recorded — never the function call.
  const emitBeat = (call: string, holdMs: number) => {
    lines.push("Hide");
    lines.push(typeCmd(call));
    lines.push("Enter");
    lines.push("Show");
    lines.push(`Sleep ${ms(holdMs)}`);
    estMs += holdMs;
  };

  cfg.scenes.forEach((scene, i) => {
    const speed = scene.typingSpeedMs ?? typingDefault;
    lines.push(`# scene ${i + 1}${scene.title ? `: ${scene.title}` : ""}`);

    if (scene.sleepBeforeMs) {
      lines.push(`Sleep ${ms(scene.sleepBeforeMs)}`);
      estMs += scene.sleepBeforeMs;
    }

    if (scene.card) {
      const sub = scene.card.subtitle ? ` ${arg(scene.card.subtitle)}` : "";
      emitBeat(`__card ${arg(scene.card.title)}${sub}`, scene.card.holdMs ?? 3000);
    }

    if (scene.note) {
      const det = scene.note.detail ? ` ${arg(scene.note.detail)}` : "";
      emitBeat(`__note ${arg(scene.note.heading)}${det}`, scene.note.holdMs ?? 2200);
    }

    if (scene.title) {
      const header = `# ${scene.title}`;
      lines.push(typeCmd(header));
      lines.push("Enter");
      estMs += header.length * speed + 300;
    }

    if (scene.command) {
      if (scene.typingSpeedMs) lines.push(`Set TypingSpeed ${ms(speed)}`);
      lines.push(typeCmd(scene.command));
      lines.push("Sleep 400ms");
      lines.push("Enter");
      estMs += scene.command.length * speed + 400 + 300;
      if (scene.typingSpeedMs) lines.push(`Set TypingSpeed ${ms(typingDefault)}`);

      const after = scene.sleepAfterMs ?? 3000;
      lines.push(`Sleep ${ms(after)}`);
      estMs += after;
    }
    lines.push("");
  });

  // Post-roll hold so the last frame lingers.
  lines.push("Sleep 2s");
  estMs += 2000;

  const tapePath = join(dir, "tape.tape");
  writeFileSync(tapePath, lines.join("\n") + "\n", "utf8");

  const secs = (estMs / 1000).toFixed(1);
  console.log(`Wrote ${tapePath}`);
  console.log(`Scenes: ${cfg.scenes.length}   Output: ${cfg.output}   Est. duration: ~${secs}s`);
  console.log(`Record with:  vhs ${tapePath}`);
}

main().catch((e) => fail((e as Error).stack ?? String(e)));
