// Package cmddocs generates the checked-in rudder-cli command reference.
package cmddocs

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// Generate writes Markdown and YAML command references under outputDir/commands
// and section-one man pages directly under manDir.
func Generate(root *cobra.Command, outputDir, manDir string) error {
	if root == nil {
		return fmt.Errorf("generating command docs: root command is nil")
	}
	if strings.TrimSpace(outputDir) == "" || strings.TrimSpace(manDir) == "" {
		return fmt.Errorf("generating command docs: output and man directories are required")
	}

	commandsDir := filepath.Join(outputDir, "commands")
	markdownPaths := commandPathsByFilename(root, "_", ".md")
	yamlPaths := commandPathsByFilename(root, "_", ".yaml")
	manPaths := commandPathsByFilename(root, "-", ".1")

	if err := prepareDirectory(commandsDir, ownedCommandFiles(markdownPaths, yamlPaths), ".md", ".yaml"); err != nil {
		return fmt.Errorf("preparing command docs directory: %w", err)
	}
	if err := prepareDirectory(manDir, ownedCommandFiles(manPaths), ".1"); err != nil {
		return fmt.Errorf("preparing man page directory: %w", err)
	}

	paths := markdownPaths
	prepender := func(filename string) string {
		return "---\ncommand: " + strconv.Quote(paths[filepath.Base(filename)]) + "\n---\n\n"
	}
	linkHandler := func(link string) string {
		return filepath.ToSlash(filepath.Base(link))
	}
	if err := doc.GenMarkdownTreeCustom(root, commandsDir, prepender, linkHandler); err != nil {
		return fmt.Errorf("generating Markdown command docs: %w", err)
	}
	if err := trimMarkdownEOF(commandsDir, markdownPaths); err != nil {
		return fmt.Errorf("normalizing Markdown command docs: %w", err)
	}
	if err := doc.GenYamlTree(root, commandsDir); err != nil {
		return fmt.Errorf("generating YAML command docs: %w", err)
	}

	date := time.Unix(0, 0).UTC()
	header := &doc.GenManHeader{Section: "1", Date: &date, Source: "rudder-cli", Manual: "Rudder CLI Manual"}
	if err := doc.GenManTree(root, header, manDir); err != nil {
		return fmt.Errorf("generating man pages: %w", err)
	}
	return nil
}

func trimMarkdownEOF(dir string, paths map[string]string) error {
	for name := range paths {
		filename := filepath.Join(dir, name)
		contents, err := os.ReadFile(filename)
		if err != nil {
			return err
		}
		normalized := append([]byte(strings.TrimRight(string(contents), "\n")), '\n')
		if err := os.WriteFile(filename, normalized, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func prepareDirectory(dir string, owned map[string]struct{}, extensions ...string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		name := entry.Name()
		path := filepath.Join(dir, name)
		_, expected := owned[name]
		if entry.IsDir() || !hasExtension(name, extensions) || (!expected && !isStaleGeneratedFile(path)) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	return nil
}

func hasExtension(name string, extensions []string) bool {
	for _, extension := range extensions {
		if strings.HasSuffix(name, extension) {
			return true
		}
	}
	return false
}

func ownedCommandFiles(fileMaps ...map[string]string) map[string]struct{} {
	owned := make(map[string]struct{})
	for _, files := range fileMaps {
		for name := range files {
			owned[name] = struct{}{}
		}
	}
	return owned
}

func isStaleGeneratedFile(path string) bool {
	name := filepath.Base(path)
	if !strings.HasPrefix(name, "rudder-cli") {
		return false
	}
	contents, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	text := string(contents)
	return strings.Contains(text, "Auto generated by spf13/cobra") ||
		strings.Contains(text, "command: \"rudder-cli") ||
		strings.HasPrefix(text, "name: rudder-cli") ||
		strings.HasPrefix(text, ".TH \"RUDDER-CLI")
}

func commandPathsByFilename(root *cobra.Command, separator, extension string) map[string]string {
	paths := make(map[string]string)
	var visit func(*cobra.Command)
	visit = func(command *cobra.Command) {
		if command != root && (!command.IsAvailableCommand() || command.IsAdditionalHelpTopicCommand()) {
			return
		}
		filename := strings.ReplaceAll(command.CommandPath(), " ", separator) + extension
		paths[filename] = command.CommandPath()
		for _, child := range command.Commands() {
			visit(child)
		}
	}
	visit(root)
	return paths
}
