// This file was automatically generated by Rudder CLI 1.0.0.
// Do not modify manually.

package com.rudderstack.ruddertyper

import com.rudderstack.sdk.kotlin.core.Analytics
import com.rudderstack.sdk.kotlin.core.internals.models.RudderOption
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import androidx.compose.runtime.Stable

private fun Unit.rudderSerialize(): JsonObject = buildJsonObject {}
private fun String.rudderSerialize(): JsonPrimitive = JsonPrimitive(this)
private fun Long.rudderSerialize(): JsonPrimitive = JsonPrimitive(this)
private fun Double.rudderSerialize(): JsonPrimitive = JsonPrimitive(this)
private fun Boolean.rudderSerialize(): JsonPrimitive = JsonPrimitive(this)
private fun JsonElement.rudderSerialize(): JsonElement = this
private fun JsonObject.rudderSerialize(): JsonObject = this
private fun JsonArray.rudderSerialize(): JsonArray = this
private fun JsonNull.rudderSerialize(): JsonNull = this

@JvmName("rudderSerializeListUnit")
private fun List<Unit>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListListUnit")
private fun List<List<Unit>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListString")
private fun List<String>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListListString")
private fun List<List<String>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListLong")
private fun List<Long>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListListLong")
private fun List<List<Long>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListDouble")
private fun List<Double>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListListDouble")
private fun List<List<Double>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListBoolean")
private fun List<Boolean>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListListBoolean")
private fun List<List<Boolean>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListJsonElement")
private fun List<JsonElement>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListListJsonElement")
private fun List<List<JsonElement>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListJsonObject")
private fun List<JsonObject>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListListJsonObject")
private fun List<List<JsonObject>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListJsonArray")
private fun List<JsonArray>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListListJsonArray")
private fun List<List<JsonArray>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListJsonNull")
private fun List<JsonNull>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListListJsonNull")
private fun List<List<JsonNull>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })

typealias PropertyColor = String

typealias PropertyDetails = JsonObject

typealias PropertyItemId = String

typealias PropertyLabel = String

@Stable
data class TrackButtonClickedProperties(
    val label: com.rudderstack.ruddertyper.PropertyLabel
)
fun TrackButtonClickedProperties.rudderSerialize(): JsonObject = buildJsonObject {
    put("label", label.rudderSerialize())
}
@JvmName("rudderSerializeList_TrackButtonClickedProperties")
fun List<TrackButtonClickedProperties>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListList_TrackButtonClickedProperties")
fun List<List<TrackButtonClickedProperties>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })

@Stable
data class TrackItemViewedProperties(
    val details: com.rudderstack.ruddertyper.TrackItemViewedProperties.Details? = null,

    val itemId: com.rudderstack.ruddertyper.PropertyItemId
) {
    @Stable
    data class Details(
        val color: com.rudderstack.ruddertyper.PropertyColor
    )
    fun Details.rudderSerialize(): JsonObject = buildJsonObject {
        put("color", color.rudderSerialize())
    }
    @JvmName("rudderSerializeList_Details")
    fun List<Details>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
    @JvmName("rudderSerializeListList_Details")
    fun List<List<Details>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
}
fun TrackItemViewedProperties.rudderSerialize(): JsonObject = buildJsonObject {
    if (details != null) {
        put("details", details.rudderSerialize())
    }
    put("item_id", itemId.rudderSerialize())
}
@JvmName("rudderSerializeList_TrackItemViewedProperties")
fun List<TrackItemViewedProperties>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })
@JvmName("rudderSerializeListList_TrackItemViewedProperties")
fun List<List<TrackItemViewedProperties>>.rudderSerialize(): JsonArray = JsonArray(this.map { it.rudderSerialize() })

/** Merges the ruddertyper context with user-provided custom context */
private fun mergeRudderContext(userOptions: RudderOption?, ruddertyperContext: JsonObject): RudderOption {
    return if (userOptions == null) {
        RudderOption(customContext = ruddertyperContext)
    } else {
        // Merge contexts: start with ruddertyper context, then apply user's custom context
        val mergedContext = buildJsonObject {
            // Add ruddertyper context first
            for ((key, value) in ruddertyperContext) {
                put(key, value)
            }
            // Merge in user's custom context (if provided)
            for ((key, value) in userOptions.customContext) {
                put(key, value)
            }
        }
        // Copy all properties from userOptions and set merged context
        userOptions.copy(customContext = mergedContext)
    }
}

/**
 * This file provides type-safe wrappers for tracking events with RudderStack based on your tracking plan.
 *
 * ## Tracking Plan
 * - **Name**: Test Plan
 * - **ID**: tp_123
 * - **Version**: 1
 *
 * ## Quick Start
 *
 * Initialize RudderStack Analytics:
 * ```kotlin
 * val analytics = Analytics(
 *     configuration = Configuration(
 *         writeKey = "YOUR_WRITE_KEY",
 *         dataPlaneUrl = "YOUR_DATA_PLANE_URL"
 *     ),
 *     application = application
 * )
 * val rudderAnalytics = RudderAnalytics(analytics)
 * ```
 *
 * Track events using the generated type-safe methods.
 *
 * For more information, refer to:
 * - [RudderStack Kotlin SDK Documentation](https://github.com/rudderlabs/rudder-sdk-kotlin)
 */
class RudderAnalytics(private val analytics: Analytics) {
    private val context = buildJsonObject {
        put("ruddertyper", buildJsonObject {
            put("platform", "kotlin")
            put("rudderCLIVersion", "1.0.0")
            put("trackingPlanId", "tp_123")
            put("trackingPlanVersion", 1)
        })
    }

    /**
     * 
     *
     * Event:
     *   Name: "Button Clicked"
     *   Identity Section: "properties"
     *
     * @param properties The properties to include with this event
     * @param options Optional RudderStack options for this event
     *
     * @see com.rudderstack.sdk.kotlin.core.Analytics.track
     */
    fun trackButtonClicked(properties: TrackButtonClickedProperties, options: RudderOption? = null) {
        var mergedOptions = mergeRudderContext(options, context)
        analytics.track(
            name = "Button Clicked",
            properties = properties.rudderSerialize(),
            options = mergedOptions
        )
    }

    /**
     * 
     *
     * Event:
     *   Name: "Item Viewed"
     *   Identity Section: "properties"
     *
     * @param properties The properties to include with this event
     * @param options Optional RudderStack options for this event
     *
     * @see com.rudderstack.sdk.kotlin.core.Analytics.track
     */
    fun trackItemViewed(properties: TrackItemViewedProperties, options: RudderOption? = null) {
        var mergedOptions = mergeRudderContext(options, context)
        analytics.track(
            name = "Item Viewed",
            properties = properties.rudderSerialize(),
            options = mergedOptions
        )
    }
}