/**
 * RudderTyper.ts
 * This file was automatically generated by Rudder CLI 1.0.0.
 * Do not modify manually.
 */

import type {
    ApiOptions,
    RudderAnalytics,
    ApiCallback,
    ApiObject as SDKApiObject,
    IdentifyTraits as SDKIdentifyTraits,
} from "@rudderstack/analytics-js";

// ===== Property Enums =====

/** Type of device */
export type PropertyDeviceType = "mobile" | "tablet" | "desktop" | "smartTV" | "IoT-Device";

/** Field with $ for testing string interpolation: $variable and ${expression} */
export type PropertyDollarField = "$USD" | "$100" | "Price: $99.99" | "$variable_name";

/** Feature enabled flag */
export type PropertyEnabled = true | false;

/** Mixed type enum */
export type PropertyMixedValue = "active" | 1 | true | 2.5;

/** Priority level */
export type PropertyPriority = 1 | 2 | 3;

/** Rating value */
export type PropertyRating = 1.5 | 2.5 | 3.5 | 4.5 | 5;

/** HTTP status with special characters */
export type PropertyStatusCode = "200: OK" | "404: Not Found" | "500: Internal \"Server\" Error";

/** Field demonstrating various Unicode characters in enum values */
export type PropertyUnicodeEnumField = "🎯" | "✅" | "активный" | "已完成" | "ενεργός" | "café" | "!!!";


// ===== Custom Types =====

/** Whether user is active */
export type CustomTypeActive = boolean;

/** List of addresses */
export type CustomTypeAddressList = CustomTypeAddressDetails[];

/** User's age in years */
export type CustomTypeAge = number;

/** Custom type for Colors */
export type CustomTypeColor = string;

/** Custom type for email validation */
export type CustomTypeEmail = string;

/** List of email addresses */
export type CustomTypeEmailList = CustomTypeEmail[];

/** Empty object that does not allow additional properties */
export type CustomTypeEmptyObjectNoAdditionalProps = Record<string, never>;

/** Empty object that allows additional properties */
export type CustomTypeEmptyObjectWithAdditionalProps = Record<string, unknown>;

/** Custom type representing a null value */
export type CustomTypeNullType = null;

/** Custom type for phone numbers */
export type CustomTypePhoneNumber = string;

/** List of user profiles */
export type CustomTypeProfileList = CustomTypeUserProfile[];

/** User status enum */
export type CustomTypeStatus = "pending" | "active" | "suspended" | "deleted";

/** Custom type with Cyrillic name */
export type CustomTypeТипыДанных = "активный" | "неактивный" | "pending";


/** Address details object */
export interface CustomTypeAddressDetails {
    /** City name */
    city: string;
    /** Postal code */
    postal_code?: string;
    /** Street address */
    street: string;
}


/** User profile information */
export interface CustomTypeUserProfile {
    /** User's email address */
    email: CustomTypeEmail;
    /** User's first name */
    first_name: string;
    /** User's last name */
    last_name?: string;
}


// ===== Variant Types =====

/** Feature in beta (string 'beta') */
export interface CustomTypeFeatureConfigCaseBeta {
    /** Feature flag that can be boolean or string */
    feature_flag: "beta";
    /** User tags as array of strings */
    tags?: string[];
}


/** Feature disabled (boolean false) */
export interface CustomTypeFeatureConfigCaseFalse {
    /** Feature flag that can be boolean or string */
    feature_flag: false;
    /** User's first name */
    first_name?: string;
}


/** Feature enabled (boolean true) */
export interface CustomTypeFeatureConfigCaseTrue {
    /** User's age */
    age?: CustomTypeAge;
    /** Feature flag that can be boolean or string */
    feature_flag: true;
}


/** Default case */
export interface CustomTypeFeatureConfigDefault {
    /** Feature flag that can be boolean or string */
    feature_flag: Exclude<boolean | string, true | false | "beta">;
}


/** Feature configuration with variants based on multi-type flag */
export type CustomTypeFeatureConfig = CustomTypeFeatureConfigCaseBeta | CustomTypeFeatureConfigCaseFalse | CustomTypeFeatureConfigCaseTrue | CustomTypeFeatureConfigDefault;


/** Home page variant with no additional properties */
export interface CustomTypePageContextCaseHome {
    /** Type of page */
    page_type: "home";
}


/** Product page variant */
export interface CustomTypePageContextCaseProduct {
    /** Type of page */
    page_type: "product";
    /** Product identifier */
    product_id: string;
}


/** Search page variant */
export interface CustomTypePageContextCaseSearch {
    /** Type of page */
    page_type: "search";
    /** Search query */
    query: string;
}


/** Default case */
export interface CustomTypePageContextDefault {
    /** Additional page data */
    page_data?: Record<string, unknown>;
    /** Type of page */
    page_type: Exclude<string, "search" | "product" | "home">;
}


/** Page context with variants based on page type */
export type CustomTypePageContext = CustomTypePageContextCaseHome | CustomTypePageContextCaseProduct | CustomTypePageContextCaseSearch | CustomTypePageContextDefault;


/** Inactive user access */
export interface CustomTypeUserAccessCaseFalse {
    /** User active status */
    active: false;
    /** User account status */
    status: CustomTypeStatus;
}


/** Active user access */
export interface CustomTypeUserAccessCaseTrue {
    /** User active status */
    active: true;
    /** User's email address */
    email: CustomTypeEmail;
}


/** Default case */
export interface CustomTypeUserAccessDefault {
    /** User active status */
    active: Exclude<CustomTypeActive, true | false>;
}


/** User access with variants based on active status */
export type CustomTypeUserAccess = CustomTypeUserAccessCaseFalse | CustomTypeUserAccessCaseTrue | CustomTypeUserAccessDefault;


/** Desktop page view */
export interface EventWithVariantsCaseDesktop {
    /** Type of device */
    device_type: "desktop";
    /** User's first name */
    first_name: string;
    /** User's last name */
    last_name?: string;
    /** Page context information */
    page_context?: CustomTypePageContext;
    /** User profile data */
    profile: CustomTypeUserProfile;
}


/** Mobile device page view */
export interface EventWithVariantsCaseMobile {
    /** Type of device */
    device_type: "mobile";
    /** Page context information */
    page_context?: CustomTypePageContext;
    /** User profile data */
    profile: CustomTypeUserProfile;
    /** User tags as array of strings */
    tags?: string[];
}


/** Default case */
export interface EventWithVariantsDefault {
    /** Type of device */
    device_type: Exclude<PropertyDeviceType, "mobile" | "desktop">;
    /** Page context information */
    page_context?: CustomTypePageContext;
    /** User profile data */
    profile: CustomTypeUserProfile;
    /** A field with no explicit type (treated as any) */
    untyped_field?: unknown;
}


/** Example event to demonstrate variants */
export type EventWithVariants = EventWithVariantsCaseDesktop | EventWithVariantsCaseMobile | EventWithVariantsDefault;


// ===== Nested Object Types =====

/** demonstrates multiple levels of nesting */
export interface UserSignedUpContextNestedContext {
    /** Array of favorite colors using custom type */
    favorite_colors?: CustomTypeColor[];
    /** User profile data */
    profile?: CustomTypeUserProfile;
}


/** example of object property */
export interface UserSignedUpContext {
    /** IP address of the user */
    ip_address: string;
    /** demonstrates multiple levels of nesting */
    nested_context: UserSignedUpContextNestedContext;
}


// ===== Event Types =====

/** Group association event */
export interface GroupTraits {
    /** User active status */
    active: CustomTypeActive;
    /** User account status */
    status?: CustomTypeStatus;
}


/** User identification event */
export interface IdentifyTraits {
    /** User active status */
    active?: CustomTypeActive;
    /** User's email address */
    email: CustomTypeEmail;
}


/** Page view event */
export interface PageProperties {
    /** User profile data */
    profile: CustomTypeUserProfile;
}


/** Event with dollar signs to test string interpolation escaping */
export interface VariableString {
    /** Field with $ for testing string interpolation: $variable and ${expression} */
    dollar_field: PropertyDollarField;
}


/** Event with special characters that collide after sanitization */
export interface EventWithNameCamelCase {
    /** User's email address */
    email?: CustomTypeEmail;
}


/** Triggered when user clicks on a "premium" product /\* important *\/ */
export interface ProductPremiumClicked {
    /** Field with special chars: "quotes", backslash\path, and /\* comment *\/ */
    special_field: string;
    /** HTTP status with special characters */
    status_code?: PropertyStatusCode;
}


/** Triggered when a user signs up */
export interface UserSignedUp {
    /** User active status */
    active: CustomTypeActive;
    /** User's addresses */
    addresses?: CustomTypeAddressList;
    /** User's age */
    age?: CustomTypeAge;
    /** An array that can contain any type of items */
    array_of_any?: unknown[];
    /** Array with items that can be string or null */
    array_with_null_items?: Array<string | null>;
    /** Array of user contacts */
    contacts?: CustomTypeEmail[];
    /** example of object property */
    context?: UserSignedUpContext;
    /** Property using custom null type */
    custom_null_field?: CustomTypeNullType;
    /** Type of device */
    device_type?: PropertyDeviceType;
    /** User's email addresses */
    email_list?: CustomTypeEmailList;
    /** Property with empty object not allowing additional properties */
    empty_object_no_additional_props?: CustomTypeEmptyObjectNoAdditionalProps;
    /** Property with empty object allowing additional properties */
    empty_object_with_additional_props?: CustomTypeEmptyObjectWithAdditionalProps;
    /** Feature enabled flag */
    enabled?: PropertyEnabled;
    /** Feature configuration information */
    feature_config?: CustomTypeFeatureConfig;
    /** Property with mixed unicode: café, naïve, 日本語 */
    mixed_unicode?: string;
    /** Mixed type enum */
    mixed_value?: PropertyMixedValue;
    /** An array with items that can be string or integer */
    multi_type_array?: Array<string | number>;
    /** A field that can be string, integer, or boolean */
    multi_type_field?: string | number | boolean;
    /** Property that can be string, integer, or null */
    multi_type_with_null?: string | number | null;
    /** Nested property with empty object allowing additional properties */
    nested_empty_object?: Record<string, unknown>;
    /** Nested property with empty object not allowing additional properties */
    nested_empty_object_no_additional_props?: Record<string, never>;
    /** Property that is always null */
    null_field?: null;
    /** Property that can be number or null */
    number_or_null?: number | null;
    /** An object field with no defined structure */
    object_property?: Record<string, unknown>;
    /** Array of phone numbers using custom type */
    phone_numbers?: CustomTypePhoneNumber[];
    /** Priority level */
    priority?: PropertyPriority;
    /** User profile data */
    profile: CustomTypeUserProfile;
    /** List of related user profiles */
    profile_list?: CustomTypeProfileList;
    /** A field that can contain any type of value */
    property_of_any?: unknown;
    /** Rating value */
    rating?: PropertyRating;
    /** User account status */
    status?: CustomTypeStatus;
    /** Property that can be string or null */
    string_or_null?: string | null;
    /** User tags as array of strings */
    tags?: string[];
    /** Property using custom type with Unicode */
    unicode_custom_type?: CustomTypeТипыДанных;
    /** Field demonstrating various Unicode characters in enum values */
    unicode_enum_field?: PropertyUnicodeEnumField;
    /** An array with no explicit item type (treated as any) */
    untyped_array?: unknown[];
    /** A field with no explicit type (treated as any) */
    untyped_field?: unknown;
    /** User access information */
    user_access?: CustomTypeUserAccess;
    /** Username in Chinese characters */
    "用户名"?: string;
}


/** Event with camel case name */
export interface EventWithNameCamelCase1 {
    /** User active status */
    active?: CustomTypeActive;
}


// ===== RudderTyper =====

/**
 * Type-safe wrappers for RudderStack tracking based on your Tracking Plan.
 *
 * Tracking Plan: Test Plan (https://app.rudderstack.com/trackingPlans/plan_12345)
 * - ID: plan_12345
 * - Version: 13
 *
 * @example
 * ```ts
 * import { RudderAnalytics } from "@rudderstack/analytics-js";
 * import { RudderTyper } from "./RudderTyper";
 *
 * const analytics = new RudderAnalytics();
 * analytics.load("YOUR_WRITE_KEY", "YOUR_DATA_PLANE_URL");
 * const rudderTyper = new RudderTyper(analytics);
 * ```
 */
export class RudderTyper {
    private readonly analytics: RudderAnalytics;

    constructor(analytics: RudderAnalytics) {
        this.analytics = analytics;
    }

    public group(
        groupId: string,
        traits?: GroupTraits,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void;
    public group(
        traits?: GroupTraits,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void;
    /**
     * Group association event
     */
    public group(
        groupIdOrTraits?: string | GroupTraits,
        traitsOrOptions?: GroupTraits | ApiOptions,
        optionsOrCallback?: ApiOptions | ApiCallback,
        callback?: ApiCallback,
    ): void {
        if (typeof groupIdOrTraits === "string") {
            this.analytics.group(
                groupIdOrTraits,
                undefined,
                this.withRudderTyperContext(optionsOrCallback as ApiOptions | undefined, traitsOrOptions as unknown as SDKApiObject),
                callback,
            );
        } else {
            this.analytics.group(
                null,
                this.withRudderTyperContext(traitsOrOptions as ApiOptions | undefined, groupIdOrTraits as unknown as SDKApiObject),
                optionsOrCallback as ApiCallback | undefined,
            );
        }
    }

    public identify(
        userId: string,
        traits?: IdentifyTraits,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void;
    public identify(
        traits?: IdentifyTraits,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void;
    /**
     * User identification event
     */
    public identify(
        userIdOrTraits?: string | IdentifyTraits,
        traitsOrOptions?: IdentifyTraits | ApiOptions,
        optionsOrCallback?: ApiOptions | ApiCallback,
        callback?: ApiCallback,
    ): void {
        if (typeof userIdOrTraits === "string") {
            this.analytics.identify(
                userIdOrTraits,
                traitsOrOptions as unknown as SDKIdentifyTraits,
                this.withRudderTyperContext(optionsOrCallback as ApiOptions | undefined),
                callback,
            );
        } else {
            this.analytics.identify(
                userIdOrTraits as unknown as SDKIdentifyTraits,
                this.withRudderTyperContext(traitsOrOptions as ApiOptions | undefined),
                optionsOrCallback as ApiCallback | undefined,
            );
        }
    }

    public page(
        category: string,
        name: string,
        properties?: PageProperties,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void;
    public page(
        name: string,
        properties?: PageProperties,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void;
    public page(
        properties?: PageProperties,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void;
    /**
     * Page view event
     */
    public page(
        arg0?: string | PageProperties,
        arg1?: string | PageProperties | ApiOptions,
        arg2?: PageProperties | ApiOptions | ApiCallback,
        arg3?: ApiOptions | ApiCallback,
        arg4?: ApiCallback,
    ): void {
        if (typeof arg0 === "string" && typeof arg1 === "string") {
            this.analytics.page(
                arg0,
                arg1,
                arg2 as unknown as SDKApiObject,
                this.withRudderTyperContext(arg3 as ApiOptions | undefined),
                arg4,
            );
        } else if (typeof arg0 === "string") {
            this.analytics.page(
                arg0,
                arg1 as unknown as SDKApiObject,
                this.withRudderTyperContext(arg2 as ApiOptions | undefined),
                arg3 as ApiCallback | undefined,
            );
        } else {
            this.analytics.page(
                arg0 as unknown as SDKApiObject,
                this.withRudderTyperContext(arg1 as ApiOptions | undefined),
                arg2 as ApiCallback | undefined,
            );
        }
    }

    /**
     * Event with dollar signs to test string interpolation escaping
     *
     * @param props - The properties to include with this event
     * @param options - Optional ApiOptions for additional event configuration
     * @param callback - Optional callback fired after the call is dispatched
     */
    public trackVariableString(
        props: VariableString,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void {
        this.analytics.track(
            "$Variable$String",
            props as unknown as SDKApiObject,
            this.withRudderTyperContext(options),
            callback,
        );
    }

    /**
     * Event with special characters that collide after sanitization
     *
     * @param props - The properties to include with this event
     * @param options - Optional ApiOptions for additional event configuration
     * @param callback - Optional callback fired after the call is dispatched
     */
    public trackEventWithNameCamelCase(
        props: EventWithNameCamelCase,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void {
        this.analytics.track(
            "$eventWithNameCamelCase$!",
            props as unknown as SDKApiObject,
            this.withRudderTyperContext(options),
            callback,
        );
    }

    /**
     * Empty event schema with additionalProperties false
     *
     * @param options - Optional ApiOptions for additional event configuration
     * @param callback - Optional callback fired after the call is dispatched
     */
    public trackEmptyEventNoAdditionalProps(
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void {
        this.analytics.track(
            "Empty Event No Additional Props",
            {},
            this.withRudderTyperContext(options),
            callback,
        );
    }

    /**
     * Empty event schema with additionalProperties true
     *
     * @param props - Additional properties to include with this event
     * @param options - Optional ApiOptions for additional event configuration
     * @param callback - Optional callback fired after the call is dispatched
     */
    public trackEmptyEventWithAdditionalProps(
        props?: Record<string, unknown>,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void {
        this.analytics.track(
            "Empty Event With Additional Props",
            props as unknown as SDKApiObject,
            this.withRudderTyperContext(options),
            callback,
        );
    }

    /**
     * Example event to demonstrate variants
     *
     * @param props - The properties to include with this event
     * @param options - Optional ApiOptions for additional event configuration
     * @param callback - Optional callback fired after the call is dispatched
     */
    public trackEventWithVariants(
        props: EventWithVariants,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void {
        this.analytics.track(
            "Event With Variants",
            props as unknown as SDKApiObject,
            this.withRudderTyperContext(options),
            callback,
        );
    }

    /**
     * Triggered when user clicks on a "premium" product /\* important *\/
     *
     * @param props - The properties to include with this event
     * @param options - Optional ApiOptions for additional event configuration
     * @param callback - Optional callback fired after the call is dispatched
     */
    public trackProductPremiumClicked(
        props: ProductPremiumClicked,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void {
        this.analytics.track(
            "Product \"Premium\" Clicked",
            props as unknown as SDKApiObject,
            this.withRudderTyperContext(options),
            callback,
        );
    }

    /**
     * Triggered when a user signs up
     *
     * @param props - The properties to include with this event
     * @param options - Optional ApiOptions for additional event configuration
     * @param callback - Optional callback fired after the call is dispatched
     */
    public trackUserSignedUp(
        props: UserSignedUp,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void {
        this.analytics.track(
            "User Signed Up",
            props as unknown as SDKApiObject,
            this.withRudderTyperContext(options),
            callback,
        );
    }

    /**
     * Event with camel case name
     *
     * @param props - The properties to include with this event
     * @param options - Optional ApiOptions for additional event configuration
     * @param callback - Optional callback fired after the call is dispatched
     */
    public trackEventWithNameCamelCase1(
        props: EventWithNameCamelCase1,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void {
        this.analytics.track(
            "eventWithNameCamelCase",
            props as unknown as SDKApiObject,
            this.withRudderTyperContext(options),
            callback,
        );
    }

    private withRudderTyperContext(options?: ApiOptions, contextTraits?: SDKApiObject): ApiOptions {
        const rudderTyperContext: SDKApiObject = {
            ruddertyper: {
                "platform": "typescript",
                "rudderCLIVersion": "1.0.0",
                "trackingPlanId": "plan_12345",
                "trackingPlanVersion": 13,
            },
        };
        if (contextTraits) {
            rudderTyperContext["traits"] = contextTraits;
        }
        return {
            ...(options ?? {}),
            context: {
                ...((options?.context ?? {}) as SDKApiObject),
                ...rudderTyperContext,
            },
        };
    }
}
