/**
 * RudderTyper.ts
 * This file was automatically generated by Rudder CLI 1.0.0.
 * Do not modify manually.
 */

import type { ApiOptions, RudderAnalytics } from "@rudderstack/analytics-js";

// ===== Event Traits =====

/** User identification event */
export interface IdentifyTraits {
    /** User active status */
    active?: boolean;
    /** User's email address */
    email: string;
}

// ===== RudderTyper =====

/**
 * Type-safe wrappers for RudderStack tracking based on your Tracking Plan.
 *
 * Tracking Plan: Test Plan (https://app.rudderstack.com/trackingPlans/plan_12345)
 * - ID: plan_12345
 * - Version: 13
 *
 * @example
 * ```ts
 * import { RudderAnalytics } from "@rudderstack/analytics-js";
 * import { RudderTyper } from "./RudderTyper";
 *
 * const analytics = new RudderAnalytics();
 * analytics.load("YOUR_WRITE_KEY", "YOUR_DATA_PLANE_URL");
 * const rudderTyper = new RudderTyper(analytics);
 * ```
 */
export class RudderTyper {
    private readonly analytics: RudderAnalytics;

    constructor(analytics: RudderAnalytics) {
        this.analytics = analytics;
    }

    /**
     * User identification event
     *
     * @param userId - The user identifier
     * @param traits - The traits to include with this event
     * @param options - Optional ApiOptions for additional event configuration
     */
    public identify(
        userId: string,
        traits?: IdentifyTraits,
        options?: ApiOptions,
    ): void {
        this.analytics.identify(
            userId,
            traits,
            this.withRudderTyperContext(options),
        );
    }

    private withRudderTyperContext(options?: ApiOptions): ApiOptions {
        const rudderTyperContext = {
            ruddertyper: {
                "platform": "typescript",
                "rudderCLIVersion": "1.0.0",
                "trackingPlanId": "plan_12345",
                "trackingPlanVersion": 13,
            },
        };
        return {
            ...(options ?? {}),
            context: {
                ...((options?.context ?? {}) as Record<string, unknown>),
                ...rudderTyperContext,
            },
        };
    }
}
