//
// RudderTyper.swift
// This client was automatically generated by RudderTyper CLI. ** Do Not Edit **
//

import Foundation
import RudderStackAnalytics

// MARK: - Custom Types

/// Whether user is active
public typealias CustomTypeActive = Bool

/// List of addresses
public typealias CustomTypeAddressList = [CustomTypeAddressDetails]

/// User's age in years
public typealias CustomTypeAge = Double

/// Custom type for Colors
public typealias CustomTypeColor = String

/// Custom type for email validation
public typealias CustomTypeEmail = String

/// List of email addresses
public typealias CustomTypeEmailList = [CustomTypeEmail]

/// Empty object that does not allow additional properties
public typealias CustomTypeEmptyObjectNoAdditionalProps = [String: Any]

/// Empty object that allows additional properties
public typealias CustomTypeEmptyObjectWithAdditionalProps = [String: Any]

/// Custom type representing a null value
public typealias CustomTypeNullType = NSNull

/// Custom type for phone numbers
public typealias CustomTypePhoneNumber = String

/// List of user profiles
public typealias CustomTypeProfileList = [CustomTypeUserProfile]

/// Empty event schema with additionalProperties true
public typealias TrackEmptyEventWithAdditionalPropsProperties = [String: Any]

/// Feature configuration with variants based on multi-type flag
public enum CustomTypeFeatureConfig {
    /// Feature enabled (boolean true)
    case caseTrue(CaseTrue)
    /// Feature disabled (boolean false)
    case caseFalse(CaseFalse)
    /// Feature in beta (string 'beta')
    case caseBeta(CaseBeta)
    case other(Default)

    /// Feature enabled (boolean true)
    public struct CaseTrue {
        /// User's age
        public var age: CustomTypeAge?
        /// Feature flag that can be boolean or string
        public var featureFlag: PropertyFeatureFlag
        public init(
            featureFlag: PropertyFeatureFlag,
            age: CustomTypeAge? = nil
        ) {
            self.age = age
            self.featureFlag = featureFlag
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [
                "feature_flag": featureFlag.value
            ]
            if let age = age { props["age"] = age }
            return props
        }
    }

    /// Feature disabled (boolean false)
    public struct CaseFalse {
        /// Feature flag that can be boolean or string
        public var featureFlag: PropertyFeatureFlag
        /// User's first name
        public var firstName: PropertyFirstName?
        public init(
            featureFlag: PropertyFeatureFlag,
            firstName: PropertyFirstName? = nil
        ) {
            self.featureFlag = featureFlag
            self.firstName = firstName
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [
                "feature_flag": featureFlag.value
            ]
            if let firstName = firstName { props["first_name"] = firstName }
            return props
        }
    }

    /// Feature in beta (string 'beta')
    public struct CaseBeta {
        /// Feature flag that can be boolean or string
        public var featureFlag: PropertyFeatureFlag
        /// User tags as array of strings
        public var tags: PropertyTags?
        public init(
            featureFlag: PropertyFeatureFlag,
            tags: PropertyTags? = nil
        ) {
            self.featureFlag = featureFlag
            self.tags = tags
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [
                "feature_flag": featureFlag.value
            ]
            if let tags = tags { props["tags"] = tags }
            return props
        }
    }

    /// Default case for unmatched discriminator values
    public struct Default {
        public init() {}

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [:]
            return props
        }
    }

    public var discriminator: String {
        switch self {
        case .caseTrue: return "true"
        case .caseFalse: return "false"
        case .caseBeta: return "beta"
        case .other: return ""
        }
    }

    public func toProperties() -> [String: Any] {
        switch self {
        case .caseTrue(let data): return data.toProperties()
        case .caseFalse(let data): return data.toProperties()
        case .caseBeta(let data): return data.toProperties()
        case .other(let data): return data.toProperties()
        }
    }
}

/// Page context with variants based on page type
public enum CustomTypePageContext {
    /// Search page variant
    case caseSearch(CaseSearch)
    /// Product page variant
    case caseProduct(CaseProduct)
    /// Home page variant with no additional properties
    case caseHome(CaseHome)
    case other(Default)

    /// Search page variant
    public struct CaseSearch {
        /// Type of page
        public var pageType: PropertyPageType
        /// Search query
        public var query: PropertyQuery
        public init(
            pageType: PropertyPageType,
            query: PropertyQuery
        ) {
            self.pageType = pageType
            self.query = query
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [
                "page_type": pageType,
                "query": query
            ]
            return props
        }
    }

    /// Product page variant
    public struct CaseProduct {
        /// Type of page
        public var pageType: PropertyPageType
        /// Product identifier
        public var productId: PropertyProductId
        public init(
            pageType: PropertyPageType,
            productId: PropertyProductId
        ) {
            self.pageType = pageType
            self.productId = productId
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [
                "page_type": pageType,
                "product_id": productId
            ]
            return props
        }
    }

    /// Home page variant with no additional properties
    public struct CaseHome {
        /// Type of page
        public var pageType: PropertyPageType
        public init(
            pageType: PropertyPageType
        ) {
            self.pageType = pageType
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [
                "page_type": pageType
            ]
            return props
        }
    }

    /// Default case for unmatched discriminator values
    public struct Default {
        /// Additional page data
        public var pageData: PropertyPageData?
        public init(
            pageData: PropertyPageData? = nil
        ) {
            self.pageData = pageData
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [:]
            if let pageData = pageData { props["page_data"] = pageData }
            return props
        }
    }

    public var discriminator: String {
        switch self {
        case .caseSearch: return "search"
        case .caseProduct: return "product"
        case .caseHome: return "home"
        case .other: return ""
        }
    }

    public func toProperties() -> [String: Any] {
        switch self {
        case .caseSearch(let data): return data.toProperties()
        case .caseProduct(let data): return data.toProperties()
        case .caseHome(let data): return data.toProperties()
        case .other(let data): return data.toProperties()
        }
    }
}

/// User access with variants based on active status
public enum CustomTypeUserAccess {
    /// Active user access
    case caseTrue(CaseTrue)
    /// Inactive user access
    case caseFalse(CaseFalse)
    case other(Default)

    /// Active user access
    public struct CaseTrue {
        /// User active status
        public var active: CustomTypeActive
        /// User's email address
        public var email: CustomTypeEmail
        public init(
            active: CustomTypeActive,
            email: CustomTypeEmail
        ) {
            self.active = active
            self.email = email
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [
                "active": active,
                "email": email
            ]
            return props
        }
    }

    /// Inactive user access
    public struct CaseFalse {
        /// User active status
        public var active: CustomTypeActive
        /// User account status
        public var status: CustomTypeStatus
        public init(
            active: CustomTypeActive,
            status: CustomTypeStatus
        ) {
            self.active = active
            self.status = status
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [
                "active": active,
                "status": status.rawValue
            ]
            return props
        }
    }

    /// Default case for unmatched discriminator values
    public struct Default {
        public init() {}

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [:]
            return props
        }
    }

    public var discriminator: String {
        switch self {
        case .caseTrue: return "true"
        case .caseFalse: return "false"
        case .other: return ""
        }
    }

    public func toProperties() -> [String: Any] {
        switch self {
        case .caseTrue(let data): return data.toProperties()
        case .caseFalse(let data): return data.toProperties()
        case .other(let data): return data.toProperties()
        }
    }
}

/// Example event to demonstrate variants
public enum TrackEventWithVariantsProperties {
    /// Mobile device page view
    case caseMobile(CaseMobile)
    /// Desktop page view
    case caseDesktop(CaseDesktop)
    case other(Default)

    /// Mobile device page view
    public struct CaseMobile {
        /// Type of device
        public var deviceType: PropertyDeviceType
        /// Page context information
        public var pageContext: CustomTypePageContext?
        /// User profile data
        public var profile: CustomTypeUserProfile
        /// User tags as array of strings
        public var tags: PropertyTags?
        public init(
            deviceType: PropertyDeviceType,
            profile: CustomTypeUserProfile,
            pageContext: CustomTypePageContext? = nil,
            tags: PropertyTags? = nil
        ) {
            self.deviceType = deviceType
            self.pageContext = pageContext
            self.profile = profile
            self.tags = tags
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [
                "device_type": deviceType.rawValue,
                "profile": profile.toProperties()
            ]
            if let pageContext = pageContext { props["page_context"] = pageContext.toProperties() }
            if let tags = tags { props["tags"] = tags }
            return props
        }
    }

    /// Desktop page view
    public struct CaseDesktop {
        /// Type of device
        public var deviceType: PropertyDeviceType
        /// User's first name
        public var firstName: PropertyFirstName
        /// User's last name
        public var lastName: PropertyLastName?
        /// Page context information
        public var pageContext: CustomTypePageContext?
        /// User profile data
        public var profile: CustomTypeUserProfile
        public init(
            deviceType: PropertyDeviceType,
            firstName: PropertyFirstName,
            profile: CustomTypeUserProfile,
            lastName: PropertyLastName? = nil,
            pageContext: CustomTypePageContext? = nil
        ) {
            self.deviceType = deviceType
            self.firstName = firstName
            self.lastName = lastName
            self.pageContext = pageContext
            self.profile = profile
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [
                "device_type": deviceType.rawValue,
                "first_name": firstName,
                "profile": profile.toProperties()
            ]
            if let lastName = lastName { props["last_name"] = lastName }
            if let pageContext = pageContext { props["page_context"] = pageContext.toProperties() }
            return props
        }
    }

    /// Default case for unmatched discriminator values
    public struct Default {
        /// A field with no explicit type (treated as any)
        public var untypedField: Any?
        public init(
            untypedField: Any? = nil
        ) {
            self.untypedField = untypedField
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [:]
            if let untypedField = untypedField { props["untyped_field"] = untypedField }
            return props
        }
    }

    public var discriminator: String {
        switch self {
        case .caseMobile: return "mobile"
        case .caseDesktop: return "desktop"
        case .other: return ""
        }
    }

    public func toProperties() -> [String: Any] {
        switch self {
        case .caseMobile(let data): return data.toProperties()
        case .caseDesktop(let data): return data.toProperties()
        case .other(let data): return data.toProperties()
        }
    }
}

// MARK: - Property Types

/// User active status
public typealias PropertyActive = CustomTypeActive

/// User's addresses
public typealias PropertyAddresses = CustomTypeAddressList

/// User's age
public typealias PropertyAge = CustomTypeAge

/// An array that can contain any type of items
public typealias PropertyArrayOfAny = [Any]

/// Array with items that can be string or null
public typealias PropertyArrayWithNullItems = [PropertyArrayWithNullItemsItem]

/// City name
public typealias PropertyCity = String

/// Array of user contacts
public typealias PropertyContacts = [CustomTypeEmail]

/// example of object property
public typealias PropertyContext = [String: Any]

/// Property using custom null type
public typealias PropertyCustomNullField = CustomTypeNullType

/// User's email address
public typealias PropertyEmail = CustomTypeEmail

/// User's email addresses
public typealias PropertyEmailList = CustomTypeEmailList

/// Property with empty object not allowing additional properties
public typealias PropertyEmptyObjectNoAdditionalProps = CustomTypeEmptyObjectNoAdditionalProps

/// Property with empty object allowing additional properties
public typealias PropertyEmptyObjectWithAdditionalProps = CustomTypeEmptyObjectWithAdditionalProps

/// Array of favorite colors using custom type
public typealias PropertyFavoriteColors = [CustomTypeColor]

/// Feature configuration information
public typealias PropertyFeatureConfig = CustomTypeFeatureConfig

/// User's first name
public typealias PropertyFirstName = String

/// IP address of the user
public typealias PropertyIpAddress = String

/// User's last name
public typealias PropertyLastName = String

/// Property with mixed unicode: café, naïve, 日本語
public typealias PropertyMixedUnicode = String

/// An array with items that can be string or integer
public typealias PropertyMultiTypeArray = [PropertyMultiTypeArrayItem]

/// demonstrates multiple levels of nesting
public typealias PropertyNestedContext = [String: Any]

/// Nested property with empty object allowing additional properties
public typealias PropertyNestedEmptyObject = [String: Any]

/// Nested property with empty object not allowing additional properties
public typealias PropertyNestedEmptyObjectNoAdditionalProps = [String: Any]

/// Property that is always null
public typealias PropertyNullField = NSNull

/// An object field with no defined structure
public typealias PropertyObjectProperty = [String: Any]

/// Page context information
public typealias PropertyPageContext = CustomTypePageContext

/// Additional page data
public typealias PropertyPageData = [String: Any]

/// Type of page
public typealias PropertyPageType = String

/// Array of phone numbers using custom type
public typealias PropertyPhoneNumbers = [CustomTypePhoneNumber]

/// Postal code
public typealias PropertyPostalCode = String

/// Product identifier
public typealias PropertyProductId = String

/// User profile data
public typealias PropertyProfile = CustomTypeUserProfile

/// List of related user profiles
public typealias PropertyProfileList = CustomTypeProfileList

/// A field that can contain any type of value
public typealias PropertyPropertyOfAny = Any

/// Search query
public typealias PropertyQuery = String

/// Field with special chars: "quotes", backslash\path, and /* comment */
public typealias PropertySpecialField = String

/// User account status
public typealias PropertyStatus = CustomTypeStatus

/// Street address
public typealias PropertyStreet = String

/// User tags as array of strings
public typealias PropertyTags = [String]

/// Property using custom type with Unicode
public typealias PropertyUnicodeCustomType = CustomTypeТипыДанных

/// An array with no explicit item type (treated as any)
public typealias PropertyUntypedArray = [Any]

/// A field with no explicit type (treated as any)
public typealias PropertyUntypedField = Any

/// User access information
public typealias PropertyUserAccess = CustomTypeUserAccess

/// Username in Chinese characters
public typealias Property用户名 = String

/// User status enum
public enum CustomTypeStatus: String, CaseIterable {
    case pending = "pending"
    case active = "active"
    case suspended = "suspended"
    case deleted = "deleted"
}

/// Custom type with Cyrillic name
public enum CustomTypeТипыДанных: String, CaseIterable {
    case активный = "активный"
    case неактивный = "неактивный"
    case pending = "pending"
}

/// Type of device
public enum PropertyDeviceType: String, CaseIterable {
    case mobile = "mobile"
    case tablet = "tablet"
    case desktop = "desktop"
    case smartTv = "smartTV"
    case ioTDevice = "IoT-Device"
}

/// Field with $ for testing string interpolation: $variable and ${expression}
public enum PropertyDollarField: String, CaseIterable {
    case usd = "$USD"
    case n100 = "$100"
    case price9999 = "Price: $99.99"
    case variableName = "$variable_name"
}

/// Feature enabled flag
public enum PropertyEnabled: String, CaseIterable {
    case `true` = "true"
    case `false` = "false"
}

/// Mixed type enum
public enum PropertyMixedValue: String, CaseIterable {
    case active = "active"
    case n1 = "1"
    case `true` = "true"
    case n25 = "2.5"
}

/// Priority level
public enum PropertyPriority: Int, CaseIterable {
    case n1 = 1
    case n2 = 2
    case n3 = 3
}

/// Rating value
public enum PropertyRating: Double, CaseIterable {
    case n15 = 1.5
    case n25 = 2.5
    case n35 = 3.5
    case n45 = 4.5
    case n5 = 5
}

/// HTTP status with special characters
public enum PropertyStatusCode: String, CaseIterable {
    case n200Ok = "200: OK"
    case n404NotFound = "404: Not Found"
    case n500InternalServerError = "500: Internal \"Server\" Error"
}

/// Field demonstrating various Unicode characters in enum values
public enum PropertyUnicodeEnumField: String, CaseIterable {
    case u1F3AF = "🎯"
    case u2705 = "✅"
    case активный = "активный"
    case 已完成 = "已完成"
    case ενεργός = "ενεργός"
    case café = "café"
    case u212121 = "!!!"
}

/// Item type for array_with_null_items array
public enum PropertyArrayWithNullItemsItem {
    case string(String)
    case null

    public var value: Any {
        switch self {
        case .string(let v): return v
        case .null: return NSNull()
        }
    }
}

/// Feature flag that can be boolean or string
public enum PropertyFeatureFlag {
    case bool(Bool)
    case string(String)

    public var value: Any {
        switch self {
        case .bool(let v): return v
        case .string(let v): return v
        }
    }
}

/// Item type for multi_type_array array
public enum PropertyMultiTypeArrayItem {
    case string(String)
    case int(Int)

    public var value: Any {
        switch self {
        case .string(let v): return v
        case .int(let v): return v
        }
    }
}

/// A field that can be string, integer, or boolean
public enum PropertyMultiTypeField {
    case string(String)
    case int(Int)
    case bool(Bool)

    public var value: Any {
        switch self {
        case .string(let v): return v
        case .int(let v): return v
        case .bool(let v): return v
        }
    }
}

/// Property that can be string, integer, or null
public enum PropertyMultiTypeWithNull {
    case string(String)
    case int(Int)
    case null

    public var value: Any {
        switch self {
        case .string(let v): return v
        case .int(let v): return v
        case .null: return NSNull()
        }
    }
}

/// Property that can be number or null
public enum PropertyNumberOrNull {
    case double(Double)
    case null

    public var value: Any {
        switch self {
        case .double(let v): return v
        case .null: return NSNull()
        }
    }
}

/// Property that can be string or null
public enum PropertyStringOrNull {
    case string(String)
    case null

    public var value: Any {
        switch self {
        case .string(let v): return v
        case .null: return NSNull()
        }
    }
}

// MARK: - Event Properties

/// Address details object
public struct CustomTypeAddressDetails {
    /// City name
    public var city: PropertyCity
    /// Postal code
    public var postalCode: PropertyPostalCode?
    /// Street address
    public var street: PropertyStreet
    public init(
        city: PropertyCity,
        street: PropertyStreet,
        postalCode: PropertyPostalCode? = nil
    ) {
        self.city = city
        self.postalCode = postalCode
        self.street = street
    }

    public func toProperties() -> [String: Any] {
        var props: [String: Any] = [
            "city": city,
            "street": street
        ]
        if let postalCode = postalCode { props["postal_code"] = postalCode }
        return props
    }
}

/// User profile information
public struct CustomTypeUserProfile {
    /// User's email address
    public var email: CustomTypeEmail
    /// User's first name
    public var firstName: PropertyFirstName
    /// User's last name
    public var lastName: PropertyLastName?
    public init(
        email: CustomTypeEmail,
        firstName: PropertyFirstName,
        lastName: PropertyLastName? = nil
    ) {
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
    }

    public func toProperties() -> [String: Any] {
        var props: [String: Any] = [
            "email": email,
            "first_name": firstName
        ]
        if let lastName = lastName { props["last_name"] = lastName }
        return props
    }
}

/// Group association event
public struct GroupTraits {
    /// User active status
    public var active: CustomTypeActive
    /// User account status
    public var status: CustomTypeStatus?
    public init(
        active: CustomTypeActive,
        status: CustomTypeStatus? = nil
    ) {
        self.active = active
        self.status = status
    }

    public func toTraits() -> [String: Any] {
        var props: [String: Any] = [
            "active": active
        ]
        if let status = status { props["status"] = status.rawValue }
        return props
    }
}

/// User identification event
public struct IdentifyTraits {
    /// User active status
    public var active: CustomTypeActive?
    /// User's email address
    public var email: CustomTypeEmail
    public init(
        email: CustomTypeEmail,
        active: CustomTypeActive? = nil
    ) {
        self.active = active
        self.email = email
    }

    public func toTraits() -> [String: Any] {
        var props: [String: Any] = [
            "email": email
        ]
        if let active = active { props["active"] = active }
        return props
    }
}

/// Screen view event
public struct ScreenProperties {
    /// User profile data
    public var profile: CustomTypeUserProfile?
    public init(
        profile: CustomTypeUserProfile? = nil
    ) {
        self.profile = profile
    }

    public func toProperties() -> [String: Any] {
        var props: [String: Any] = [:]
        if let profile = profile { props["profile"] = profile.toProperties() }
        return props
    }
}

/// Event with dollar signs to test string interpolation escaping
public struct TrackVariable$stringProperties {
    /// Field with $ for testing string interpolation: $variable and ${expression}
    public var dollarField: PropertyDollarField
    public init(
        dollarField: PropertyDollarField
    ) {
        self.dollarField = dollarField
    }

    public func toProperties() -> [String: Any] {
        var props: [String: Any] = [
            "dollar_field": dollarField.rawValue
        ]
        return props
    }
}

/// Event with special characters that collide after sanitization
public struct TrackEventWithNameCamelCaseProperties {
    /// User's email address
    public var email: CustomTypeEmail?
    public init(
        email: CustomTypeEmail? = nil
    ) {
        self.email = email
    }

    public func toProperties() -> [String: Any] {
        var props: [String: Any] = [:]
        if let email = email { props["email"] = email }
        return props
    }
}

/// Triggered when user clicks on a "premium" product /* important */
public struct TrackProductPremiumClickedProperties {
    /// Field with special chars: "quotes", backslash\path, and /* comment */
    public var specialField: PropertySpecialField
    /// HTTP status with special characters
    public var statusCode: PropertyStatusCode?
    public init(
        specialField: PropertySpecialField,
        statusCode: PropertyStatusCode? = nil
    ) {
        self.specialField = specialField
        self.statusCode = statusCode
    }

    public func toProperties() -> [String: Any] {
        var props: [String: Any] = [
            "special_field": specialField
        ]
        if let statusCode = statusCode { props["status_code"] = statusCode.rawValue }
        return props
    }
}

/// Triggered when a user signs up
public struct TrackUserSignedUpProperties {
    /// User active status
    public var active: CustomTypeActive
    /// User's addresses
    public var addresses: CustomTypeAddressList?
    /// User's age
    public var age: CustomTypeAge?
    /// An array that can contain any type of items
    public var arrayOfAny: PropertyArrayOfAny?
    /// Array with items that can be string or null
    public var arrayWithNullItems: PropertyArrayWithNullItems?
    /// Array of user contacts
    public var contacts: PropertyContacts?
    /// example of object property
    public var context: Context?
    /// Property using custom null type
    public var customNullField: CustomTypeNullType?
    /// Type of device
    public var deviceType: PropertyDeviceType?
    /// User's email addresses
    public var emailList: CustomTypeEmailList?
    /// Property with empty object not allowing additional properties
    public var emptyObjectNoAdditionalProps: CustomTypeEmptyObjectNoAdditionalProps?
    /// Property with empty object allowing additional properties
    public var emptyObjectWithAdditionalProps: CustomTypeEmptyObjectWithAdditionalProps?
    /// Feature enabled flag
    public var enabled: PropertyEnabled?
    /// Feature configuration information
    public var featureConfig: CustomTypeFeatureConfig?
    /// Property with mixed unicode: café, naïve, 日本語
    public var mixedUnicode: PropertyMixedUnicode?
    /// Mixed type enum
    public var mixedValue: PropertyMixedValue?
    /// An array with items that can be string or integer
    public var multiTypeArray: PropertyMultiTypeArray?
    /// A field that can be string, integer, or boolean
    public var multiTypeField: PropertyMultiTypeField?
    /// Property that can be string, integer, or null
    public var multiTypeWithNull: PropertyMultiTypeWithNull?
    /// Nested property with empty object allowing additional properties
    public var nestedEmptyObject: PropertyNestedEmptyObject?
    /// Nested property with empty object not allowing additional properties
    public var nestedEmptyObjectNoAdditionalProps: PropertyNestedEmptyObjectNoAdditionalProps?
    /// Property that is always null
    public var nullField: PropertyNullField?
    /// Property that can be number or null
    public var numberOrNull: PropertyNumberOrNull?
    /// An object field with no defined structure
    public var objectProperty: PropertyObjectProperty?
    /// Array of phone numbers using custom type
    public var phoneNumbers: PropertyPhoneNumbers?
    /// Priority level
    public var priority: PropertyPriority?
    /// User profile data
    public var profile: CustomTypeUserProfile
    /// List of related user profiles
    public var profileList: CustomTypeProfileList?
    /// A field that can contain any type of value
    public var propertyOfAny: Any?
    /// Rating value
    public var rating: PropertyRating?
    /// User account status
    public var status: CustomTypeStatus?
    /// Property that can be string or null
    public var stringOrNull: PropertyStringOrNull?
    /// User tags as array of strings
    public var tags: PropertyTags?
    /// Property using custom type with Unicode
    public var unicodeCustomType: CustomTypeТипыДанных?
    /// Field demonstrating various Unicode characters in enum values
    public var unicodeEnumField: PropertyUnicodeEnumField?
    /// An array with no explicit item type (treated as any)
    public var untypedArray: PropertyUntypedArray?
    /// A field with no explicit type (treated as any)
    public var untypedField: Any?
    /// User access information
    public var userAccess: CustomTypeUserAccess?
    /// Username in Chinese characters
    public var 用户名: Property用户名?

    /// example of object property
    public struct Context {
        /// IP address of the user
        public var ipAddress: PropertyIpAddress
        /// demonstrates multiple levels of nesting
        public var nestedContext: NestedContext

        /// demonstrates multiple levels of nesting
        public struct NestedContext {
            /// Array of favorite colors using custom type
            public var favoriteColors: PropertyFavoriteColors?
            /// User profile data
            public var profile: CustomTypeUserProfile?
            public init(
                favoriteColors: PropertyFavoriteColors? = nil,
                profile: CustomTypeUserProfile? = nil
            ) {
                self.favoriteColors = favoriteColors
                self.profile = profile
            }

            public func toProperties() -> [String: Any] {
                var props: [String: Any] = [:]
                if let favoriteColors = favoriteColors { props["favorite_colors"] = favoriteColors }
                if let profile = profile { props["profile"] = profile.toProperties() }
                return props
            }
        }
        public init(
            ipAddress: PropertyIpAddress,
            nestedContext: NestedContext
        ) {
            self.ipAddress = ipAddress
            self.nestedContext = nestedContext
        }

        public func toProperties() -> [String: Any] {
            var props: [String: Any] = [
                "ip_address": ipAddress,
                "nested_context": nestedContext.toProperties()
            ]
            return props
        }
    }
    public init(
        active: CustomTypeActive,
        profile: CustomTypeUserProfile,
        addresses: CustomTypeAddressList? = nil,
        age: CustomTypeAge? = nil,
        arrayOfAny: PropertyArrayOfAny? = nil,
        arrayWithNullItems: PropertyArrayWithNullItems? = nil,
        contacts: PropertyContacts? = nil,
        context: Context? = nil,
        customNullField: CustomTypeNullType? = nil,
        deviceType: PropertyDeviceType? = nil,
        emailList: CustomTypeEmailList? = nil,
        emptyObjectNoAdditionalProps: CustomTypeEmptyObjectNoAdditionalProps? = nil,
        emptyObjectWithAdditionalProps: CustomTypeEmptyObjectWithAdditionalProps? = nil,
        enabled: PropertyEnabled? = nil,
        featureConfig: CustomTypeFeatureConfig? = nil,
        mixedUnicode: PropertyMixedUnicode? = nil,
        mixedValue: PropertyMixedValue? = nil,
        multiTypeArray: PropertyMultiTypeArray? = nil,
        multiTypeField: PropertyMultiTypeField? = nil,
        multiTypeWithNull: PropertyMultiTypeWithNull? = nil,
        nestedEmptyObject: PropertyNestedEmptyObject? = nil,
        nestedEmptyObjectNoAdditionalProps: PropertyNestedEmptyObjectNoAdditionalProps? = nil,
        nullField: PropertyNullField? = nil,
        numberOrNull: PropertyNumberOrNull? = nil,
        objectProperty: PropertyObjectProperty? = nil,
        phoneNumbers: PropertyPhoneNumbers? = nil,
        priority: PropertyPriority? = nil,
        profileList: CustomTypeProfileList? = nil,
        propertyOfAny: Any? = nil,
        rating: PropertyRating? = nil,
        status: CustomTypeStatus? = nil,
        stringOrNull: PropertyStringOrNull? = nil,
        tags: PropertyTags? = nil,
        unicodeCustomType: CustomTypeТипыДанных? = nil,
        unicodeEnumField: PropertyUnicodeEnumField? = nil,
        untypedArray: PropertyUntypedArray? = nil,
        untypedField: Any? = nil,
        userAccess: CustomTypeUserAccess? = nil,
        用户名: Property用户名? = nil
    ) {
        self.active = active
        self.addresses = addresses
        self.age = age
        self.arrayOfAny = arrayOfAny
        self.arrayWithNullItems = arrayWithNullItems
        self.contacts = contacts
        self.context = context
        self.customNullField = customNullField
        self.deviceType = deviceType
        self.emailList = emailList
        self.emptyObjectNoAdditionalProps = emptyObjectNoAdditionalProps
        self.emptyObjectWithAdditionalProps = emptyObjectWithAdditionalProps
        self.enabled = enabled
        self.featureConfig = featureConfig
        self.mixedUnicode = mixedUnicode
        self.mixedValue = mixedValue
        self.multiTypeArray = multiTypeArray
        self.multiTypeField = multiTypeField
        self.multiTypeWithNull = multiTypeWithNull
        self.nestedEmptyObject = nestedEmptyObject
        self.nestedEmptyObjectNoAdditionalProps = nestedEmptyObjectNoAdditionalProps
        self.nullField = nullField
        self.numberOrNull = numberOrNull
        self.objectProperty = objectProperty
        self.phoneNumbers = phoneNumbers
        self.priority = priority
        self.profile = profile
        self.profileList = profileList
        self.propertyOfAny = propertyOfAny
        self.rating = rating
        self.status = status
        self.stringOrNull = stringOrNull
        self.tags = tags
        self.unicodeCustomType = unicodeCustomType
        self.unicodeEnumField = unicodeEnumField
        self.untypedArray = untypedArray
        self.untypedField = untypedField
        self.userAccess = userAccess
        self.用户名 = 用户名
    }

    public func toProperties() -> [String: Any] {
        var props: [String: Any] = [
            "active": active,
            "profile": profile.toProperties()
        ]
        if let addresses = addresses { props["addresses"] = addresses }
        if let age = age { props["age"] = age }
        if let arrayOfAny = arrayOfAny { props["array_of_any"] = arrayOfAny }
        if let arrayWithNullItems = arrayWithNullItems { props["array_with_null_items"] = arrayWithNullItems }
        if let contacts = contacts { props["contacts"] = contacts }
        if let context = context { props["context"] = context.toProperties() }
        if let customNullField = customNullField { props["custom_null_field"] = customNullField }
        if let deviceType = deviceType { props["device_type"] = deviceType.rawValue }
        if let emailList = emailList { props["email_list"] = emailList }
        if let emptyObjectNoAdditionalProps = emptyObjectNoAdditionalProps { props["empty_object_no_additional_props"] = emptyObjectNoAdditionalProps }
        if let emptyObjectWithAdditionalProps = emptyObjectWithAdditionalProps { props["empty_object_with_additional_props"] = emptyObjectWithAdditionalProps }
        if let enabled = enabled { props["enabled"] = enabled.rawValue }
        if let featureConfig = featureConfig { props["feature_config"] = featureConfig.toProperties() }
        if let mixedUnicode = mixedUnicode { props["mixed_unicode"] = mixedUnicode }
        if let mixedValue = mixedValue { props["mixed_value"] = mixedValue.rawValue }
        if let multiTypeArray = multiTypeArray { props["multi_type_array"] = multiTypeArray }
        if let multiTypeField = multiTypeField { props["multi_type_field"] = multiTypeField.value }
        if let multiTypeWithNull = multiTypeWithNull { props["multi_type_with_null"] = multiTypeWithNull.value }
        if let nestedEmptyObject = nestedEmptyObject { props["nested_empty_object"] = nestedEmptyObject }
        if let nestedEmptyObjectNoAdditionalProps = nestedEmptyObjectNoAdditionalProps { props["nested_empty_object_no_additional_props"] = nestedEmptyObjectNoAdditionalProps }
        if let nullField = nullField { props["null_field"] = nullField }
        if let numberOrNull = numberOrNull { props["number_or_null"] = numberOrNull.value }
        if let objectProperty = objectProperty { props["object_property"] = objectProperty }
        if let phoneNumbers = phoneNumbers { props["phone_numbers"] = phoneNumbers }
        if let priority = priority { props["priority"] = priority.rawValue }
        if let profileList = profileList { props["profile_list"] = profileList }
        if let propertyOfAny = propertyOfAny { props["property_of_any"] = propertyOfAny }
        if let rating = rating { props["rating"] = rating.rawValue }
        if let status = status { props["status"] = status.rawValue }
        if let stringOrNull = stringOrNull { props["string_or_null"] = stringOrNull.value }
        if let tags = tags { props["tags"] = tags }
        if let unicodeCustomType = unicodeCustomType { props["unicode_custom_type"] = unicodeCustomType.rawValue }
        if let unicodeEnumField = unicodeEnumField { props["unicode_enum_field"] = unicodeEnumField.rawValue }
        if let untypedArray = untypedArray { props["untyped_array"] = untypedArray }
        if let untypedField = untypedField { props["untyped_field"] = untypedField }
        if let userAccess = userAccess { props["user_access"] = userAccess.toProperties() }
        if let 用户名 = 用户名 { props["用户名"] = 用户名 }
        return props
    }
}

/// Event with camel case name
public struct TrackEventWithNameCamelCaseProperties1 {
    /// User active status
    public var active: CustomTypeActive?
    public init(
        active: CustomTypeActive? = nil
    ) {
        self.active = active
    }

    public func toProperties() -> [String: Any] {
        var props: [String: Any] = [:]
        if let active = active { props["active"] = active }
        return props
    }
}

// MARK: - RudderTyperAnalytics

/// Type-safe wrappers for RudderStack tracking based on your Tracking Plan.
///
/// Tracking Plan: Test Plan (https://app.rudderstack.com/trackingPlans/plan_12345)
/// - ID: plan_12345
/// - Version: 13
///
/// ## Quick Start
/// ```swift
/// let analytics = Analytics(configuration: Configuration(
///     writeKey: "YOUR_WRITE_KEY",
///     dataPlaneUrl: "YOUR_DATA_PLANE_URL"
/// ))
/// let rudderTyper = RudderTyperAnalytics(analytics: analytics)
/// ```
public class RudderTyperAnalytics {
    private let analytics: Analytics

    public init(analytics: Analytics) {
        self.analytics = analytics
    }

    // MARK: - Events

    /// Group association event
    /// - Parameters:
    ///   - groupId:
    ///   - traits: The traits to include with this event
    ///   - options: Optional RudderOption for additional event configuration
    public func group(groupId: String,
        traits: GroupTraits? = nil,
        options: RudderOption? = nil
    ) {
        analytics.group(
            groupId: groupId,
            traits: traits?.toTraits(),
            options: withRudderTyperContext(options: options)
        )
    }

    /// User identification event
    /// - Parameters:
    ///   - userId:
    ///   - traits: The traits to include with this event
    ///   - options: Optional RudderOption for additional event configuration
    public func identify(userId: String? = nil,
        traits: IdentifyTraits? = nil,
        options: RudderOption? = nil
    ) {
        analytics.identify(
            userId: userId,
            traits: traits?.toTraits(),
            options: withRudderTyperContext(options: options)
        )
    }

    /// Screen view event
    /// - Parameters:
    ///   - properties: The properties to include with this event
    ///   - category:
    ///   - options: Optional RudderOption for additional event configuration
    public func screen(properties: ScreenProperties,
        category: String? = nil,
        options: RudderOption? = nil
    ) {
        analytics.screen(
            screenName: "",
            category: category,
            properties: properties.toProperties(),
            options: withRudderTyperContext(options: options)
        )
    }

    /// Event with dollar signs to test string interpolation escaping
    /// - Parameters:
    ///   - properties: The properties to include with this event
    ///   - options: Optional RudderOption for additional event configuration
    public func trackVariable$string(properties: TrackVariable$stringProperties,
        options: RudderOption? = nil
    ) {
        analytics.track(
            name: "$Variable$String",
            properties: properties.toProperties(),
            options: withRudderTyperContext(options: options)
        )
    }

    /// Event with special characters that collide after sanitization
    /// - Parameters:
    ///   - properties: The properties to include with this event
    ///   - options: Optional RudderOption for additional event configuration
    public func trackEventWithNameCamelCase(properties: TrackEventWithNameCamelCaseProperties,
        options: RudderOption? = nil
    ) {
        analytics.track(
            name: "$eventWithNameCamelCase$!",
            properties: properties.toProperties(),
            options: withRudderTyperContext(options: options)
        )
    }

    /// Empty event schema with additionalProperties false
    /// - Parameters:
    ///   - options: Optional RudderOption for additional event configuration
    public func trackEmptyEventNoAdditionalProps(options: RudderOption? = nil
    ) {
        analytics.track(
            name: "Empty Event No Additional Props",
            properties: nil,
            options: withRudderTyperContext(options: options)
        )
    }

    /// Empty event schema with additionalProperties true
    /// - Parameters:
    ///   - properties: The properties to include with this event
    ///   - options: Optional RudderOption for additional event configuration
    public func trackEmptyEventWithAdditionalProps(properties: TrackEmptyEventWithAdditionalPropsProperties? = nil,
        options: RudderOption? = nil
    ) {
        analytics.track(
            name: "Empty Event With Additional Props",
            properties: properties,
            options: withRudderTyperContext(options: options)
        )
    }

    /// Example event to demonstrate variants
    /// - Parameters:
    ///   - properties: The properties to include with this event
    ///   - options: Optional RudderOption for additional event configuration
    public func trackEventWithVariants(properties: TrackEventWithVariantsProperties,
        options: RudderOption? = nil
    ) {
        analytics.track(
            name: "Event With Variants",
            properties: properties.toProperties(),
            options: withRudderTyperContext(options: options)
        )
    }

    /// Triggered when user clicks on a "premium" product /* important */
    /// - Parameters:
    ///   - properties: The properties to include with this event
    ///   - options: Optional RudderOption for additional event configuration
    public func trackProductPremiumClicked(properties: TrackProductPremiumClickedProperties,
        options: RudderOption? = nil
    ) {
        analytics.track(
            name: "Product \"Premium\" Clicked",
            properties: properties.toProperties(),
            options: withRudderTyperContext(options: options)
        )
    }

    /// Triggered when a user signs up
    /// - Parameters:
    ///   - properties: The properties to include with this event
    ///   - options: Optional RudderOption for additional event configuration
    public func trackUserSignedUp(properties: TrackUserSignedUpProperties,
        options: RudderOption? = nil
    ) {
        analytics.track(
            name: "User Signed Up",
            properties: properties.toProperties(),
            options: withRudderTyperContext(options: options)
        )
    }

    /// Event with camel case name
    /// - Parameters:
    ///   - properties: The properties to include with this event
    ///   - options: Optional RudderOption for additional event configuration
    public func trackEventWithNameCamelCase1(properties: TrackEventWithNameCamelCaseProperties1,
        options: RudderOption? = nil
    ) {
        analytics.track(
            name: "eventWithNameCamelCase",
            properties: properties.toProperties(),
            options: withRudderTyperContext(options: options)
        )
    }

    // MARK: - Private Helpers

    private func withRudderTyperContext(options: RudderOption?) -> RudderOption {
        let rudderTyperContext: [String: Any] = [
            "ruddertyper": [
                "language": "swift",
                "rudderTyperVersion": "1.0.0",
                "sdk": "rudder-sdk-swift",
                "trackingPlanId": "plan_12345",
                "trackingPlanVersion": 13,
            ] as [String: Any]
        ]

        if let options = options {
            let mergedContext = (options.customContext ?? [:]).merging(rudderTyperContext) { _, new in new }
            return RudderOption(
                integrations: options.integrations,
                customContext: mergedContext,
                externalIds: options.externalIds
            )
        } else {
            return RudderOption(customContext: rudderTyperContext)
        }
    }
}
