/**
 * RudderTyper.ts
 * This file was automatically generated by Rudder CLI 1.0.0.
 * Do not modify manually.
 */

import type {
    ApiOptions,
    RudderAnalytics,
    ApiCallback,
    ApiObject as SDKApiObject,
} from "@rudderstack/analytics-js";

// ===== Custom Types =====

/** Whether user is active */
export type CustomTypeActive = boolean;


// ===== Event Types =====

/** Triggered when a user signs up */
export interface UserSignedUp {
    /** User active status */
    active: CustomTypeActive;
}


// ===== RudderTyper =====

/**
 * Type-safe wrappers for RudderStack tracking based on your Tracking Plan.
 *
 * Tracking Plan: Empty Identity Plan (https://app.rudderstack.com/trackingPlans/plan_empty_identity)
 * - ID: plan_empty_identity
 * - Version: 1
 *
 * The constructor takes a resolver function that returns the current
 * RudderAnalytics instance. It is re-invoked on every call, so a lazily-loaded
 * SDK is always resolved fresh rather than captured once at construction.
 *
 * @example
 * ```ts
 * import { RudderAnalytics } from "@rudderstack/analytics-js";
 * import { RudderTyper } from "./RudderTyper";
 *
 * const analytics = new RudderAnalytics();
 * analytics.load("YOUR_WRITE_KEY", "YOUR_DATA_PLANE_URL");
 * const rudderTyper = new RudderTyper(() => analytics);
 * ```
 *
 * In a browser app that loads the SDK asynchronously, the standard RudderStack
 * snippet swaps `window.rudderanalytics` from the buffering preloader to the real
 * SDK once it loads. Because the resolver re-resolves on every call, events are
 * always sent through the current SDK — an eagerly captured instance would pin the
 * preloader and silently drop events fired after the SDK loads:
 *
 * ```ts
 * const rudderTyper = new RudderTyper(() => window.rudderanalytics);
 * ```
 */
export class RudderTyper {
    private readonly resolveAnalytics: () => RudderAnalytics;

    /**
     * @param resolveAnalytics - a function that returns the current RudderAnalytics
     * instance. Re-invoked on every call so a lazily-loaded SDK is resolved fresh
     * rather than captured once at construction.
     */
    constructor(resolveAnalytics: () => RudderAnalytics) {
        this.resolveAnalytics = resolveAnalytics;
    }

    private get analytics(): RudderAnalytics {
        return this.resolveAnalytics();
    }

    public group(
        groupId: string,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void;
    /**
     * Group association event
     */
    public group(
        groupId: string,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void {
        this.analytics.group(
            groupId,
            {},
            this.withRudderTyperContext(options),
            callback,
        );
    }

    public identify(
        userId: string,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void;
    /**
     * User identification event
     */
    public identify(
        userId: string,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void {
        this.analytics.identify(
            userId,
            {},
            this.withRudderTyperContext(options),
            callback,
        );
    }

    /**
     * Triggered when a user signs up
     *
     * @param props - The properties to include with this event
     * @param options - Optional ApiOptions for additional event configuration
     * @param callback - Optional callback fired after the call is dispatched
     */
    public trackUserSignedUp(
        props: UserSignedUp,
        options?: ApiOptions,
        callback?: ApiCallback,
    ): void {
        this.analytics.track(
            "User Signed Up",
            props as unknown as SDKApiObject,
            this.withRudderTyperContext(options),
            callback,
        );
    }

    private withRudderTyperContext(options?: ApiOptions): ApiOptions {
        const rudderTyperContext: SDKApiObject = {
            ruddertyper: {
                "platform": "typescript",
                "rudderCLIVersion": "1.0.0",
                "trackingPlanId": "plan_empty_identity",
                "trackingPlanVersion": 1,
            },
        };
        return {
            ...(options ?? {}),
            context: {
                ...((options?.context ?? {}) as SDKApiObject),
                ...rudderTyperContext,
            },
        };
    }
}
