package renderer

import (
	"encoding/json"
	"fmt"
	"io"
	"slices"

	"github.com/rudderlabs/rudder-iac/cli/internal/validation"
	"github.com/rudderlabs/rudder-iac/cli/internal/validation/rules"
)

// JSONRenderer emits diagnostics as a single JSON document for machine
// consumers — CI gates, editors, and coding agents that run validate, read the
// failures, and correct the specs themselves.
//
// One load renders one document. A run that validated clean emits an empty
// diagnostics array. A run that stopped on an error with no diagnostics of its
// own (see FailureRenderer) emits an error diagnostic with ruleId
// project/load-failed, so an empty array always means "validated clean".
type JSONRenderer struct {
	w io.Writer
}

func NewJSONRenderer(w io.Writer) Renderer {
	return &JSONRenderer{w: w}
}

// jsonDiagnostic is the wire shape, kept separate from validation.Diagnostic so
// the internal type stays free to change without breaking consumers parsing this
// output. Examples are deliberately omitted because they would dwarf the
// diagnostics. Rule documentation is generated by `make gen-rule-docs` and
// keyed by ruleId. The ruleIds project/spec-syntax-parse-valid,
// project/var-substitution and project/load-failed come from the project
// loader, not a registered rule, so they have no entry there.
type jsonDiagnostic struct {
	RuleID   string `json:"ruleId"`
	Severity string `json:"severity"`
	Message  string `json:"message"`
	File     string `json:"file"`
	Line     int    `json:"line"`
	Column   int    `json:"column"`
}

type jsonSummary struct {
	Errors   int `json:"errors"`
	Warnings int `json:"warnings"`
}

type jsonOutput struct {
	Diagnostics []jsonDiagnostic `json:"diagnostics"`
	Summary     jsonSummary      `json:"summary"`
}

// RenderFailure implements FailureRenderer.
func (r *JSONRenderer) RenderFailure(diagnostics validation.Diagnostics, cause error) error {
	return r.Render(append(slices.Clone(diagnostics), validation.Diagnostic{
		RuleID:   LoadFailureRuleID,
		Severity: rules.Error,
		Message:  cause.Error(),
	}))
}

func (r *JSONRenderer) Render(diagnostics validation.Diagnostics) error {
	out := jsonOutput{
		Diagnostics: make([]jsonDiagnostic, 0, len(diagnostics)),
		Summary: jsonSummary{
			Errors:   len(diagnostics.Errors()),
			Warnings: len(diagnostics.Warnings()),
		},
	}

	for _, d := range diagnostics {
		out.Diagnostics = append(out.Diagnostics, jsonDiagnostic{
			RuleID:   d.RuleID,
			Severity: d.Severity.String(),
			Message:  d.Message,
			File:     d.File,
			Line:     d.Position.Line,
			Column:   d.Position.Column,
		})
	}

	encoder := json.NewEncoder(r.w)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(out); err != nil {
		return fmt.Errorf("encoding diagnostics: %w", err)
	}

	return nil
}
