// Code generated by RudderTyper (Rudder CLI 1.0.0). DO NOT EDIT.

// Package ruddertyper provides type-safe analytics methods generated from the
// RudderStack tracking plan "Test Plan".
//
//   - Tracking plan: https://app.rudderstack.com/trackingPlans/plan_12345
//   - Tracking plan ID: plan_12345
//   - Tracking plan version: 13
//
// Quick start:
//
//	client := analytics.New(writeKey, dataPlaneURL)
//	defer client.Close()
//
//	rt := ruddertyper.New(client)
//	err := rt.TrackProductPremiumClicked(
//		ruddertyper.Identity{UserID: "user-123"},
//		ruddertyper.TrackProductPremiumClickedProperties{ /* ... */ },
//	)
package ruddertyper

import (
	"encoding/json"
	"errors"
	"maps"
	"time"

	analytics "github.com/rudderlabs/analytics-go/v4"
)

// --- Client ---

// RudderTyperAnalytics sends the events of the tracking plan "Test Plan"
// through a RudderStack Go SDK client. It holds no mutable state, so one
// value can be shared by many goroutines.
type RudderTyperAnalytics struct {
	client analytics.Client
}

// New returns a RudderTyperAnalytics that sends events through client.
// The caller keeps ownership of client and must Close it on shutdown.
func New(client analytics.Client) *RudderTyperAnalytics {
	if client == nil {
		panic("ruddertyper: New called with a nil analytics.Client")
	}
	return &RudderTyperAnalytics{client: client}
}

// Identity identifies who performed an event. Set UserID, AnonymousID or
// both; the SDK rejects a call that sets neither. When AnonymousID is empty,
// the SDK generates a random one for track, page, screen and group (not
// identify) calls.
type Identity struct {
	UserID      string
	AnonymousID string
}

// Errors returned by generated methods, in addition to the SDK's own. Match
// them with errors.Is.
var (
	// ErrNilPayload reports a nil or typed-nil payload that the tracking
	// plan requires.
	ErrNilPayload = errors.New("ruddertyper: payload is nil")
	// ErrInvalidValue reports a value that cannot be sent as the tracking
	// plan requires, such as an unset union or an unset required variant,
	// or that JSON cannot carry, such as NaN or a value that contains itself.
	ErrInvalidValue = errors.New("ruddertyper: invalid value")
	// ErrCategoryConflict reports a WithCategory value that the event's
	// tracking plan rule does not accept.
	ErrCategoryConflict = errors.New("ruddertyper: category conflicts with the tracking plan")
)

// Option customizes a single call. Options apply in order, so a later option
// overrides an earlier one of the same kind.
type Option func(*callOptions)

type callOptions struct {
	context      *analytics.Context
	integrations analytics.Integrations
	timestamp    time.Time
	messageID    string
}

// WithAnalyticsContext sets the event context. RudderTyper adds its metadata
// under context.ruddertyper, replacing any "ruddertyper" key in ctx.Extra.
func WithAnalyticsContext(ctx analytics.Context) Option {
	return func(o *callOptions) { o.context = &ctx }
}

// WithIntegrations selects the destinations the event is sent to.
func WithIntegrations(integrations analytics.Integrations) Option {
	return func(o *callOptions) { o.integrations = integrations }
}

// WithTimestamp sets when the event happened (originalTimestamp). The SDK
// uses the current time when it is not set.
func WithTimestamp(t time.Time) Option {
	return func(o *callOptions) { o.timestamp = t }
}

// WithMessageID sets the message ID. The SDK generates one when it is not set.
func WithMessageID(id string) Option {
	return func(o *callOptions) { o.messageID = id }
}

// --- Value helpers ---

// Ptr returns a pointer to v. Use it to set optional fields.
func Ptr[T any](v T) *T { return &v }

// --- Property types ---

// PropertyArrayOfAny represents the property "array_of_any".
//
// An array that can contain any type of items
type PropertyArrayOfAny = []any

// PropertyMixedUnicode represents the property "mixed_unicode".
//
// Property with mixed unicode: café, naïve, 日本語
type PropertyMixedUnicode = string

// PropertyObjectProperty represents the property "object_property".
//
// An object field with no defined structure
type PropertyObjectProperty = map[string]any

// PropertyPropertyOfAny represents the property "property_of_any".
//
// A field that can contain any type of value
type PropertyPropertyOfAny = any

// PropertySpecialField represents the property "special_field".
//
// Field with special chars: "quotes", backslash\path, and /* comment */
type PropertySpecialField = string

// PropertyUntypedArray represents the property "untyped_array".
//
// An array with no explicit item type (treated as any)
type PropertyUntypedArray = []any

// PropertyUntypedField represents the property "untyped_field".
//
// A field with no explicit type (treated as any)
type PropertyUntypedField = any

// Property用户名 represents the property "用户名".
//
// Username in Chinese characters
type Property用户名 = string

// --- Event payloads ---

// TrackVariableStringProperties holds the properties of "$Variable$String".
type TrackVariableStringProperties struct{}

func (v TrackVariableStringProperties) toMap() map[string]any {
	m := map[string]any{}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackVariableStringProperties) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackVariableStringProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// TrackEventWithNameCamelCaseProperties holds the properties of "$eventWithNameCamelCase$!".
type TrackEventWithNameCamelCaseProperties struct{}

func (v TrackEventWithNameCamelCaseProperties) toMap() map[string]any {
	m := map[string]any{}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackEventWithNameCamelCaseProperties) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEventWithNameCamelCaseProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// TrackEmptyEventWithAdditionalPropsProperties holds the properties of "Empty Event With Additional Props". The tracking plan declares no properties and allows any.
type TrackEmptyEventWithAdditionalPropsProperties = map[string]any

// TrackEventWithVariantsProperties holds the properties of "Event With Variants".
type TrackEventWithVariantsProperties struct{}

func (v TrackEventWithVariantsProperties) toMap() map[string]any {
	m := map[string]any{}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackEventWithVariantsProperties) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEventWithVariantsProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// TrackProductPremiumClickedProperties holds the properties of "Product \"Premium\" Clicked".
type TrackProductPremiumClickedProperties struct {
	SpecialField PropertySpecialField // required
}

func (v TrackProductPremiumClickedProperties) toMap() map[string]any {
	m := map[string]any{
		"special_field": v.SpecialField,
	}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackProductPremiumClickedProperties) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackProductPremiumClickedProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// TrackUserSignedUpProperties holds the properties of "User Signed Up".
type TrackUserSignedUpProperties struct {
	ArrayOfAny     PropertyArrayOfAny     // optional
	MixedUnicode   *PropertyMixedUnicode  // optional
	ObjectProperty PropertyObjectProperty // optional
	PropertyOfAny  PropertyPropertyOfAny  // optional
	UntypedArray   PropertyUntypedArray   // optional
	UntypedField   PropertyUntypedField   // optional
	X用户名           *Property用户名           // optional
}

func (v TrackUserSignedUpProperties) toMap() map[string]any {
	m := map[string]any{}
	if v.ArrayOfAny != nil {
		m["array_of_any"] = v.ArrayOfAny
	}
	if v.MixedUnicode != nil {
		m["mixed_unicode"] = *v.MixedUnicode
	}
	if v.ObjectProperty != nil {
		m["object_property"] = v.ObjectProperty
	}
	if v.PropertyOfAny != nil {
		m["property_of_any"] = v.PropertyOfAny
	}
	if v.UntypedArray != nil {
		m["untyped_array"] = v.UntypedArray
	}
	if v.UntypedField != nil {
		m["untyped_field"] = v.UntypedField
	}
	if v.X用户名 != nil {
		m["用户名"] = *v.X用户名
	}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackUserSignedUpProperties) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackUserSignedUpProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// TrackEventWithNameCamelCaseProperties1 holds the properties of "eventWithNameCamelCase".
type TrackEventWithNameCamelCaseProperties1 struct{}

func (v TrackEventWithNameCamelCaseProperties1) toMap() map[string]any {
	m := map[string]any{}
	return m
}

// ToProperties returns the properties as sent on the wire.
func (v TrackEventWithNameCamelCaseProperties1) ToProperties() (analytics.Properties, error) {
	return v.toMap(), nil
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEventWithNameCamelCaseProperties1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.toMap())
}

// --- Events ---

// TrackVariableString sends the track event "$Variable$String".
//
// Event with dollar signs to test string interpolation escaping
func (r *RudderTyperAnalytics) TrackVariableString(identity Identity, props TrackVariableStringProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "$Variable$String", p, opts)
}

// TrackEventWithNameCamelCase sends the track event "$eventWithNameCamelCase$!".
//
// Event with special characters that collide after sanitization
func (r *RudderTyperAnalytics) TrackEventWithNameCamelCase(identity Identity, props TrackEventWithNameCamelCaseProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "$eventWithNameCamelCase$!", p, opts)
}

// TrackEmptyEventNoAdditionalProps sends the track event "Empty Event No Additional Props", which has no properties.
//
// Empty event schema with additionalProperties false
func (r *RudderTyperAnalytics) TrackEmptyEventNoAdditionalProps(identity Identity, opts ...Option) error {
	return r.track(identity, "Empty Event No Additional Props", nil, opts)
}

// TrackEmptyEventWithAdditionalProps sends the track event "Empty Event With Additional Props". props may be nil.
//
// Empty event schema with additionalProperties true
func (r *RudderTyperAnalytics) TrackEmptyEventWithAdditionalProps(identity Identity, props TrackEmptyEventWithAdditionalPropsProperties, opts ...Option) error {
	return r.track(identity, "Empty Event With Additional Props", props, opts)
}

// TrackEventWithVariants sends the track event "Event With Variants".
//
// Example event to demonstrate variants
func (r *RudderTyperAnalytics) TrackEventWithVariants(identity Identity, props TrackEventWithVariantsProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Event With Variants", p, opts)
}

// TrackProductPremiumClicked sends the track event "Product \"Premium\" Clicked".
//
// Triggered when user clicks on a "premium" product /* important */
func (r *RudderTyperAnalytics) TrackProductPremiumClicked(identity Identity, props TrackProductPremiumClickedProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Product \"Premium\" Clicked", p, opts)
}

// TrackUserSignedUp sends the track event "User Signed Up".
//
// Triggered when a user signs up
func (r *RudderTyperAnalytics) TrackUserSignedUp(identity Identity, props TrackUserSignedUpProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "User Signed Up", p, opts)
}

// TrackEventWithNameCamelCase1 sends the track event "eventWithNameCamelCase".
//
// Event with camel case name
func (r *RudderTyperAnalytics) TrackEventWithNameCamelCase1(identity Identity, props TrackEventWithNameCamelCaseProperties1, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "eventWithNameCamelCase", p, opts)
}

// --- Internals ---

func (r *RudderTyperAnalytics) track(identity Identity, event string, properties analytics.Properties, opts []Option) error {
	o := applyOptions(opts)
	return r.client.Enqueue(analytics.Track{
		UserId:            identity.UserID,
		AnonymousId:       identity.AnonymousID,
		Event:             event,
		Properties:        properties,
		Context:           o.analyticsContext(),
		Integrations:      o.integrations,
		OriginalTimestamp: o.timestamp,
		MessageId:         o.messageID,
	})
}

// rudderTyperContext returns the metadata sent as context.ruddertyper. It
// builds a new map on every call because Config.Callback receives the
// message and could otherwise modify a shared one.
func rudderTyperContext() map[string]any {
	return map[string]any{
		"platform":            "go",
		"rudderCLIVersion":    "1.0.0",
		"trackingPlanId":      "plan_12345",
		"trackingPlanVersion": 13,
	}
}

// applyOptions applies opts in order, skipping nil ones.
func applyOptions(opts []Option) callOptions {
	var o callOptions
	for _, opt := range opts {
		if opt != nil {
			opt(&o)
		}
	}
	return o
}

// analyticsContext builds a fresh context for the call, because the SDK
// writes into the context it is given.
func (o callOptions) analyticsContext() *analytics.Context {
	var ctx analytics.Context
	if o.context != nil {
		ctx = *o.context
	}
	extra := make(map[string]any, len(ctx.Extra)+1)
	maps.Copy(extra, ctx.Extra)
	extra["ruddertyper"] = rudderTyperContext()
	ctx.Extra = extra
	return &ctx
}
