// Code generated by RudderTyper (Rudder CLI 1.0.0). DO NOT EDIT.

// Package ruddertyper provides type-safe analytics methods generated from the
// RudderStack tracking plan "Test Plan".
//
//   - Tracking plan: https://app.rudderstack.com/trackingPlans/plan_12345
//   - Tracking plan ID: plan_12345
//   - Tracking plan version: 13
//
// Quick start:
//
//	client := analytics.New(writeKey, dataPlaneURL)
//	defer client.Close()
//
//	rt := ruddertyper.New(client)
//	err := rt.TrackVariableString(
//		ruddertyper.Identity{UserID: "user-123"},
//		ruddertyper.TrackVariableStringProperties{ /* ... */ },
//	)
package ruddertyper

import (
	"bytes"
	"encoding"
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"math"
	"reflect"
	"slices"
	"time"

	analytics "github.com/rudderlabs/analytics-go/v4"
)

// --- Client ---

// RudderTyperAnalytics sends the events of the tracking plan "Test Plan"
// through a RudderStack Go SDK client. It holds no mutable state, so one
// value can be shared by many goroutines.
type RudderTyperAnalytics struct {
	client analytics.Client
}

// New returns a RudderTyperAnalytics that sends events through client.
// The caller keeps ownership of client and must Close it on shutdown.
func New(client analytics.Client) *RudderTyperAnalytics {
	if client == nil {
		panic("ruddertyper: New called with a nil analytics.Client")
	}
	return &RudderTyperAnalytics{client: client}
}

// Identity identifies who performed an event. Set UserID, AnonymousID or
// both; the SDK rejects a call that sets neither. When AnonymousID is empty,
// the SDK generates a random one for track, page, screen and group (not
// identify) calls.
type Identity struct {
	UserID      string
	AnonymousID string
}

// Errors returned by generated methods, in addition to the SDK's own. Match
// them with errors.Is.
var (
	// ErrNilPayload reports a nil or typed-nil payload that the tracking
	// plan requires.
	ErrNilPayload = errors.New("ruddertyper: payload is nil")
	// ErrInvalidValue reports a value that cannot be sent as the tracking
	// plan requires, such as an unset union or an unset required variant,
	// or that JSON cannot carry, such as NaN or a value that contains itself.
	ErrInvalidValue = errors.New("ruddertyper: invalid value")
	// ErrCategoryConflict reports a WithCategory value that the event's
	// tracking plan rule does not accept.
	ErrCategoryConflict = errors.New("ruddertyper: category conflicts with the tracking plan")
)

// Option customizes a single call. Options apply in order, so a later option
// overrides an earlier one of the same kind.
type Option func(*callOptions)

type callOptions struct {
	context      *analytics.Context
	integrations analytics.Integrations
	timestamp    time.Time
	messageID    string
}

// WithAnalyticsContext sets the event context. Everything reachable from ctx
// is copied when the event method is called, so ctx can be reused or changed
// afterwards. RudderTyper adds its metadata under context.ruddertyper,
// replacing any "ruddertyper" key in ctx.Extra.
func WithAnalyticsContext(ctx analytics.Context) Option {
	return func(o *callOptions) { o.context = &ctx }
}

// WithIntegrations selects the destinations the event is sent to. The map is
// copied when the event method is called.
func WithIntegrations(integrations analytics.Integrations) Option {
	return func(o *callOptions) { o.integrations = integrations }
}

// WithTimestamp sets when the event happened (originalTimestamp). The SDK
// uses the current time when it is not set.
func WithTimestamp(t time.Time) Option {
	return func(o *callOptions) { o.timestamp = t }
}

// WithMessageID sets the message ID. The SDK generates one when it is not set.
func WithMessageID(id string) Option {
	return func(o *callOptions) { o.messageID = id }
}

// --- Value helpers ---

// Ptr returns a pointer to v. Use it to set optional fields.
func Ptr[T any](v T) *T { return &v }

// --- Property types ---

// PropertyArrayOfAny represents the property "array_of_any".
//
// An array that can contain any type of items
type PropertyArrayOfAny = []any

// PropertyMixedUnicode represents the property "mixed_unicode".
//
// Property with mixed unicode: café, naïve, 日本語
type PropertyMixedUnicode = string

// PropertyObjectProperty represents the property "object_property".
//
// An object field with no defined structure
type PropertyObjectProperty = map[string]any

// PropertyPropertyOfAny represents the property "property_of_any".
//
// A field that can contain any type of value
type PropertyPropertyOfAny = any

// PropertySpecialField represents the property "special_field".
//
// Field with special chars: "quotes", backslash\path, and /* comment */
type PropertySpecialField = string

// PropertyUntypedArray represents the property "untyped_array".
//
// An array with no explicit item type (treated as any)
type PropertyUntypedArray = []any

// PropertyUntypedField represents the property "untyped_field".
//
// A field with no explicit type (treated as any)
type PropertyUntypedField = any

// Property用户名 represents the property "用户名".
//
// Username in Chinese characters
type Property用户名 = string

// --- Event payloads ---

// TrackVariableStringProperties holds the properties of "$Variable$String".
type TrackVariableStringProperties struct{}

func (v TrackVariableStringProperties) toMap() map[string]any {
	m := map[string]any{}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackVariableStringProperties) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackVariableStringProperties) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// TrackEventWithNameCamelCaseProperties holds the properties of "$eventWithNameCamelCase$!".
type TrackEventWithNameCamelCaseProperties struct{}

func (v TrackEventWithNameCamelCaseProperties) toMap() map[string]any {
	m := map[string]any{}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackEventWithNameCamelCaseProperties) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEventWithNameCamelCaseProperties) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// TrackEmptyEventWithAdditionalPropsProperties holds the properties of "Empty Event With Additional Props". The tracking plan declares no properties and allows any.
type TrackEmptyEventWithAdditionalPropsProperties = map[string]any

// TrackEventWithVariantsProperties holds the properties of "Event With Variants".
type TrackEventWithVariantsProperties struct{}

func (v TrackEventWithVariantsProperties) toMap() map[string]any {
	m := map[string]any{}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackEventWithVariantsProperties) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEventWithVariantsProperties) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// TrackProductPremiumClickedProperties holds the properties of "Product \"Premium\" Clicked".
type TrackProductPremiumClickedProperties struct {
	SpecialField PropertySpecialField // required
}

func (v TrackProductPremiumClickedProperties) toMap() map[string]any {
	m := map[string]any{
		"special_field": v.SpecialField,
	}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackProductPremiumClickedProperties) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackProductPremiumClickedProperties) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// TrackUserSignedUpProperties holds the properties of "User Signed Up".
type TrackUserSignedUpProperties struct {
	ArrayOfAny     PropertyArrayOfAny     // optional
	MixedUnicode   *PropertyMixedUnicode  // optional
	ObjectProperty PropertyObjectProperty // optional
	PropertyOfAny  PropertyPropertyOfAny  // optional
	UntypedArray   PropertyUntypedArray   // optional
	UntypedField   PropertyUntypedField   // optional
	X用户名           *Property用户名           // optional
}

func (v TrackUserSignedUpProperties) toMap() map[string]any {
	m := map[string]any{}
	if v.ArrayOfAny != nil {
		m["array_of_any"] = v.ArrayOfAny
	}
	if v.MixedUnicode != nil {
		m["mixed_unicode"] = *v.MixedUnicode
	}
	if v.ObjectProperty != nil {
		m["object_property"] = v.ObjectProperty
	}
	if v.PropertyOfAny != nil {
		m["property_of_any"] = v.PropertyOfAny
	}
	if v.UntypedArray != nil {
		m["untyped_array"] = v.UntypedArray
	}
	if v.UntypedField != nil {
		m["untyped_field"] = v.UntypedField
	}
	if v.X用户名 != nil {
		m["用户名"] = *v.X用户名
	}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackUserSignedUpProperties) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackUserSignedUpProperties) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// TrackEventWithNameCamelCaseProperties1 holds the properties of "eventWithNameCamelCase".
type TrackEventWithNameCamelCaseProperties1 struct{}

func (v TrackEventWithNameCamelCaseProperties1) toMap() map[string]any {
	m := map[string]any{}
	return m
}

// ToProperties returns a deep copy of the properties as sent on the wire.
func (v TrackEventWithNameCamelCaseProperties1) ToProperties() (analytics.Properties, error) {
	return snapshot(v)
}

// MarshalJSON implements json.Marshaler using the tracking plan's keys.
func (v TrackEventWithNameCamelCaseProperties1) MarshalJSON() ([]byte, error) {
	return marshal(v)
}

// --- Events ---

// TrackVariableString sends the track event "$Variable$String".
//
// Event with dollar signs to test string interpolation escaping
func (r *RudderTyperAnalytics) TrackVariableString(identity Identity, props TrackVariableStringProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "$Variable$String", p, opts)
}

// TrackEventWithNameCamelCase sends the track event "$eventWithNameCamelCase$!".
//
// Event with special characters that collide after sanitization
func (r *RudderTyperAnalytics) TrackEventWithNameCamelCase(identity Identity, props TrackEventWithNameCamelCaseProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "$eventWithNameCamelCase$!", p, opts)
}

// TrackEmptyEventNoAdditionalProps sends the track event "Empty Event No Additional Props", which has no properties.
//
// Empty event schema with additionalProperties false
func (r *RudderTyperAnalytics) TrackEmptyEventNoAdditionalProps(identity Identity, opts ...Option) error {
	return r.track(identity, "Empty Event No Additional Props", nil, opts)
}

// TrackEmptyEventWithAdditionalProps sends the track event "Empty Event With Additional Props". props may be nil; it is copied, so it can be reused after the call.
//
// Empty event schema with additionalProperties true
func (r *RudderTyperAnalytics) TrackEmptyEventWithAdditionalProps(identity Identity, props TrackEmptyEventWithAdditionalPropsProperties, opts ...Option) error {
	p, err := snapshot(props)
	if err != nil {
		return err
	}
	return r.track(identity, "Empty Event With Additional Props", p, opts)
}

// TrackEventWithVariants sends the track event "Event With Variants".
//
// Example event to demonstrate variants
func (r *RudderTyperAnalytics) TrackEventWithVariants(identity Identity, props TrackEventWithVariantsProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Event With Variants", p, opts)
}

// TrackProductPremiumClicked sends the track event "Product \"Premium\" Clicked".
//
// Triggered when user clicks on a "premium" product /* important */
func (r *RudderTyperAnalytics) TrackProductPremiumClicked(identity Identity, props TrackProductPremiumClickedProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "Product \"Premium\" Clicked", p, opts)
}

// TrackUserSignedUp sends the track event "User Signed Up".
//
// Triggered when a user signs up
func (r *RudderTyperAnalytics) TrackUserSignedUp(identity Identity, props TrackUserSignedUpProperties, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "User Signed Up", p, opts)
}

// TrackEventWithNameCamelCase1 sends the track event "eventWithNameCamelCase".
//
// Event with camel case name
func (r *RudderTyperAnalytics) TrackEventWithNameCamelCase1(identity Identity, props TrackEventWithNameCamelCaseProperties1, opts ...Option) error {
	p, err := props.ToProperties()
	if err != nil {
		return err
	}
	return r.track(identity, "eventWithNameCamelCase", p, opts)
}

// --- Internals ---

func (r *RudderTyperAnalytics) track(identity Identity, event string, properties analytics.Properties, opts []Option) error {
	o, err := applyOptions(opts)
	if err != nil {
		return err
	}
	return r.client.Enqueue(analytics.Track{
		UserId:            identity.UserID,
		AnonymousId:       identity.AnonymousID,
		Event:             event,
		Properties:        properties,
		Context:           o.analyticsContext(nil),
		Integrations:      o.integrations,
		OriginalTimestamp: o.timestamp,
		MessageId:         o.messageID,
	})
}

// rudderTyperContext returns the metadata sent as context.ruddertyper. It
// builds a new map on every call because Config.Callback receives the
// message and could otherwise modify a shared one.
func rudderTyperContext() map[string]any {
	return map[string]any{
		"platform":            "go",
		"rudderCLIVersion":    "1.0.0",
		"trackingPlanId":      "plan_12345",
		"trackingPlanVersion": 13,
	}
}

// applyOptions applies opts and copies every caller-owned value they hold, so
// the SDK, which serializes later on another goroutine, never shares memory
// with the caller. The fields it does not copy are encoded once, so a value
// the SDK could not send is reported here rather than in Config.Callback.
func applyOptions(opts []Option) (callOptions, error) {
	var o callOptions
	for _, opt := range opts {
		if opt != nil {
			opt(&o)
		}
	}
	var err error
	if o.integrations, err = snapshot(o.integrations); err != nil {
		return o, fmt.Errorf("integrations: %w", err)
	}
	if _, err := o.timestamp.MarshalJSON(); err != nil {
		return o, fmt.Errorf("%w: timestamp: %w", ErrInvalidValue, err)
	}
	if o.context == nil {
		return o, nil
	}
	ctx := *o.context
	if ctx.Extra, err = snapshot(ctx.Extra); err != nil {
		return o, fmt.Errorf("context.Extra: %w", err)
	}
	if ctx.Traits, err = snapshot(ctx.Traits); err != nil {
		return o, fmt.Errorf("context.Traits: %w", err)
	}
	ctx.IP = slices.Clone(ctx.IP)
	fields := ctx
	fields.Extra, fields.Traits = nil, nil
	if _, err := json.Marshal(fields); err != nil {
		return o, fmt.Errorf("%w: context: %w", ErrInvalidValue, err)
	}
	o.context = &ctx
	return o, nil
}

// analyticsContext builds a fresh context for the call, because the SDK
// writes into the context it is given. contextTraits (from a context.traits
// identify rule) win over caller-supplied Context.Traits keys.
func (o callOptions) analyticsContext(contextTraits analytics.Traits) *analytics.Context {
	var ctx analytics.Context
	if o.context != nil {
		ctx = *o.context
	}
	extra := make(map[string]any, len(ctx.Extra)+1)
	maps.Copy(extra, ctx.Extra)
	extra["ruddertyper"] = rudderTyperContext()
	ctx.Extra = extra
	if len(contextTraits) > 0 {
		traits := make(analytics.Traits, len(ctx.Traits)+len(contextTraits))
		maps.Copy(traits, ctx.Traits)
		maps.Copy(traits, contextTraits)
		ctx.Traits = traits
	}
	return &ctx
}

// wireObject is implemented by every generated struct, and wireValuer by the
// other generated types with a wire form of their own: unions, mixed enums,
// Nullable and Null.
type (
	wireObject interface{ toMap() map[string]any }
	wireValuer interface{ wireValue() (any, error) }
)

// maxDepth bounds how deeply a value may nest. Real events stay far below it;
// a value that contains itself reaches it and fails instead of overflowing
// the stack.
const maxDepth = 1000

// snapshot converts v into what the SDK receives: new maps and slices holding
// strings, bools, numbers and nil. The SDK serializes later on another
// goroutine, so nothing the caller owns may reach it, and converting now
// reports a value that cannot be sent before Enqueue.
func snapshot(v any) (map[string]any, error) {
	w, err := wire(reflect.ValueOf(v), 0)
	if err != nil {
		return nil, err
	}
	m, _ := w.(map[string]any)
	return m, nil
}

// marshal is the MarshalJSON of every generated type, so json.Marshal and the
// event methods produce the same JSON.
func marshal(v any) ([]byte, error) {
	w, err := wire(reflect.ValueOf(v), 0)
	if err != nil {
		return nil, err
	}
	return json.Marshal(w)
}

// wire returns the JSON value of rv as new plain Go values. Nil slices and
// maps become [] and {}, so a Go zero value is never sent as null by
// accident; null comes only from nil pointers and interfaces, Null and an
// invalid Nullable.
func wire(rv reflect.Value, depth int) (any, error) {
	if depth > maxDepth {
		return nil, fmt.Errorf("%w: value nests more than %d levels deep or contains itself", ErrInvalidValue, maxDepth)
	}
	depth++
	if !rv.IsValid() {
		return nil, nil
	}
	if k := rv.Kind(); (k == reflect.Pointer || k == reflect.Interface) && isNil(rv.Interface()) {
		// toMap already omits or rejects nil variants in fields, so this is a
		// nil variant array item, which has no valid wire form.
		if k == reflect.Interface && rv.Type().Implements(reflect.TypeOf((*wireObject)(nil)).Elem()) {
			return nil, fmt.Errorf("%w: nil %s item", ErrInvalidValue, rv.Type())
		}
		return nil, nil
	}
	switch v := rv.Interface().(type) {
	case wireObject:
		return wire(reflect.ValueOf(v.toMap()), depth)
	case wireValuer:
		x, err := v.wireValue()
		if err != nil {
			return nil, err
		}
		return wire(reflect.ValueOf(x), depth)
	case json.Number, json.Marshaler, encoding.TextMarshaler:
		return encode(v)
	}
	// encoding/json also calls pointer-receiver marshalers on addressable
	// values, such as slice elements.
	if rv.CanAddr() {
		switch p := rv.Addr().Interface().(type) {
		case json.Marshaler, encoding.TextMarshaler:
			return encode(p)
		}
	}
	switch rv.Kind() {
	case reflect.Interface, reflect.Pointer:
		return wire(rv.Elem(), depth)
	case reflect.Map:
		if rv.Type().Key().Kind() != reflect.String {
			return foreign(rv, depth)
		}
		m := make(map[string]any, rv.Len())
		for it := rv.MapRange(); it.Next(); {
			x, err := wire(it.Value(), depth)
			if err != nil {
				return nil, err
			}
			m[it.Key().String()] = x
		}
		return m, nil
	case reflect.Slice, reflect.Array:
		if rv.Kind() == reflect.Slice && rv.Type().Elem().Kind() == reflect.Uint8 {
			return encode(rv.Interface()) // base64, as encoding/json sends []byte
		}
		s := make([]any, rv.Len())
		for i := range s {
			x, err := wire(rv.Index(i), depth)
			if err != nil {
				return nil, err
			}
			s[i] = x
		}
		return s, nil
	case reflect.Struct:
		return foreign(rv, depth)
	case reflect.String:
		return rv.String(), nil
	case reflect.Bool:
		return rv.Bool(), nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return rv.Int(), nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return rv.Uint(), nil
	case reflect.Float32, reflect.Float64:
		f := rv.Float()
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return nil, fmt.Errorf("%w: %v is not a JSON number", ErrInvalidValue, f)
		}
		if rv.Kind() == reflect.Float32 {
			return float32(f), nil
		}
		return f, nil
	}
	// Channels, functions and complex numbers: encoding/json names the error.
	return encode(rv.Interface())
}

// foreign converts a caller-defined struct, or a map with non-string keys,
// with encoding/json, whose rules for them this file does not repeat. The
// values inside are walked first and the result dropped: a generated value
// in there is encoded by its own MarshalJSON, which starts a new walk, so
// only this walk can stop a cycle that runs through it.
func foreign(rv reflect.Value, depth int) (any, error) {
	if rv.Kind() == reflect.Map {
		for it := rv.MapRange(); it.Next(); {
			if _, err := wire(it.Value(), depth); err != nil {
				return nil, err
			}
		}
		return encode(rv.Interface())
	}
	// VisibleFields includes the fields encoding/json promotes from embedded
	// structs; those behind a nil embedded pointer have no value to walk.
	for _, f := range reflect.VisibleFields(rv.Type()) {
		fv, err := rv.FieldByIndexErr(f.Index)
		if err != nil || !f.IsExported() || f.Tag.Get("json") == "-" {
			continue
		}
		if _, err := wire(fv, depth); err != nil {
			return nil, err
		}
	}
	// encoding/json calls pointer-receiver marshalers only on addressable values.
	if rv.CanAddr() {
		rv = rv.Addr()
	}
	return encode(rv.Interface())
}

// encode converts v through encoding/json, for values whose JSON form only
// encoding/json defines. Numbers inside them come back as json.Number.
func encode(v any) (any, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrInvalidValue, err)
	}
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.UseNumber()
	var x any
	if err := dec.Decode(&x); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrInvalidValue, err)
	}
	return x, nil
}

// isNil reports whether v is nil or a nil pointer stored in an interface.
func isNil(v any) bool {
	if v == nil {
		return true
	}
	rv := reflect.ValueOf(v)
	return rv.Kind() == reflect.Pointer && rv.IsNil()
}
