// This file was automatically generated by Rudder CLI 1.0.0.
// Do not modify manually.

package com.rudderstack.ruddertyper

import com.rudderstack.sdk.kotlin.core.Analytics
import com.rudderstack.sdk.kotlin.core.internals.models.RudderOption
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import kotlinx.serialization.json.encodeToJsonElement
import kotlinx.serialization.json.jsonObject

/** Whether user is active */
typealias CustomTypeActive = Boolean

/** User's age in years */
typealias CustomTypeAge = Double

/** Custom type for email validation */
typealias CustomTypeEmail = String

/** List of email addresses */
typealias CustomTypeEmailList = List<CustomTypeEmail>

/** Empty object that does not allow additional properties */
typealias CustomTypeEmptyObjectNoAdditionalProps = Unit

/** Empty object that allows additional properties */
typealias CustomTypeEmptyObjectWithAdditionalProps = JsonObject

/** Custom type representing a null value */
typealias CustomTypeNullType = JsonNull

/** List of user profiles */
typealias CustomTypeProfileList = List<CustomTypeUserProfile>

/** User active status */
typealias PropertyActive = CustomTypeActive

/** User's age */
typealias PropertyAge = CustomTypeAge

/** An array that can contain any type of items */
typealias PropertyArrayOfAny = List<JsonElement>

/** Array with items that can be string or null */
typealias PropertyArrayWithNullItems = List<ArrayItemArrayWithNullItems>

/** Array of user contacts */
typealias PropertyContacts = List<CustomTypeEmail>

/** example of object property */
typealias PropertyContext = JsonObject

/** Property using custom null type */
typealias PropertyCustomNullField = CustomTypeNullType

/** User's email address */
typealias PropertyEmail = CustomTypeEmail

/** User's email addresses */
typealias PropertyEmailList = CustomTypeEmailList

/** Property with empty object not allowing additional properties */
typealias PropertyEmptyObjectNoAdditionalProps = CustomTypeEmptyObjectNoAdditionalProps

/** Property with empty object allowing additional properties */
typealias PropertyEmptyObjectWithAdditionalProps = CustomTypeEmptyObjectWithAdditionalProps

/** Feature configuration information */
typealias PropertyFeatureConfig = CustomTypeFeatureConfig

/** User's first name */
typealias PropertyFirstName = String

/** IP address of the user */
typealias PropertyIpAddress = String

/** User's last name */
typealias PropertyLastName = String

/** Property with mixed unicode: café, naïve, 日本語 */
typealias PropertyMixedUnicode = String

/** An array with items that can be string or integer */
typealias PropertyMultiTypeArray = List<ArrayItemMultiTypeArray>

/** demonstrates multiple levels of nesting */
typealias PropertyNestedContext = JsonObject

/** Nested property with empty object allowing additional properties */
typealias PropertyNestedEmptyObject = JsonObject

/** Nested property with empty object not allowing additional properties */
typealias PropertyNestedEmptyObjectNoAdditionalProps = JsonObject

/** Property that is always null */
typealias PropertyNullField = JsonNull

/** An object field with no defined structure */
typealias PropertyObjectProperty = JsonObject

/** Page context information */
typealias PropertyPageContext = CustomTypePageContext

/** Additional page data */
typealias PropertyPageData = JsonObject

/** Type of page */
typealias PropertyPageType = String

/** Product identifier */
typealias PropertyProductId = String

/** User profile data */
typealias PropertyProfile = CustomTypeUserProfile

/** List of related user profiles */
typealias PropertyProfileList = CustomTypeProfileList

/** A field that can contain any type of value */
typealias PropertyPropertyOfAny = JsonElement

/** Search query */
typealias PropertyQuery = String

/** Field with special chars: "quotes", backslash\path, and /\* comment *\/ */
typealias PropertySpecialField = String

/** User account status */
typealias PropertyStatus = CustomTypeStatus

/** User tags as array of strings */
typealias PropertyTags = List<String>

/** Property using custom type with Unicode */
typealias PropertyUnicodeCustomType = CustomTypeТипыДанных

/** An array with no explicit item type (treated as any) */
typealias PropertyUntypedArray = List<JsonElement>

/** A field with no explicit type (treated as any) */
typealias PropertyUntypedField = JsonElement

/** User access information */
typealias PropertyUserAccess = CustomTypeUserAccess

/** Username in Chinese characters */
typealias Property用户名 = String

/** Empty event schema with additionalProperties true */
typealias TrackEmptyEventWithAdditionalPropsProperties = JsonObject

/** User status enum */
@Serializable(with = RudderCustomTypeStatusSerializer::class)
enum class CustomTypeStatus {
    PENDING,
    ACTIVE,
    SUSPENDED,
    DELETED
}

private object RudderCustomTypeStatusSerializer : KSerializer<CustomTypeStatus> {
    override val descriptor = buildClassSerialDescriptor("CustomTypeStatus")

    override fun serialize(encoder: Encoder, value: CustomTypeStatus) {
        val jsonValue = when (value) {
            CustomTypeStatus.PENDING -> JsonPrimitive("pending")
            CustomTypeStatus.ACTIVE -> JsonPrimitive("active")
            CustomTypeStatus.SUSPENDED -> JsonPrimitive("suspended")
            CustomTypeStatus.DELETED -> JsonPrimitive("deleted")
        }
        encoder.encodeSerializableValue(JsonPrimitive.serializer(), jsonValue)
    }

    override fun deserialize(decoder: Decoder): CustomTypeStatus {
        throw SerializationException("Deserialization not supported for CustomTypeStatus")
    }
}

/** Custom type with Cyrillic name */
@Serializable(with = RudderCustomTypeТипыДанныхSerializer::class)
enum class CustomTypeТипыДанных {
    АКТИВНЫЙ,
    НЕАКТИВНЫЙ,
    PENDING
}

private object RudderCustomTypeТипыДанныхSerializer : KSerializer<CustomTypeТипыДанных> {
    override val descriptor = buildClassSerialDescriptor("CustomTypeТипыДанных")

    override fun serialize(encoder: Encoder, value: CustomTypeТипыДанных) {
        val jsonValue = when (value) {
            CustomTypeТипыДанных.АКТИВНЫЙ -> JsonPrimitive("активный")
            CustomTypeТипыДанных.НЕАКТИВНЫЙ -> JsonPrimitive("неактивный")
            CustomTypeТипыДанных.PENDING -> JsonPrimitive("pending")
        }
        encoder.encodeSerializableValue(JsonPrimitive.serializer(), jsonValue)
    }

    override fun deserialize(decoder: Decoder): CustomTypeТипыДанных {
        throw SerializationException("Deserialization not supported for CustomTypeТипыДанных")
    }
}

/** Type of device */
@Serializable(with = RudderPropertyDeviceTypeSerializer::class)
enum class PropertyDeviceType {
    MOBILE,
    TABLET,
    DESKTOP,
    SMART_TV,
    IO_T_DEVICE
}

private object RudderPropertyDeviceTypeSerializer : KSerializer<PropertyDeviceType> {
    override val descriptor = buildClassSerialDescriptor("PropertyDeviceType")

    override fun serialize(encoder: Encoder, value: PropertyDeviceType) {
        val jsonValue = when (value) {
            PropertyDeviceType.MOBILE -> JsonPrimitive("mobile")
            PropertyDeviceType.TABLET -> JsonPrimitive("tablet")
            PropertyDeviceType.DESKTOP -> JsonPrimitive("desktop")
            PropertyDeviceType.SMART_TV -> JsonPrimitive("smartTV")
            PropertyDeviceType.IO_T_DEVICE -> JsonPrimitive("IoT-Device")
        }
        encoder.encodeSerializableValue(JsonPrimitive.serializer(), jsonValue)
    }

    override fun deserialize(decoder: Decoder): PropertyDeviceType {
        throw SerializationException("Deserialization not supported for PropertyDeviceType")
    }
}

/** Feature enabled flag */
@Serializable(with = RudderPropertyEnabledSerializer::class)
enum class PropertyEnabled {
    TRUE,
    FALSE
}

private object RudderPropertyEnabledSerializer : KSerializer<PropertyEnabled> {
    override val descriptor = buildClassSerialDescriptor("PropertyEnabled")

    override fun serialize(encoder: Encoder, value: PropertyEnabled) {
        val jsonValue = when (value) {
            PropertyEnabled.TRUE -> JsonPrimitive(true)
            PropertyEnabled.FALSE -> JsonPrimitive(false)
        }
        encoder.encodeSerializableValue(JsonPrimitive.serializer(), jsonValue)
    }

    override fun deserialize(decoder: Decoder): PropertyEnabled {
        throw SerializationException("Deserialization not supported for PropertyEnabled")
    }
}

/** Mixed type enum */
@Serializable(with = RudderPropertyMixedValueSerializer::class)
enum class PropertyMixedValue {
    ACTIVE,
    _1,
    TRUE,
    _2_5
}

private object RudderPropertyMixedValueSerializer : KSerializer<PropertyMixedValue> {
    override val descriptor = buildClassSerialDescriptor("PropertyMixedValue")

    override fun serialize(encoder: Encoder, value: PropertyMixedValue) {
        val jsonValue = when (value) {
            PropertyMixedValue.ACTIVE -> JsonPrimitive("active")
            PropertyMixedValue._1 -> JsonPrimitive(1)
            PropertyMixedValue.TRUE -> JsonPrimitive(true)
            PropertyMixedValue._2_5 -> JsonPrimitive(2.5)
        }
        encoder.encodeSerializableValue(JsonPrimitive.serializer(), jsonValue)
    }

    override fun deserialize(decoder: Decoder): PropertyMixedValue {
        throw SerializationException("Deserialization not supported for PropertyMixedValue")
    }
}

/** Priority level */
@Serializable(with = RudderPropertyPrioritySerializer::class)
enum class PropertyPriority {
    _1,
    _2,
    _3
}

private object RudderPropertyPrioritySerializer : KSerializer<PropertyPriority> {
    override val descriptor = buildClassSerialDescriptor("PropertyPriority")

    override fun serialize(encoder: Encoder, value: PropertyPriority) {
        val jsonValue = when (value) {
            PropertyPriority._1 -> JsonPrimitive(1)
            PropertyPriority._2 -> JsonPrimitive(2)
            PropertyPriority._3 -> JsonPrimitive(3)
        }
        encoder.encodeSerializableValue(JsonPrimitive.serializer(), jsonValue)
    }

    override fun deserialize(decoder: Decoder): PropertyPriority {
        throw SerializationException("Deserialization not supported for PropertyPriority")
    }
}

/** Rating value */
@Serializable(with = RudderPropertyRatingSerializer::class)
enum class PropertyRating {
    _1_5,
    _2_5,
    _3_5,
    _4_5,
    _5
}

private object RudderPropertyRatingSerializer : KSerializer<PropertyRating> {
    override val descriptor = buildClassSerialDescriptor("PropertyRating")

    override fun serialize(encoder: Encoder, value: PropertyRating) {
        val jsonValue = when (value) {
            PropertyRating._1_5 -> JsonPrimitive(1.5)
            PropertyRating._2_5 -> JsonPrimitive(2.5)
            PropertyRating._3_5 -> JsonPrimitive(3.5)
            PropertyRating._4_5 -> JsonPrimitive(4.5)
            PropertyRating._5 -> JsonPrimitive(5)
        }
        encoder.encodeSerializableValue(JsonPrimitive.serializer(), jsonValue)
    }

    override fun deserialize(decoder: Decoder): PropertyRating {
        throw SerializationException("Deserialization not supported for PropertyRating")
    }
}

/** HTTP status with special characters */
@Serializable(with = RudderPropertyStatusCodeSerializer::class)
enum class PropertyStatusCode {
    _200_OK,
    _404_NOT_FOUND,
    _500_INTERNAL_SERVER_ERROR
}

private object RudderPropertyStatusCodeSerializer : KSerializer<PropertyStatusCode> {
    override val descriptor = buildClassSerialDescriptor("PropertyStatusCode")

    override fun serialize(encoder: Encoder, value: PropertyStatusCode) {
        val jsonValue = when (value) {
            PropertyStatusCode._200_OK -> JsonPrimitive("200: OK")
            PropertyStatusCode._404_NOT_FOUND -> JsonPrimitive("404: Not Found")
            PropertyStatusCode._500_INTERNAL_SERVER_ERROR -> JsonPrimitive("500: Internal \"Server\" Error")
        }
        encoder.encodeSerializableValue(JsonPrimitive.serializer(), jsonValue)
    }

    override fun deserialize(decoder: Decoder): PropertyStatusCode {
        throw SerializationException("Deserialization not supported for PropertyStatusCode")
    }
}

/** Field demonstrating various Unicode characters in enum values */
@Serializable(with = RudderPropertyUnicodeEnumFieldSerializer::class)
enum class PropertyUnicodeEnumField {
    _1,
    _2,
    АКТИВНЫЙ,
    已完成,
    ΕΝΕΡΓΌΣ,
    CAFÉ,
    ___1
}

private object RudderPropertyUnicodeEnumFieldSerializer : KSerializer<PropertyUnicodeEnumField> {
    override val descriptor = buildClassSerialDescriptor("PropertyUnicodeEnumField")

    override fun serialize(encoder: Encoder, value: PropertyUnicodeEnumField) {
        val jsonValue = when (value) {
            PropertyUnicodeEnumField._1 -> JsonPrimitive("🎯")
            PropertyUnicodeEnumField._2 -> JsonPrimitive("✅")
            PropertyUnicodeEnumField.АКТИВНЫЙ -> JsonPrimitive("активный")
            PropertyUnicodeEnumField.已完成 -> JsonPrimitive("已完成")
            PropertyUnicodeEnumField.ΕΝΕΡΓΌΣ -> JsonPrimitive("ενεργός")
            PropertyUnicodeEnumField.CAFÉ -> JsonPrimitive("café")
            PropertyUnicodeEnumField.___1 -> JsonPrimitive("!!!")
        }
        encoder.encodeSerializableValue(JsonPrimitive.serializer(), jsonValue)
    }

    override fun deserialize(decoder: Decoder): PropertyUnicodeEnumField {
        throw SerializationException("Deserialization not supported for PropertyUnicodeEnumField")
    }
}

interface SealedClassWithJson {
    val _jsonElement: JsonElement
}

open class SealedClassJsonSerializer<T : SealedClassWithJson> : KSerializer<T> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("SealedClass")

    override fun serialize(encoder: Encoder, value: T) {
        val jsonEncoder = encoder as? JsonEncoder
            ?: throw SerializationException("This serializer only works with JSON")
        jsonEncoder.encodeJsonElement(value._jsonElement)
    }

    override fun deserialize(decoder: Decoder): T {
        throw NotImplementedError("Deserialization is not supported")
    }
}

/** Feature configuration with variants based on multi-type flag */
@Serializable(with = RudderCustomTypeFeatureConfigSerializer::class)
sealed class CustomTypeFeatureConfig : SealedClassWithJson {
    /** Feature flag that can be boolean or string */
    @SerialName("feature_flag")
    abstract val featureFlag: PropertyFeatureFlag
    abstract override val _jsonElement: JsonElement

    /** Feature enabled (boolean true) */
    @Serializable
    data class CaseTrue(
        /** User's age */
        @SerialName("age")
        val age: PropertyAge? = null
    ) : CustomTypeFeatureConfig() {
        /** Feature flag that can be boolean or string */
        @SerialName("feature_flag")
        override val featureFlag: PropertyFeatureFlag = PropertyFeatureFlag.BooleanValue(true)
        override val _jsonElement: JsonElement = buildJsonObject {
            age?.let { put("age", Json.encodeToJsonElement(it)) }
            put("feature_flag", Json.encodeToJsonElement(featureFlag))
        }
    }

    /** Feature disabled (boolean false) */
    @Serializable
    data class CaseFalse(
        /** User's first name */
        @SerialName("first_name")
        val firstName: PropertyFirstName? = null
    ) : CustomTypeFeatureConfig() {
        /** Feature flag that can be boolean or string */
        @SerialName("feature_flag")
        override val featureFlag: PropertyFeatureFlag = PropertyFeatureFlag.BooleanValue(false)
        override val _jsonElement: JsonElement = buildJsonObject {
            firstName?.let { put("first_name", Json.encodeToJsonElement(it)) }
            put("feature_flag", Json.encodeToJsonElement(featureFlag))
        }
    }

    /** Feature in beta (string 'beta') */
    @Serializable
    data class CaseBeta(
        /** User tags as array of strings */
        @SerialName("tags")
        val tags: PropertyTags? = null
    ) : CustomTypeFeatureConfig() {
        /** Feature flag that can be boolean or string */
        @SerialName("feature_flag")
        override val featureFlag: PropertyFeatureFlag = PropertyFeatureFlag.StringValue("beta")
        override val _jsonElement: JsonElement = buildJsonObject {
            tags?.let { put("tags", Json.encodeToJsonElement(it)) }
            put("feature_flag", Json.encodeToJsonElement(featureFlag))
        }
    }

    /** Default case */
    @Serializable
    data class Default(
        /** Feature flag that can be boolean or string */
        @SerialName("feature_flag")
        override val featureFlag: PropertyFeatureFlag
    ) : CustomTypeFeatureConfig() {
        override val _jsonElement: JsonElement = buildJsonObject {
            put("feature_flag", Json.encodeToJsonElement(featureFlag))
        }
    }
}

private object RudderCustomTypeFeatureConfigSerializer : SealedClassJsonSerializer<CustomTypeFeatureConfig>()

/** Page context with variants based on page type */
@Serializable(with = RudderCustomTypePageContextSerializer::class)
sealed class CustomTypePageContext : SealedClassWithJson {
    /** Type of page */
    @SerialName("page_type")
    abstract val pageType: PropertyPageType
    abstract override val _jsonElement: JsonElement

    /** Search page variant */
    @Serializable
    data class CaseSearch(
        /** Search query */
        @SerialName("query")
        val query: PropertyQuery
    ) : CustomTypePageContext() {
        /** Type of page */
        @SerialName("page_type")
        override val pageType: PropertyPageType = "search"
        override val _jsonElement: JsonElement = buildJsonObject {
            put("query", Json.encodeToJsonElement(query))
            put("page_type", Json.encodeToJsonElement(pageType))
        }
    }

    /** Product page variant */
    @Serializable
    data class CaseProduct(
        /** Product identifier */
        @SerialName("product_id")
        val productId: PropertyProductId
    ) : CustomTypePageContext() {
        /** Type of page */
        @SerialName("page_type")
        override val pageType: PropertyPageType = "product"
        override val _jsonElement: JsonElement = buildJsonObject {
            put("product_id", Json.encodeToJsonElement(productId))
            put("page_type", Json.encodeToJsonElement(pageType))
        }
    }

    /** Home page variant with no additional properties */
    @Serializable
    class CaseHome() : CustomTypePageContext() {
        /** Type of page */
        @SerialName("page_type")
        override val pageType: PropertyPageType = "home"
        override val _jsonElement: JsonElement = buildJsonObject {
            put("page_type", Json.encodeToJsonElement(pageType))
        }
    }

    /** Default case */
    @Serializable
    data class Default(
        /** Additional page data */
        @SerialName("page_data")
        val pageData: PropertyPageData? = null,

        /** Type of page */
        @SerialName("page_type")
        override val pageType: PropertyPageType
    ) : CustomTypePageContext() {
        override val _jsonElement: JsonElement = buildJsonObject {
            pageData?.let { put("page_data", Json.encodeToJsonElement(it)) }
            put("page_type", Json.encodeToJsonElement(pageType))
        }
    }
}

private object RudderCustomTypePageContextSerializer : SealedClassJsonSerializer<CustomTypePageContext>()

/** User access with variants based on active status */
@Serializable(with = RudderCustomTypeUserAccessSerializer::class)
sealed class CustomTypeUserAccess : SealedClassWithJson {
    /** User active status */
    @SerialName("active")
    abstract val active: PropertyActive
    abstract override val _jsonElement: JsonElement

    /** Active user access */
    @Serializable
    data class CaseTrue(
        /** User's email address */
        @SerialName("email")
        val email: PropertyEmail
    ) : CustomTypeUserAccess() {
        /** User active status */
        @SerialName("active")
        override val active: PropertyActive = true
        override val _jsonElement: JsonElement = buildJsonObject {
            put("email", Json.encodeToJsonElement(email))
            put("active", Json.encodeToJsonElement(active))
        }
    }

    /** Inactive user access */
    @Serializable
    data class CaseFalse(
        /** User account status */
        @SerialName("status")
        val status: PropertyStatus
    ) : CustomTypeUserAccess() {
        /** User active status */
        @SerialName("active")
        override val active: PropertyActive = false
        override val _jsonElement: JsonElement = buildJsonObject {
            put("status", Json.encodeToJsonElement(status))
            put("active", Json.encodeToJsonElement(active))
        }
    }

    /** Default case */
    @Serializable
    data class Default(
        /** User active status */
        @SerialName("active")
        override val active: PropertyActive
    ) : CustomTypeUserAccess() {
        override val _jsonElement: JsonElement = buildJsonObject {
            put("active", Json.encodeToJsonElement(active))
        }
    }
}

private object RudderCustomTypeUserAccessSerializer : SealedClassJsonSerializer<CustomTypeUserAccess>()

/** Item type for array_with_null_items array */
@Serializable(with = RudderArrayItemArrayWithNullItemsSerializer::class)
sealed class ArrayItemArrayWithNullItems : SealedClassWithJson {
    abstract override val _jsonElement: JsonElement
    /** Represents a 'string' value */
    @Serializable
    data class StringValue(
        @SerialName("value")
        val value: String
    ) : ArrayItemArrayWithNullItems() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }

    /** Represents a 'null' value */
    @Serializable
    data class NullValue(
        @SerialName("value")
        val value: JsonNull
    ) : ArrayItemArrayWithNullItems() {

        override val _jsonElement: JsonElement = value
    }
}

private object RudderArrayItemArrayWithNullItemsSerializer : SealedClassJsonSerializer<ArrayItemArrayWithNullItems>()

/** Feature flag that can be boolean or string */
@Serializable(with = RudderPropertyFeatureFlagSerializer::class)
sealed class PropertyFeatureFlag : SealedClassWithJson {
    abstract override val _jsonElement: JsonElement
    /** Represents a 'boolean' value */
    @Serializable
    data class BooleanValue(
        @SerialName("value")
        val value: Boolean
    ) : PropertyFeatureFlag() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }

    /** Represents a 'string' value */
    @Serializable
    data class StringValue(
        @SerialName("value")
        val value: String
    ) : PropertyFeatureFlag() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }
}

private object RudderPropertyFeatureFlagSerializer : SealedClassJsonSerializer<PropertyFeatureFlag>()

/** Item type for multi_type_array array */
@Serializable(with = RudderArrayItemMultiTypeArraySerializer::class)
sealed class ArrayItemMultiTypeArray : SealedClassWithJson {
    abstract override val _jsonElement: JsonElement
    /** Represents a 'string' value */
    @Serializable
    data class StringValue(
        @SerialName("value")
        val value: String
    ) : ArrayItemMultiTypeArray() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }

    /** Represents a 'integer' value */
    @Serializable
    data class IntegerValue(
        @SerialName("value")
        val value: Long
    ) : ArrayItemMultiTypeArray() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }
}

private object RudderArrayItemMultiTypeArraySerializer : SealedClassJsonSerializer<ArrayItemMultiTypeArray>()

/** A field that can be string, integer, or boolean */
@Serializable(with = RudderPropertyMultiTypeFieldSerializer::class)
sealed class PropertyMultiTypeField : SealedClassWithJson {
    abstract override val _jsonElement: JsonElement
    /** Represents a 'string' value */
    @Serializable
    data class StringValue(
        @SerialName("value")
        val value: String
    ) : PropertyMultiTypeField() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }

    /** Represents a 'integer' value */
    @Serializable
    data class IntegerValue(
        @SerialName("value")
        val value: Long
    ) : PropertyMultiTypeField() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }

    /** Represents a 'boolean' value */
    @Serializable
    data class BooleanValue(
        @SerialName("value")
        val value: Boolean
    ) : PropertyMultiTypeField() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }
}

private object RudderPropertyMultiTypeFieldSerializer : SealedClassJsonSerializer<PropertyMultiTypeField>()

/** Property that can be string, integer, or null */
@Serializable(with = RudderPropertyMultiTypeWithNullSerializer::class)
sealed class PropertyMultiTypeWithNull : SealedClassWithJson {
    abstract override val _jsonElement: JsonElement
    /** Represents a 'string' value */
    @Serializable
    data class StringValue(
        @SerialName("value")
        val value: String
    ) : PropertyMultiTypeWithNull() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }

    /** Represents a 'integer' value */
    @Serializable
    data class IntegerValue(
        @SerialName("value")
        val value: Long
    ) : PropertyMultiTypeWithNull() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }

    /** Represents a 'null' value */
    @Serializable
    data class NullValue(
        @SerialName("value")
        val value: JsonNull
    ) : PropertyMultiTypeWithNull() {

        override val _jsonElement: JsonElement = value
    }
}

private object RudderPropertyMultiTypeWithNullSerializer : SealedClassJsonSerializer<PropertyMultiTypeWithNull>()

/** Property that can be number or null */
@Serializable(with = RudderPropertyNumberOrNullSerializer::class)
sealed class PropertyNumberOrNull : SealedClassWithJson {
    abstract override val _jsonElement: JsonElement
    /** Represents a 'number' value */
    @Serializable
    data class NumberValue(
        @SerialName("value")
        val value: Double
    ) : PropertyNumberOrNull() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }

    /** Represents a 'null' value */
    @Serializable
    data class NullValue(
        @SerialName("value")
        val value: JsonNull
    ) : PropertyNumberOrNull() {

        override val _jsonElement: JsonElement = value
    }
}

private object RudderPropertyNumberOrNullSerializer : SealedClassJsonSerializer<PropertyNumberOrNull>()

/** Property that can be string or null */
@Serializable(with = RudderPropertyStringOrNullSerializer::class)
sealed class PropertyStringOrNull : SealedClassWithJson {
    abstract override val _jsonElement: JsonElement
    /** Represents a 'string' value */
    @Serializable
    data class StringValue(
        @SerialName("value")
        val value: String
    ) : PropertyStringOrNull() {

        override val _jsonElement: JsonElement = JsonPrimitive(value)
    }

    /** Represents a 'null' value */
    @Serializable
    data class NullValue(
        @SerialName("value")
        val value: JsonNull
    ) : PropertyStringOrNull() {

        override val _jsonElement: JsonElement = value
    }
}

private object RudderPropertyStringOrNullSerializer : SealedClassJsonSerializer<PropertyStringOrNull>()

/** Example event to demonstrate variants */
@Serializable(with = RudderTrackEventWithVariantsPropertiesSerializer::class)
sealed class TrackEventWithVariantsProperties : SealedClassWithJson {
    /** Type of device */
    @SerialName("device_type")
    abstract val deviceType: PropertyDeviceType
    abstract override val _jsonElement: JsonElement

    /** Mobile device page view */
    @Serializable
    data class CaseMobile(
        /** Page context information */
        @SerialName("page_context")
        val pageContext: PropertyPageContext? = null,

        /** User profile data */
        @SerialName("profile")
        val profile: PropertyProfile,

        /** User tags as array of strings */
        @SerialName("tags")
        val tags: PropertyTags? = null
    ) : TrackEventWithVariantsProperties() {
        /** Type of device */
        @SerialName("device_type")
        override val deviceType: PropertyDeviceType = PropertyDeviceType.MOBILE
        override val _jsonElement: JsonElement = buildJsonObject {
            pageContext?.let { put("page_context", Json.encodeToJsonElement(it)) }
            put("profile", Json.encodeToJsonElement(profile))
            tags?.let { put("tags", Json.encodeToJsonElement(it)) }
            put("device_type", Json.encodeToJsonElement(deviceType))
        }
    }

    /** Desktop page view */
    @Serializable
    data class CaseDesktop(
        /** User's first name */
        @SerialName("first_name")
        val firstName: PropertyFirstName,

        /** User's last name */
        @SerialName("last_name")
        val lastName: PropertyLastName? = null,

        /** Page context information */
        @SerialName("page_context")
        val pageContext: PropertyPageContext? = null,

        /** User profile data */
        @SerialName("profile")
        val profile: PropertyProfile
    ) : TrackEventWithVariantsProperties() {
        /** Type of device */
        @SerialName("device_type")
        override val deviceType: PropertyDeviceType = PropertyDeviceType.DESKTOP
        override val _jsonElement: JsonElement = buildJsonObject {
            put("first_name", Json.encodeToJsonElement(firstName))
            lastName?.let { put("last_name", Json.encodeToJsonElement(it)) }
            pageContext?.let { put("page_context", Json.encodeToJsonElement(it)) }
            put("profile", Json.encodeToJsonElement(profile))
            put("device_type", Json.encodeToJsonElement(deviceType))
        }
    }

    /** Default case */
    @Serializable
    data class Default(
        /** Type of device */
        @SerialName("device_type")
        override val deviceType: PropertyDeviceType,

        /** Page context information */
        @SerialName("page_context")
        val pageContext: PropertyPageContext? = null,

        /** User profile data */
        @SerialName("profile")
        val profile: PropertyProfile,

        /** A field with no explicit type (treated as any) */
        @SerialName("untyped_field")
        val untypedField: PropertyUntypedField? = null
    ) : TrackEventWithVariantsProperties() {
        override val _jsonElement: JsonElement = buildJsonObject {
            put("device_type", Json.encodeToJsonElement(deviceType))
            pageContext?.let { put("page_context", Json.encodeToJsonElement(it)) }
            put("profile", Json.encodeToJsonElement(profile))
            untypedField?.let { put("untyped_field", Json.encodeToJsonElement(it)) }
        }
    }
}

private object RudderTrackEventWithVariantsPropertiesSerializer : SealedClassJsonSerializer<TrackEventWithVariantsProperties>()

/** User profile information */
@Serializable
data class CustomTypeUserProfile(
    /** User's email address */
    @SerialName("email")
    val email: PropertyEmail,

    /** User's first name */
    @SerialName("first_name")
    val firstName: PropertyFirstName,

    /** User's last name */
    @SerialName("last_name")
    val lastName: PropertyLastName? = null
)

/** Group association event */
@Serializable
data class GroupTraits(
    /** User active status */
    @SerialName("active")
    val active: PropertyActive
)

/** User identification event */
@Serializable
data class IdentifyTraits(
    /** User active status */
    @SerialName("active")
    val active: PropertyActive? = null,

    /** User's email address */
    @SerialName("email")
    val email: PropertyEmail
)

/** Page view event */
@Serializable
data class PageProperties(
    /** User profile data */
    @SerialName("profile")
    val profile: PropertyProfile
)

/** Screen view event */
@Serializable
data class ScreenProperties(
    /** User profile data */
    @SerialName("profile")
    val profile: PropertyProfile? = null
)

/** Triggered when user clicks on a "premium" product /\* important *\/ */
@Serializable
data class TrackProductPremiumClickedProperties(
    /** Field with special chars: "quotes", backslash\path, and /\* comment *\/ */
    @SerialName("special_field")
    val specialField: PropertySpecialField,

    /** HTTP status with special characters */
    @SerialName("status_code")
    val statusCode: PropertyStatusCode? = null
)

/** Triggered when a user signs up */
@Serializable
data class TrackUserSignedUpProperties(
    /** User active status */
    @SerialName("active")
    val active: PropertyActive,

    /** User's age */
    @SerialName("age")
    val age: PropertyAge? = null,

    /** An array that can contain any type of items */
    @SerialName("array_of_any")
    val arrayOfAny: PropertyArrayOfAny? = null,

    /** Array with items that can be string or null */
    @SerialName("array_with_null_items")
    val arrayWithNullItems: PropertyArrayWithNullItems? = null,

    /** Array of user contacts */
    @SerialName("contacts")
    val contacts: PropertyContacts? = null,

    /** example of object property */
    @SerialName("context")
    val context: TrackUserSignedUpProperties.Context? = null,

    /** Property using custom null type */
    @SerialName("custom_null_field")
    val customNullField: PropertyCustomNullField? = null,

    /** Type of device */
    @SerialName("device_type")
    val deviceType: PropertyDeviceType? = null,

    /** User's email addresses */
    @SerialName("email_list")
    val emailList: PropertyEmailList? = null,

    /** Property with empty object not allowing additional properties */
    @SerialName("empty_object_no_additional_props")
    val emptyObjectNoAdditionalProps: PropertyEmptyObjectNoAdditionalProps? = null,

    /** Property with empty object allowing additional properties */
    @SerialName("empty_object_with_additional_props")
    val emptyObjectWithAdditionalProps: PropertyEmptyObjectWithAdditionalProps? = null,

    /** Feature enabled flag */
    @SerialName("enabled")
    val enabled: PropertyEnabled? = null,

    /** Feature configuration information */
    @SerialName("feature_config")
    val featureConfig: PropertyFeatureConfig? = null,

    /** Property with mixed unicode: café, naïve, 日本語 */
    @SerialName("mixed_unicode")
    val mixedUnicode: PropertyMixedUnicode? = null,

    /** Mixed type enum */
    @SerialName("mixed_value")
    val mixedValue: PropertyMixedValue? = null,

    /** An array with items that can be string or integer */
    @SerialName("multi_type_array")
    val multiTypeArray: PropertyMultiTypeArray? = null,

    /** A field that can be string, integer, or boolean */
    @SerialName("multi_type_field")
    val multiTypeField: PropertyMultiTypeField? = null,

    /** Property that can be string, integer, or null */
    @SerialName("multi_type_with_null")
    val multiTypeWithNull: PropertyMultiTypeWithNull? = null,

    /** Nested property with empty object allowing additional properties */
    @SerialName("nested_empty_object")
    val nestedEmptyObject: PropertyNestedEmptyObject? = null,

    /** Nested property with empty object not allowing additional properties */
    @SerialName("nested_empty_object_no_additional_props")
    val nestedEmptyObjectNoAdditionalProps: Unit? = null,

    /** Property that is always null */
    @SerialName("null_field")
    val nullField: PropertyNullField? = null,

    /** Property that can be number or null */
    @SerialName("number_or_null")
    val numberOrNull: PropertyNumberOrNull? = null,

    /** An object field with no defined structure */
    @SerialName("object_property")
    val objectProperty: PropertyObjectProperty? = null,

    /** Priority level */
    @SerialName("priority")
    val priority: PropertyPriority? = null,

    /** User profile data */
    @SerialName("profile")
    val profile: PropertyProfile,

    /** List of related user profiles */
    @SerialName("profile_list")
    val profileList: PropertyProfileList? = null,

    /** A field that can contain any type of value */
    @SerialName("property_of_any")
    val propertyOfAny: PropertyPropertyOfAny? = null,

    /** Rating value */
    @SerialName("rating")
    val rating: PropertyRating? = null,

    /** User account status */
    @SerialName("status")
    val status: PropertyStatus? = null,

    /** Property that can be string or null */
    @SerialName("string_or_null")
    val stringOrNull: PropertyStringOrNull? = null,

    /** User tags as array of strings */
    @SerialName("tags")
    val tags: PropertyTags? = null,

    /** Property using custom type with Unicode */
    @SerialName("unicode_custom_type")
    val unicodeCustomType: PropertyUnicodeCustomType? = null,

    /** Field demonstrating various Unicode characters in enum values */
    @SerialName("unicode_enum_field")
    val unicodeEnumField: PropertyUnicodeEnumField? = null,

    /** An array with no explicit item type (treated as any) */
    @SerialName("untyped_array")
    val untypedArray: PropertyUntypedArray? = null,

    /** A field with no explicit type (treated as any) */
    @SerialName("untyped_field")
    val untypedField: PropertyUntypedField? = null,

    /** User access information */
    @SerialName("user_access")
    val userAccess: PropertyUserAccess? = null,

    /** Username in Chinese characters */
    @SerialName("用户名")
    val 用户名: Property用户名? = null
) {
    /** example of object property */
    @Serializable
    data class Context(
        /** IP address of the user */
        @SerialName("ip_address")
        val ipAddress: PropertyIpAddress,

        /** demonstrates multiple levels of nesting */
        @SerialName("nested_context")
        val nestedContext: TrackUserSignedUpProperties.Context.NestedContext
    ) {
        /** demonstrates multiple levels of nesting */
        @Serializable
        data class NestedContext(
            /** User profile data */
            @SerialName("profile")
            val profile: PropertyProfile? = null
        )
    }
}

class RudderAnalytics(private val analytics: Analytics) {
    private val json = Json {
        prettyPrint = true
        encodeDefaults = false
    }

    private val context = buildJsonObject {
        put("ruddertyper", buildJsonObject {
            put("platform", "kotlin")
            put("rudderCLIVersion", "1.0.0")
            put("trackingPlanId", "plan_12345")
            put("trackingPlanVersion", 13)
        })
    }

    /**
     * Group association event
     */
    fun group(groupId: String, traits: GroupTraits) {
        analytics.group(
            groupId = groupId,
            traits = json.encodeToJsonElement(traits).jsonObject,
            options = RudderOption(customContext = context)
        )
    }

    /**
     * User identification event
     */
    fun identify(userId: String = "", traits: IdentifyTraits) {
        analytics.identify(
            userId = userId,
            traits = json.encodeToJsonElement(traits).jsonObject,
            options = RudderOption(customContext = context)
        )
    }

    /**
     * Screen view event
     */
    fun screen(screenName: String, category: String = "", properties: ScreenProperties) {
        analytics.screen(
            screenName = screenName,
            category = category,
            properties = json.encodeToJsonElement(properties).jsonObject,
            options = RudderOption(customContext = context)
        )
    }

    /**
     * Empty event schema with additionalProperties false
     */
    fun trackEmptyEventNoAdditionalProps() {
        analytics.track(
            name = "Empty Event No Additional Props",
            options = RudderOption(customContext = context)
        )
    }

    /**
     * Empty event schema with additionalProperties true
     */
    fun trackEmptyEventWithAdditionalProps(properties: TrackEmptyEventWithAdditionalPropsProperties) {
        analytics.track(
            name = "Empty Event With Additional Props",
            properties = json.encodeToJsonElement(properties).jsonObject,
            options = RudderOption(customContext = context)
        )
    }

    /**
     * Example event to demonstrate variants
     */
    fun trackEventWithVariants(properties: TrackEventWithVariantsProperties) {
        analytics.track(
            name = "Event With Variants",
            properties = json.encodeToJsonElement(properties).jsonObject,
            options = RudderOption(customContext = context)
        )
    }

    /**
     * Triggered when user clicks on a "premium" product /\* important *\/
     */
    fun trackProductPremiumClicked(properties: TrackProductPremiumClickedProperties) {
        analytics.track(
            name = "Product \"Premium\" Clicked",
            properties = json.encodeToJsonElement(properties).jsonObject,
            options = RudderOption(customContext = context)
        )
    }

    /**
     * Triggered when a user signs up
     */
    fun trackUserSignedUp(properties: TrackUserSignedUpProperties) {
        analytics.track(
            name = "User Signed Up",
            properties = json.encodeToJsonElement(properties).jsonObject,
            options = RudderOption(customContext = context)
        )
    }
}